### ISSUE TITLE
Missing Readme file.

### ISSUE THREAD

**Issue by divarvel** [Geal/nom#1]
Steps to reproduce: try reading the Readme file.

Expected result: the readme file explains what this is about.
Actual result: there is no readme file.

**Comment by Geal** [comment]
closed by e2b04635c99bc63

Na!

**Comment by divarvel** [comment]
![<http://clementd-files.cellar-c1.clvrcld.net/lol/viewer.html#/lol/i-accept-that.webm>](http://clementd-files.cellar-c1.clvrcld.net/lol/thumbs/i-accept-that.jpg)
