### ISSUE TITLE
flat_map is to strict

### ISSUE THREAD

**Issue by adamAndMath** [Geal/nom#1000]
In nom 5.0 [flat_map](https://docs.rs/nom/5.0.0/nom/combinator/fn.flat_map.html)'s second parameter returns a `Fn`, but it could just as well return a `FnOnce`

**Comment by Geal** [comment]
why do you need it to be a `FnOnce` ?

**Comment by adamAndMath** [comment]
Needed to forward non copy information

**Comment by Geal** [comment]
Could you give me more details so I can understand ? Code example, etc

**Comment by adamAndMath** [comment]
I have a range-like syntax that accepts `x-y` and `x+`, cosponsoring to `x..=y` and `x..` in rust. I don't want to re-pass `x` if the first case fails, so I want to do something like
```rust
flat_map(pair(usize::parse, anychar), |(from, c)|move|i|match c {
    '-' => map(usize::parse, |to|LevelRange::Closed(from, to))(i),
    '+' => Ok((i, LevelRange::Open(from))),
    _ => Err(nom::Err::Error(make_error(i, ErrorKind::Alt))),
})
```
In this case I could copy the value, but I have other similar cases where that isn't possible and there are more variants.

**Comment by koutheir** [comment]
The `*map()` operation itself does not call its given lambda more than once, which makes it enough to use the `FnOnce` bound (i.e., the `Fn` bound is too strict in this context). However, if the `*map()` operation itself is called multiple times (for example, in a sequence), then this might result in the given lambda being called multiple times, which would violate `FnOnce`, and require `Fn`.

**Comment by adamAndMath** [comment]
The difference is that the closure produced in `flat_map` is produced and consumed per call to the parser. So for `flat_map` you could still call it multiple times, unlike `map`

**Comment by Geal** [comment]
with 84d1ac025ba2 the trait bound is `FnMut`, this should be testable soon

**Comment by Geal** [comment]
nom 6 is released now :partying_face:
