### ISSUE TITLE
Parsing least significant bits first?

### ISSUE THREAD

**Issue by mpizenberg** [Geal/nom#1005]
- Rust version : 1.36.0
- nom version : 5.0.0

For a [PNG decoder](https://github.com/mpizenberg/png-decoder) I'm writing with nom, I need to implement a deflate decoder ("inflate"). According to [DEFLATE spec](https://tools.ietf.org/html/rfc1951) bits are packed into bytes with least significant bit first. As a human we would note the bit indices like so: [7|6|5|4|3|2|1|0].

I've tried to use nom's bit parsers, but from the following simple program, it seems that nom parses bits with most significant bit first (reverse order compared to deflate spec). Is there another set of functions for parsing bits in increasing significance order that I didn't find?

```
use nom::bits::bits;
use nom::bits::complete::take;
use nom::IResult;

fn main() {
    match first_bit(&ONE[1..]) {
        Ok((_, n)) => println!("{:?}", n),
        Err(e) => eprintln!("{:?}", e),
    };
}

const ONE: &[u8] = &[1, 128];

fn first_bit(input: &[u8]) -> IResult<&[u8], u8> {
    bits::<_, _, (_, _), _, _>(take(1_usize))(input)
}
```

**Comment by mpizenberg** [comment]
I've tried to adapt what I read in the `nom::bits::complete::take` function. I think the following `take_increasing` function should work according to some manual testing. I'll see if I manage to implement the decoding with it (might take some time ^^).
```rust
pub fn take_increasing<I, O, C, E: ParseError<(I, usize)>>(
    count: C,
) -> impl Fn((I, usize)) -> IResult<(I, usize), O, E>
where
    I: Slice<RangeFrom<usize>> + InputIter<Item = u8> + InputLength,
    C: ToUsize,
    O: From<u8> + AddAssign + Shl<usize, Output = O> + Shr<usize, Output = O>,
{
    let count = count.to_usize();
    move |(input, bit_offset): (I, usize)| {
        if count == 0 {
            Ok(((input, bit_offset), 0u8.into()))
        } else {
            let cnt = (count + bit_offset).div(8);
            if input.input_len() * 8 < count + bit_offset {
                Err(Err::Error(E::from_error_kind(
                    (input, bit_offset),
                    ErrorKind::Eof,
                )))
            } else {
                let mut acc: O = (0 as u8).into();
                let mut acc_nb: usize = 0;
                let mut offset: usize = bit_offset;
                let mut remaining: usize = count;
                let mut end_offset: usize = 0;

                for byte in input.iter_elements().take(cnt + 1) {
                    if remaining == 0 {
                        break;
                    }

                    // overflow = negative underflow
                    let underflow: isize = 8 - offset as isize - remaining as isize;

                    // val contains our bits in this byte,
                    // with higher significance bits set to 0 (left padded)
                    let val: O = if underflow < 0 {
                        byte.into()
                    } else {
                        ((byte << underflow) >> underflow).into()
                    };

                    if offset > 0 {
                        // necessarily the beginning of bit retrieving
                        acc = val >> offset;
                    } else {
                        // the val has higher weight (more significant bits)
                        acc += val << acc_nb;
                    }

                    if underflow > 0 {
                        // we just need to update end_offset if no overflow
                        end_offset = remaining + offset;
                        break;
                    } else {
                        acc_nb += 8 - offset;
                        remaining -= 8 - offset;
                        offset = 0;
                    }
                }
                Ok(((input.slice(cnt..), end_offset), acc))
            }
        }
    }
}
```

**Comment by bgourlie** [comment]
I was attempting to decode a bitstream for a not-super-well-documented format, comparing it to a reference implementation and banging my head at the different results. Turns out, the reference implementation was decoding bits least-significant-to-most-significant. Anyhow, after plugging in @mpizenberg's implementation it appears to be working as I'd expect. 

+1 to having the ability to configure bit-endianness

**Comment by Geal** [comment]
with nom 6 you'll be able to use [bitvec](https://crates.io/crates/bitvec)'s [BitSlice type](https://github.com/Geal/nom/blob/b4b1a04dcf99d6673c8e576172eb1eccbdd4b1d4/tests/bitstream.rs#L11) that can have configurable endianness

**Comment by Geal** [comment]
closing this for now, as nom 6 is now releaed, please ping me if there's anything else

**Comment by Tandolf** [comment]
> with nom 6 you'll be able to use [bitvec](https://crates.io/crates/bitvec)'s [BitSlice type](https://github.com/Geal/nom/blob/b4b1a04dcf99d6673c8e576172eb1eccbdd4b1d4/tests/bitstream.rs#L11) that can have configurable endianness

This bridge between nom and bitvec is broken, since the bitvec version in it too old. There are open PRs that fixes this since a year back, are there any plans on merging these PRs so that nom_bitvec works again?
