### ISSUE TITLE
alt and pair cannot be used together

### ISSUE THREAD

**Issue by SephVelut** [Geal/nom#1006]
Using `alt` in combination with `pair` results in:

```
error[E0271]: type mismatch resolving `<impl std::ops::Fn<(_,)> as std::ops::FnOnce<(_,)>>::Output == std::re
sult::Result<(_, (_, _)), nom::Err<_>>`
   --> src/lib.rs:327:9
    |
327 |         alt(( pair(tag("a"), tag("q")), tag("a") ))(input);
    |         ^^^ cyclic type of infinite size
    |
    = note: required because of the requirements on the impl of `nom::branch::Alt<_, (_, _), _>` for `(impl s
td::ops::Fn<(_,)>, impl std::ops::Fn<(_,)>)`
    = note: required by `nom::branch::alt`
```

`alt(( pair(tag("a"), tag("q")), tag("a") ))(input);`

**Comment by Geal** [comment]
all the parsers passed to `alt` must have the same input and output types, but here `pair(tag("a"), tag("q"))` returns a `(&[u8], &[u8])` while `tag("a")` returns a `&[u8]`.  It will compile fine with `alt(( pair(tag("a"), tag("q")), pair(tag("a"), tag("b")) )`.
As to why the compiler shows that error message, huuuuh, I have no idea, I've never seen that before :D

**Comment by SephVelut** [comment]
Ah I see. I was able to navigate the returns in `alt` by using `map` and `map_parser` to align the homunculus types to a one canonical type. I don't know if it's appropriate to keep this issue open for cyclical error, as it may not be related to nom so I will close for now.
