### ISSUE TITLE
`fold_many1` (and some others) now requires `Clone` attribute

### ISSUE THREAD

**Issue by chifflier** [Geal/nom#1008]
- Rust version : 1.36
- nom version : 5.0

`fold_many1` now requires init/return value to have `Clone`, which is annoying when it can be a complex type (and you don't want to clone it).

It was not the case with nom 4.

## Test case

```rust
struct TypeWithoutClone {
    pub a: u32,
}

named!(multi<&[u8], Vec<TypeWithoutClone>>,
    fold_many1!( tag!( "abcd" ), Vec::new(), |mut acc: Vec<_>, item| {
        acc.push( TypeWithoutClone{ a: 0 } );
        acc
    })
);
```

Nom 4 build: no error

Nom 5 build:
```
error[E0277]: the trait bound `TypeWithoutClone: std::clone::Clone` is not satisfied
  --> src/lib.rs:14:1
   |
14 | / named!(multi<&[u8], Vec<TypeWithoutClone>>,
15 | |     fold_many1!( tag!( "abcd" ), Vec::new(), |mut acc: Vec<_>, item| {
16 | |         acc.push( TypeWithoutClone{ a: 0 } );
17 | |         acc
18 | |     })
19 | | );
   | |__^ the trait `std::clone::Clone` is not implemented for `TypeWithoutClone`
   |
   = note: required because of the requirements on the impl of `std::clone::Clone` for `std::vec::Vec<TypeWithoutClone>`
   = note: required by `nom::multi::fold_many1c`
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

**Comment by ebkalderon** [comment]
Agreed. Seems that `fold_many0()` and `fold_many1()` do the same, so I have switched to a manual combination of `many0()` and `map()` to improve performance on my end. Is there a particular reason why the `R: Clone` requirement was introduced in `nom` 5.0? CC @Geal

**Comment by ebkalderon** [comment]
Vendoring the `fold_many0()` combinator in a personal project, changing it to return an `impl FnOnce(I) -> IResult<I, O, E>`, and removing the `R: Clone` bound and `clone()` call seems to produce the desired result. The parser compiles and works as expected, but naturally, the disadvantage of using `FnOnce` is that the closure produced by the combinator can only be called once.

**Comment by dougabugg** [comment]
Just ran into this today. In the context of `fold_many0`, wouldn't it make more sense for argument `init` to have type `T` where `T: Fn() -> R` and remove the requirement of `R: Clone`?

**Comment by cenodis** [comment]
To add to @ebkalderon solution.
Its possible to make the Parser return `impl Fn(I) -> IResult<I, O, E>` again by using a function that supplies the initial accumulator `init: Fn() -> R` instead of passing it directly to the function. `fold_*` can then call this supplier from within the parser function to get a new accumulator making it `Fn` instead of `FnOnce`.
I have tested this briefly and found no issue with it.
[Example of modified `fold_many0` function.](https://gist.github.com/cenodis/f66e9f45eb304e3d7e31959b5df85101)

**Comment by Geal** [comment]
@cenodis that's a good approach, it eliminates the Clone trait bound with minimal modifications in code using fold_many0
