### ISSUE TITLE
combining steaming and complete iterators

### ISSUE THREAD

**Issue by vandenoever** [Geal/nom#1013]
This is a question about nom, since I did not find a support / discussion channel.

I've ported by Turtle parser to nom 5. It's parses the complete string. I'd like to make it into a streaming parser. However, there is no production to signal the end of the data. So the streaming parser can end on Needed(1). I see two solutions:
 - send the last bytes with an additional \n to the streaming parser
 - create all productions in steaming and complete form. This could be done by wrapping the definitions in a macro or make my own named! macro that defines everything twice.

The latter is a lot of code overhead but is cleaner. Any suggestions are welcome.

**Comment by Geal** [comment]
without any more information about the format, it will be hard to give advice. If you want to transform a complete parser in a streaming one without too many modifications, an easy way would be to make everything in streaming mode, except for the last parser in the list. But if the format really does not has an end token, it will not work properly in streaming
