### ISSUE TITLE
Combination of delimited/escaped parsers run indefinitely

### ISSUE THREAD

**Issue by bgourlie** [Geal/nom#1014]
I'm trying to parse a string literal (`"some ~text~")` that allows for escaping `\` and `"` characters. The parser I've come up with runs indefinitely. 
 
- Rust version : rustc 1.36.0 (a53f9df32 2019-07-03)
- nom version : 5.0.0
- nom compilation features used: default

## Test case

```rust
use nom::bytes::complete::{escaped, take_while};
use nom::character::complete::{char, one_of};
use nom::sequence::delimited;
use nom::IResult;

pub fn main() {
    assert_eq!(
        string_literal("\"PaRsInG ~is~ cool\""),
        Ok(("", "PaRsInG ~is~ cool"))
    );
}

fn string_literal(input: &str) -> IResult<&str, &str> {
    delimited(
        char('"'),
        escaped(
            take_while(|chr| chr != '"' && chr >= ' ' && chr <= '~'),
            '\\',
            one_of("\\\""),
        ),
        char('"'),
    )(input)
}
```

**Comment by Geal** [comment]
what happens if you use `take_while1` instead of `take_while`? It might be that the parser goes into an infinite loop trying to go further than the first tilde

**Comment by mpizenberg** [comment]
I just faced the same problem and can confirm that using a parser that takes at least 1 character solves the infinite loop issue. This prevents parsing empty strings however so we can combine it with an empty string parser. Here is what I have for example:
```rust
fn string_literal(input: &str) -> IResult<&str, &str> {
    delimited(
        char('"'),
        alt((
            escaped(take_till1(|c| c == '\\' || c == '"'), '\\', one_of(r#""\"#)),
            success(""),
        )),
        char('"'),
    )(input)
}
```

**Comment by izderadicka** [comment]
@geal -   I had exactly same issue and it took me while to understand that I need `take_while1` instead of `take_while`.  I think it would worth to mention it in `escaped` documentation - that normal parser should take at least one byte/char or there will be infinite loop
