### ISSUE TITLE
Request: implement `InputTake` and `InputLength` on `proc_macro2::TokenStream`

### ISSUE THREAD

**Issue by rbalicki2** [Geal/nom#1017]
## Prerequisites

- Rust version : `rustc 1.37.0-nightly (8ebd67e4e 2019-06-27)`
- nom version : 5
- nom compilation features used: None

## Request

Hello! I was wondering, would it be possible to implement `InputTake` and `InputLength` on a proc_macro2 TokenStream?

I am not sure what issues there are with using nom directly with procedural macros, but TBH I would like to be able to take advantage of the features that TokenStreams give us: spans, automatic parsing into groups, etc.

Thank you!

**Comment by Geal** [comment]
for cases like this, it's better to have a newtype in your crate (ie, `struct MyTokenStream(proc_macro2::TokenStream)`) on which you would implement the trait
