### ISSUE TITLE
macros are very whitespace-sensitive when defining functions with type parameters

### ISSUE THREAD

**Issue by doy** [Geal/nom#102]
It's unclear how much of this is the fault of nom vs rust's macro system, but it has tripped me up a couple times, especially since the error message is very misleading:

```
#[macro_use]
extern crate nom;

pub mod foo {
    pub struct Command<T> { t: T }
    named!(
        // this will error unless there is a space between the >s
        my_tag<Command<u8>>,
        map!(tag!("foo"), |_| { Command { t: 0 } })
    );

    pub fn regex_test() {
        let _ = my_tag(b"foo");
    }
}
```

gives

```
src/lib.rs:8:16: 8:23 error: expected an item keyword
src/lib.rs:8         my_tag<Command<u8>>,
                            ^~~~~~~
```

**Comment by Geal** [comment]
This comes from Rust's macro parser. Unfortunately, I cannot do anything about it. If you insert a space, like this:  `my_tag<Command<u8> >`, it will work.

The only thing I can do for now is documenting it in the README for future users ( cf 038190e ).

**Comment by keeperofdakeys** [comment]
This is the upstream rust bug, which looks like it might be getting fixed soon. https://github.com/rust-lang/rust/issues/25274
