### ISSUE TITLE
Date Time support for parsing validating from different chronology and calendar

### ISSUE THREAD

**Issue by omac777** [Geal/nom#1020]
I do appreciate the work placed into the date time parsing for iso8601:
https://github.com/badboy/iso8601

I do hope somebody places consideration to build a parser/validator adding concepts such as chronology and calendar which may be entirely different.
https://docs.oracle.com/javase/8/docs/api/java/time/chrono/Chronology.html
https://www.joda.org/joda-time/

I did observe parsing is insufficient because although a simplistic range of 1 to 31 for days seems valid, it is not when regarding the leap years and such.  The parser would need some more capability for validation.

The validation ideally should have some familiarity with the above concepts of chronology and calendar.  I appreciate having the iso standard, but humanity's history is a bit more complicated than that and the other programming languages reflect some consideration for that.  I'm surprised to see that none of these concepts reside in the default internals of the rust language itself.

I am also implying that the parser nom could provide some kind of validating infrastructure alongside.  Parsing correct grammars is great, but I believe once the grammar is parsed some kind of support of helping to validate the different grammar parts for their intended use yes does fall into the nom user's hands, but a little guidance from nom itself would be helpful.
Perhaps more samples regarding that i.e. validating with datetime.

**Comment by Geal** [comment]
there's usually not issue in validating data as it is parsed, with combinators like [verify](https://docs.rs/nom/5.0.0/nom/combinator/fn.verify.html), but it's often better to do it as a separate pass, especially for complex data like dates.
Note though that this repository is only about the nom parser combinators library, and this library will not include a date parser in its API
