### ISSUE TITLE
Documentation for use paths

### ISSUE THREAD

**Issue by IceTDrinker** [Geal/nom#1039]
Hello,

I have been using nom for a pet project and find myself spending a certain amount of time figuring out which use paths to add to my code to get access to the different combinators.

As far as I can see the docs at https://docs.rs/nom/ does not provide much information in that regard.

Currently my goto solution is to search the combinator on the repo and infer the path from the filename.

I think it could be a welcome enhancement to have this information either in the doc or in a md file in the repo.

I did not see other issues on github on this topic so I guess it was not brought up before, if it was sorry for the duplicate.

Cheers,

IceTDrinker

**Comment by Geal** [comment]
is there an issue with the search bar on docs.rs ?

**Comment by IceTDrinker** [comment]
I don’t remember, looks fine on mobile now that you mention it.

**Comment by IceTDrinker** [comment]
And I get the "search preview" on docs.rs now, I don't know what was wrong at the time, a browser extension preventing the load or me not taking the right path ? I think I might have clicked the module link on the left of the page.

Cheers :)
