### ISSUE TITLE
Feature request: match single byte or character by predicate

### ISSUE THREAD

**Issue by lo48576** [Geal/nom#1054]
## Prerequisites

- Rust version : rustc 1.38.0 (625451e37 2019-09-23)
- nom version : 5.0.1
- nom compilation features used: std

## Abstract

There seems no parser funciton provided which eats single byte or single character by the given predicate.
In other words, I want a variant of `nom::character::complete::one_of()` receiving predicates instead of a string.
(Sorry if I overlooked something.)

`nom::bytes::complete::is_a()` returns longest matched string, and `nom::character::complete::one_of()` receives list or string, so they are not I wanted.
`one_of()` is hard to use especially if I want to match many candidates or Unicode characters.

It can be written in some ways using existing nom functions, however, I think it should be provided as dedicated parser combinator.

*  `nom::bytes::complete::take_while_m_n(1, 1, pred)` for `u8`
* `nom::combinator::verify(nom::bytes::complete::take(1), |b: &[u8]| pred(b[0]))` for `u8`
* `nom::combinator::verify(nom::character::complete::anychar(), pred)` for `char`

## Typical use case

A typical use case I thought is matching a name.
Consider the following situation:

* `fn is_name_start(c: char) -> bool` returns true if `c` is valid as the first character of a name.
* `fn is_name_continue(c: char) -> bool` returns true if `c` is valid as the non-first character of a name.
* `fn char_pred<I, F, E: ParseError<I>>(pred: F) -> impl Fn(I) -> IResult<I, char, E> where ...` is `char` version of what I wanted.
* `fn variable<E: ParseError<&str>>(s: &str) -> IResult<&str, &str, E>` parses a name.

Then I want to write this as following:

```rust
fn variable<'a, E: ParseError<&'a str>>(s: &'a str) -> IResult<&'a str, &'a str, E> {
    recognize(
        pair(
            char_pred(is_name_start),
            take_while(is_name_continue),
        )
    )(s)
}
```

**Comment by j-n-f** [comment]
the functionality of `one_of` seems more like `any_of`, whereas it's kind of surprising to see `one_of` returning > 1 bytes.

Maybe a built-in like `single(predicate)` would be helpful.

I'm trying to match ranges whose endpoints are single characters, e.g. `a-z`, `0-9`. I think I can use `delimited!()` with the dash in the middle argument, but I don't have any way to match the single characters. 

It seems @lo48576 has a viable workaround, I can do something like:

```
named!(
    single_lower,
    take_while_m_n!(1, 1, |c| (c as char).is_lowercase())
);
named!(
    alpha_range,
    delimited!(single_lower, tag!(b"-"), single_lower)
);
```

with something like `single!()` it could be less verbose:

```
named!(single_lower, single!(|c| (c as char).is_lowercase())));
```

**Comment by Geal** [comment]
hello, the `satisfy` combinator introduced in 5108ed1 should do the trick :)

**Comment by Geal** [comment]
nom 6 is released now :partying_face:

**Comment by robinkrahl** [comment]
> hello, the `satisfy` combinator introduced in [5108ed1](https://github.com/Geal/nom/commit/5108ed18d54520d2106a67432f235c10a32df24c) should do the trick :)

Would it be possible to have a similar solution for `nom::bytes`?

**Comment by LoganDark** [comment]
> hello, the `satisfy` combinator introduced in [5108ed1](https://github.com/Geal/nom/commit/5108ed18d54520d2106a67432f235c10a32df24c) should do the trick :)

`satisfy` doesn't work on `[u8]` :(
