### ISSUE TITLE
Broken link for guides in https://docs.rs/nom/3.2.1/nom/

### ISSUE THREAD

**Issue by irvifa** [Geal/nom#1064]
I notice that there's a broken links on https://docs.rs/nom/3.2.1/nom/ for example:
1. [the design of nom](http://rust.unhandledexpression.com/nom/how_nom_macros_work.html)
2. [working in parser](http://rust.unhandledexpression.com/nom/making_a_new_parser_from_scratch.html)

etc.
I'd gladly to help with improving the docs, as long as I know where is the repository for this website. Thanks in advance 🙂

**Comment by Geal** [comment]
theses docs refer to an old version of nom and are not maintained
