### ISSUE TITLE
double parser returns unexpected result for the input ". " when the lexical feature is enabled

### ISSUE THREAD

**Issue by evant** [Geal/nom#1080]
## Prerequisites

- Rust version : rustc 1.39.0 (4560ea788 2019-11-04)
- nom version : 5.0.1/master
- nom compilation features used: lexical

## Test case

The `number::complete::double` parser returns an unexpected result when passed the input `". "`. I would expect it to fail, but it returns `Ok((" ", 0.0))`. If the lexical feature is disabled, then the expected error of: `Err(Error((" ", Digit))` is returned.

Sample repo: https://github.com/evant/nom-double-parse-issue

```rust
use nom::number::complete::double;
use nom::IResult;

fn main() {
    println!("nom double parse: {:?}", nom_double(". "));
}

fn nom_double(input: &str) -> IResult<&str, f64> {
    double(input)
}
```

**Comment by Alexhuszagh** [comment]
The specific issue is here, where the complete `nom` parser uses lexical (which I maintain) to provide a streaming-like feature detection, which I believe is an issue here. Older versions of lexical detected the first invalid digit, which would raise an InvalidDigit if only a `'.'` character was found (or a '.' character follow by any non-valid digit), which was fairly amibiguous.

My new fork should correct this issue with a more modern version of lexical:
https://github.com/Alexhuszagh/nom-double-parse-issue

Newer versions, which I will shortly submit a PR for, will correctly fail with this input.

``` bash
nom double parse: Ok((" ", 0.0))
lexical_043 double parse: Result { value: 0.0, error: Error { code: InvalidDigit, index: 1 } }
lexical_070 double parse: Err(Error { code: EmptyFraction, index: 0 })
```

**Comment by Geal** [comment]
#1101 is merged, new version coming up
