### ISSUE TITLE
Differrent behaviour between many1! and many1 function

### ISSUE THREAD

**Issue by blasrodri** [Geal/nom#1084]
Hello, and thank you for submitting an issue to nom!

First, please note that, for family reasons, I have limited time to work on
nom, so following the advice here will make sure I will quickly understand
your problem and answer as soon as possible.
Second, if I don't get to work on your issue quickly, that does not mean I
don't consider it important or useful. Major version releases happen once
a year, and a lot of fixes are done for the occasion, once I have had time
to think of the right solution. So I will get back to you :)

## Prerequisites

Here are a few things you should provide to help me understand the issue:

- Rust version : `rustc 1.39.0 (4560ea788 2019-11-04)`
- nom version : `5.0.1`
- nom compilation features used: None

## Test case

```rust
#[macro_use]
extern crate nom;

use nom::{
  IResult,
  bytes::complete::tag};

use nom::multi::many1;
named!(parser_macro<&str, Vec<&str> >, many1!( tag!( "abc" ) ) );
fn parser(s: &str) -> IResult<&str, Vec<&str>> {
  many1(tag("abc"))(s)
}

fn main() {
    assert_eq!(parser("abcabc"), Ok(("", vec!["abc", "abc"])));
    assert_eq!(parser_macro("abcabc"), Ok(("", vec!["abc", "abc"])));
}
/*
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Err(Incomplete(Size(3)))`,
 right: `Ok(("", ["abc", "abc"]))`', src/main.rs:16:5

*/
```

**Comment by jamwaffles** [comment]
The `tag!()` macro uses `bytes::streaming::tag` internally which I think is the cause of your problem. You can reproduce this issue with the `fn` version by changing the import in your example from `bytes::complete::tag` to `bytes::streaming::tag`.

To fix the macro usage, try adding `complete!()`:

```rust
named!(parser_macro<&str, Vec<&str> >, many1!( complete!( tag!( "abc" ) ) ) );
```

**Comment by blasrodri** [comment]
@jamwaffles thanks for the quick reply. I checked and everything what you mention is right. 
Is there anywhere in the docs where this is reflected? I guess it's the expected behavior and the issue should be closed, though.

**Comment by jamwaffles** [comment]
No problem! I don't remember seeing anything in the docs about the behaviour, but I agree that this could use some clarification.

**Comment by blasrodri** [comment]
I'll close this one. If I can find a meaningful way to convey this advice, I'll send a PR. Thanks a lot anyways :)
