### ISSUE TITLE
Generalize `InputTake`

### ISSUE THREAD

**Issue by loewenheim** [Geal/nom#1095]
I think there’s no obvious reason why `tag` should only work on bytes, as opposed to any kind of slice or vector. However, it currently requires the `InputTake` trait on the type of the input, which allows the input to be sliced. `InputTake`’s `input_take` method specifies that it returns a slice with a specified length in bytes and is only implemented for strings and slices of bytes. I think it could be generalized to arbitrary slices, in which case the length of the returned slice would not necessarily be measured in bytes. `Compare` should work in a similar way, which would allow generalization of `tag`.

**Comment by Geal** [comment]
how would it be measured then? As long as `InputTake` and other traits are implemented, you could have different slicing methods. IIRC someone played with parsing `&[u16]` buffers at some point
