### ISSUE TITLE
Whitespace handling

### ISSUE THREAD

**Issue by jrmuizel** [Geal/nom#1113]
The GLSL parser here https://github.com/phaazon/glsl/blob/master/glsl/src/parsers.rs has a bunch of whitespace handling code spread throughout the grammar. It's easiest to find by searching for `blank` but here's an example:
```rust
      delimited(
        terminated(char('{'), blank),
        terminated(
          cut(initializer_list),
          terminated(blank, opt(terminated(char(','), blank))),
        ),
        cut(char('}')),
      ),
```

If a lexer was being used this would be handled during lexing and so it wouldn't show up in the grammar. Is there a better way of abstracting away whitespace handling so that it doesn't show up all over the grammar?

**Comment by Geal** [comment]
as of now there's no nicer way. previous versions of nom had macros to help in whitespace handling, by interleaving space parsers here and there, but it was a huge hack :disappointed:
