### ISSUE TITLE
take_until1 parser missing in v5

### ISSUE THREAD

**Issue by WesleyAC** [Geal/nom#1147]
there was previously a `take_until1` parser, acting like `take_until`, but always matching at least one byte.

this seems pretty useful, but it isn't in nom version 5.1.1 - #893 looks like it tracked adding it, but it somehow got missed - is there a reason that this parser got dropped?

**Comment by WesleyAC** [comment]
this seems quite trivial to add:

```rust
pub fn take_until1<T, Input, Error: ParseError<Input>>(tag: T) -> impl Fn(Input) -> IResult<Input, Input, Error>
where
  Input: InputTake + FindSubstring<T>,
  T: InputLength + Clone,
{
  move |i: Input| {
    let t = tag.clone();
    let res: IResult<_, _, Error> = match i.find_substring(t) {
      None | Some(0) => Err(Err::Error(Error::from_error_kind(i, ErrorKind::TakeUntil))),
      Some(index) => Ok(i.take_split(index)),
    };
    res
  }
}
```

should do it (that's the same as the `take_until` implementation, with the addition of `| Some(0) `

are you open to a PR adding this?

**Comment by SirWindfield** [comment]
> are you open to a PR adding this?

Just open a PR :) I mean more than closing it can't happen :smile:

**Comment by Geal** [comment]
yup, a PR would be good!

**Comment by hammypants** [comment]
Still missing in v6 despite being referenced in numerous places in the docs.

**Comment by Geal** [comment]
added in 386c711

**Comment by Geal** [comment]
released in nom 7: https://crates.io/crates/nom/7.0.0
