### ISSUE TITLE
Make convert_error generic

### ISSUE THREAD

**Issue by DustinByfuglien** [Geal/nom#1149]
Good day!

Nom's error handling is convenient with ```VerboseError<I>``` type that is generic over input type.
But one useful function ```convert_error``` get argument with non-generic ```VerboseError<&str>``` type.
It would be excellent if this function have generic ```VerboseError<I>``` argument too to use it with custom input types.

**Comment by DustinByfuglien** [comment]
May be it header would be looks like
```
pub fn convert_error<'a, T>(input: &str, e: VerboseError<T>) -> String
    where
        T: Copy + Offset + InputIter<Item=char> + Deref<Target=&'a str>
{
...
```

**Comment by Geal** [comment]
the type of the input argument and the `T` type in `VerboseError` should match. b2ed755 should be enough to fix it, feel free to reopen if there are some edge cases
