### ISSUE TITLE
Should there be a `map_res` that preserves errors?

### ISSUE THREAD

**Issue by ericseppanen** [Geal/nom#1171]
I discovered that this hides a subtle bug:
```rust
fn parse_u64(input: &str) -> IResult<&str, u64, MyCustomError> {
    map_res(digit1, |s: &str| -> Result<u64, MyCustomError> {
        s.parse::<u64>().map_err(|_| {
            MyCustomError::BadInt
        })
    })
    (input)
}
```

I think this is a reasonable way to attempt this?  But it doesn't actually work as expected.
```rust
fn test_parser() {
    assert_eq!(parse_u64("99999999999999999999"), Err(nom::Err::Error(MyCustomError::BadInt)));
}
```
```text
test test_parser ... FAILED

failures:

---- test_parser stdout ----
thread 'test_parser' panicked at 'assertion failed: `(left == right)`
  left: `Err(Error(NomError(MapRes)))`,
 right: `Err(Error(BadInt))`', src/lib.rs:248:5
```

The problem is that `map_res` always discards the error value returned by the closure.  Maybe that's fine in many cases, but it's not particularly helpful if a custom error type is in use.

The only workaround I've found is to reimplement the internals of `map_res` in each parser function:
```rust
fn parse_u64(input: &str) -> IResult<&str, u64, MyCustomError> {
    let (remain, s) = digit1(input)?;
    match s.parse::<u64>() {
        Ok(val) => Ok((remain, val)),
        Err(_) => Err(nom::Err::Error(MyCustomError::BadInt)),
    }
}
```

This is tolerable.  But I wonder if it would be useful to have a variation on `map_res` that returns the closure's error.  Something like this:
```rust
// in nom 5.1 style; needs updates for nom 6.0
fn map_res_err<I: Clone, O1, O2, E: ParseError<I>, F, G>(
    first: F,
    second: G,
) -> impl Fn(I) -> IResult<I, O2, E>
where
    F: Fn(I) -> IResult<I, O1, E>,
    G: Fn(O1) -> Result<O2, E>,
{
    move |input: I| {
        let (input, o1) = first(input)?;
        match second(o1) {
            Ok(o2) => Ok((input, o2)),
            Err(e) => Err(nom::Err::Error(e)),
        }
    }
}
```
This is virtually identical to `map_res`, except here `e` is preserved. And it has one less generic parameter (because there's no inner error type to be discarded.

Am I approaching this problem in the wrong way?

If there is interest in adding such a function, I can put together a PR with docs/tests/etc.

**Comment by ericseppanen** [comment]
A bigger problem with my suggested code above: it always returns `nom::Err::Error`.  For something like my example of an integer overflow during parsing, a more appropriate choice would be `nom::Err::Failure`.

I'm not sure whether that means my suggested `map_res_err` should be paired with a `map_res_fail`, or whether there should be only one implementation that requires the closure return a `Result<_, nom::Err<E>>` for maximum flexibility.

**Comment by Geal** [comment]
there's now a `FromExternalError` trait to implement in your error type, that will preserve the error from `map_res`, and you can wrap the call to  `map_res` with the `cut` combinator that will transform `Err::Error` into `Err::Failure`
