### ISSUE TITLE
MySQL binlog parsers written with nom

### ISSUE THREAD

**Issue by PrivateRookie** [Geal/nom#1179]
Although nom has many sample projects, there is no parser about mysql binlog, so I implemented a binlog parser with nom. I think this project is interesting, I hope it can be added to nom's README and being used by more developer, showing  the wonderful and powerful capabilities of nom.

project link: [boxercrab](https://github.com/PrivateRookie/boxercrab)

**Comment by Geal** [comment]
added in ab9c7ff, thanks!
