### ISSUE TITLE
nom::Err::to_owned should enabled with alloc

### ISSUE THREAD

**Issue by XAMPPRocky** [Geal/nom#1191]
Hello, I was using nom for a `no_std` project, and one of the difficulties I had using it was that the `to_owned` functions ([Example](https://docs.rs/nom/5.1.2/nom/enum.Err.html#method.to_owned)) for `nom::Err` are only available with `std`, when they should only require `alloc` for converting into owned types. It would be nice if those methods were available for`alloc` crates.

**Comment by Geal** [comment]
it should work with 4a30ddc
