### ISSUE TITLE
Make `context()` accept arbitrary types

### ISSUE THREAD

**Issue by Minoru** [Geal/nom#1197]
As of Nom 5.1.2, [`context()` requires the context name to be a `&'static str`](https://docs.rs/nom/5.1.2/nom/error/fn.context.html). I use contexts to store an explanation of what my combinators expect; when a combinator fails, I use the context as an error message.

I want to internationalize those messages with [`gettextrs::gettext()`](https://koka.github.io/gettext-rs/gettextrs/fn.gettext.html), but that's a runtime function that returns a `String`—I can't use its result as a parameter to `context()`. I also can't put the context name into a static and pass that into `gettext()`, because the tool that extracts translatable messages from the code expects to see a string literal as an argument to `gettext()`.

To get around this, I resort to an ugly solution where I put context names into statics and then use a BTreeMap to turn them into translated messages. This is ugly for a number of reasons: no compile-time protection from statics containing duplicate strings, no compile-time guarantee that all the statics have an associated entry in the map, etc. You can look at this solution here: https://github.com/newsboat/newsboat/pull/1191

If `context()` accepted arbitrary types, I could do this instead:

```rust
enum ErrorMsg {
    Case1,
    Case2,
    Case3
}

fn translate_error(err: ErrorMsg) -> String {
    match err {
        ErrorMsg::Case1 => gettext("error message 1"),
        ErrorMsg::Case2 => gettext("error message 2"),
        ErrorMsg::Case3 => gettext("error message 3"),
    }
}

fn parser<a, E: ParseError<&'a str>>(input: &'a str) -> IResult<&'a str, ResultType, E> {
    context(
        ErrorMsg::Case1,
        // more code here, irrelevant
    )
}
```

This provides all the compile-time guarantees that I want, and allows the tooling to extract messages from `gettext()` calls.

(I see there is work underway to redo error handling in Nom—#1136—but I don't think it addresses this particular problem.)

**Comment by Geal** [comment]
it might be better  to have a custom error type for your parser, and make your own `context()` combinator. You would even be able to integrate data from the input in your error i18n routine

**Comment by Minoru** [comment]
Ah, I didn't think of that, sorry. It'd be a bit weird to write my own combinator and duplicate not just the existing `context` but also `ParseError::add_context`, but it's not too bad.

Thank you for the idea! Please close this issue if you can't or don't intend to relax the requirement on the existing `context` combinator.
