### ISSUE TITLE
Why is there no nom::character::is_newline?

### ISSUE THREAD

**Issue by jmg-duarte** [Geal/nom#1205]
As the title states I don't understand why there is no `nom::character::is_newline`.

To provide more context, I'm currently developing a Markdown parser as a learning experiment.
To parse code blocks I currently do the following:

```rust
pub fn parse_code_block(input: &str) -> IResult<&str, Element> {
    sequence::delimited(complete::tag("```"), parse_code, complete::tag("```"))(input)
}

fn parse_code(input: &str) -> IResult<&str, Element> {
    let (input, (language, code)) = sequence::pair(
        nom::combinator::opt(
            complete::take_till1(|c| c == '\n') // <-- Notice here
        ),
        complete::take_until("`"),
    )(input)?;
    Ok((input, Element::Code(Code::new(code, language))))
}
```

In the marked line of the code, I am required to do `|c| c == '\n'` instead of being able to use a simple provided function.

Is there some underlying reason I am missing, or should I implement the function and submit a PR?

**Comment by Geal** [comment]
there's no underlying reason, it could be added

**Comment by jmg-duarte** [comment]
I'll submit a PR asap then!
