### ISSUE TITLE
`nom::multi::length_count` function requires input to implement unused `InputTake` and `InputLength` traits

### ISSUE THREAD

**Issue by polazarus** [Geal/nom#1229]
Using `nom` with some nonstandard inputs, I found out that I could not use the `nom::multi::length_count` function because my input did not implement `InputTake` nor `InputLength`. As it was surprising to me, I look at the actual code and did not see a real reason for the requirement. A copy/paste of the function with the said traits removed *works as intended*.

Improvement request: remove those two trait requirements.

- Rust version : 1.47.0
- nom version : 6.0.0
- nom compilation features used: []

Thanks for the great work on `nom`!

**Comment by Geal** [comment]
you're right, they're not necessary. This is fixed in 36fabd7
