### ISSUE TITLE
Add a macro to apply a parser 1..n or 0..n times

### ISSUE THREAD

**Issue by euantorano** [Geal/nom#124]
In many cases you need to apply a parser multiple times - either `0..n` or `1..n` times. It would be handy to have a standard macro for this, rather than having to chain `opt!()` calls repeatedly.

**Comment by nelsonjchen** [comment]
`many0!()`, `many1!()`?

**Comment by euantorano** [comment]
@nelsonjchen that will apply `0..infinite` or `1..infinite` if I'm reading the docs correctly. In many situations you need a fixed maximum number of times.

**Comment by nelsonjchen** [comment]
Oh! I see.

**Comment by Geal** [comment]
I implemented the `many_m_n!` combinator in cb62afb. You will be able to choose exactly how many parser applications you need.

This will be part of the 1.1 release

**Comment by euantorano** [comment]
Nice, thanks!
