### ISSUE TITLE
not compiling in no_std

### ISSUE THREAD

**Issue by macthestack** [Geal/nom#1247]
nom version / features:

`nom = { version = "6", default-features = false }`

Getting compile error:

```
╰─ cargo build
   Compiling nom v6.0.0
   Compiling memchr v2.3.4
error[E0463]: can't find crate for `std`
  |
  = note: the `thumbv8m.main-none-eabihf` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `memchr`
```

**Comment by Geal** [comment]
I think you should report this to the memchr project: https://github.com/BurntSushi/rust-memchr

**Comment by xfix** [comment]
I cannot reproduce this issue myself. `nom` without default features builds for me on `thumbv6m-none-eabi` and `thumbv8m.main-none-eabihf`.

**Comment by macthestack** [comment]
Thanks for looking at it. I think it sounds like something on my end in which case I apologise for taking your time.
