### ISSUE TITLE
Err::to_owned uses old tuple instead of new error::Error type

### ISSUE THREAD

**Issue by MalteT** [Geal/nom#1254]
- Rust version : `rustc 1.48.0-nightly (623fb90b5 2020-09-26)`
- nom version : `6.0.1`
- nom compilation features used: `[]`

The `Err::to_owned` uses the old IResult definition. Both the implementations for `&str` and `&[u8]` should probably be rewritten for the updated IResult.

Current version:
https://github.com/Geal/nom/blob/bd1adeb8cee593dfedb971df4f5aa26b8a011578/src/internal.rs#L153-L171

**Comment by ArenM** [comment]
I'm running into issues with this.

I could put together a pr, assuming it's just implementing a generic `Clone` & `ToOwned` on `nom::error::Error` if that would be useful.

**Comment by scrabsha** [comment]
@ArenM are you working on it? I am having issues as well, and I'd like to open a PR to fix it :)

**Comment by ArenM** [comment]
I didn't end up making a fix for this. As far as I can remember `ToOwned` has a generic implemation that calls clone, and it is actually correct for clone to only clone the outermost object, so implementing this in a way that looks and feels nice is a bit of a challenge. As a jumping off point this code should work pretty well:
```rust
some_parser("sdf").map_err(|e| {
    e.map(|e2| nom::error::Error {
                input: e2.input.to_owned(),
                code: e2.code,
            })
        });
