### ISSUE TITLE
Missing `html_root_url` in crate root

### ISSUE THREAD

**Issue by Kage-Yami** [Geal/nom#1266]
The crate root is missing `html_root_url`, which is [recommended for all published libraries](https://rust-lang.github.io/api-guidelines/documentation.html#crate-sets-html_root_url-attribute-c-html-root). The result is that `nom` types used in dependent crates do not link back to the `nom` documentation when a crate's documentation is built _without_ dependencies.

## Prerequisites

- Rust version : `rustc 1.48.0 (7eac88abb 2020-11-16)`
- nom version : `6.0.1`
- nom compilation features used: `default`

## Test case

Note that in the generated documentation, the return type for `return_type_link_present_in_docs()` links off to `anyhow`'s documentation on https://docs.rs, whereas the same does not occur for `return_type_missing_link_in_docs()`, when it should be pointing to `nom`'s documentation.

###### `Cargo.toml`
```toml
[dependencies]
anyhow = "1.0.36"
nom = "6.0.1"
```

###### `src/lib.rs`
```rust
pub fn return_type_missing_link_in_docs() -> nom::IResult<&'static str, &'static str> {
    nom::combinator::success("test")("")
}

pub fn return_type_link_present_in_docs() -> anyhow::Result<()> {
    Ok(())
}
```

###### `Terminal`
```sh
cargo doc --no-deps
```

## Other

As an example, [`anyhow` specifies it here](https://github.com/dtolnay/anyhow/blob/f9419cd5a13496112deb0fac5386fc3c9fd5d60f/src/lib.rs#L212).

## Edit history

27-Dec-2020 [1]: Added link to Rust API guidelines.

**Comment by jhpratt** [comment]
Just fyi, this recommendation [is on the verge of being removed](https://github.com/rust-lang/api-guidelines/issues/229). Two more checkboxes and it goes to FCP.

**Comment by Kage-Yami** [comment]
I'm going to close this off; the RFC referenced by @jhpratt has passed and is just waiting on the merge now, so this issue doesn't have sufficient justification now.
