### ISSUE TITLE
error: failed to run custom build command for `jemalloc-sys v0.3.2`

### ISSUE THREAD

**Issue by zhuxiujia** [Geal/nom#1270]
Platform, windows  msvc toolchain.
Because I need RocksDB，So it has to be an MSVC toolchain environment

**Comment by Geal** [comment]
jemallocator is only there as a dev dependency, it should not affect your build. Could you check with the jemallocator project?

**Comment by tan-wei** [comment]
Try `x86_64-pc-windows-gnu` toolchain please, `jemallocator` doesn't support msvc.

**Comment by zhuxiujia** [comment]
> Try `x86_64-pc-windows-gnu` toolchain please, `jemallocator` doesn't support msvc.

Because I'm using RocksDB， it use  msvc  toolchain

**Comment by tan-wei** [comment]
IMO, the build of c`nom` doesn't need `jemallocator` as dependency (just like @Geal saied before).

**Comment by Stargateur** [comment]
I fail to see why we need it for test. the only thing I see in the code is we use jemallocator but that all we don't use any feature from it.

**Comment by Geal** [comment]
jemalloc is only used as a dev dependency for benchmarks: https://github.com/Geal/nom/blob/master/benches/ini.rs#L2
it should not affect regular use of nom. If there's more info to provide we can reopen this
