### ISSUE TITLE
`many0` odd behaviour when combined with `do_parse`

### ISSUE THREAD

**Issue by achary** [Geal/nom#1279]
- Rust version :  1.49.0
- nom version : 6.1.0
- nom compilation features used: ["alloc"]

## Test case

when using `many0!` macro combined, the expected behaviour of this combinator is not there. I would expect that for a single valid sequence that is parsable, it will return a vector with one result. However, what is returned is something that looks like a result of "another round" of `do_parse!` execution.

To explain the difference between expected and observed behaviour I'm proving two similar parsers as reproducers.
First parser `parse_digits` extract a single value form a sequence of 3 bytes and it works correctly, (the unit tests passes).
The second parser `parse_digits_many` is identical, but wrapped with `many0!` combinato and has the return value signature changed (as per doc) to `Vec`.

Test cases:

```rust
use nom::{do_parse, many0, named, tag, take};

named!(parse_digits<&[u8], u8>,
    do_parse!(
        tag!(&[0x40, 0x55])    >>  // skipping two-byte header
        value: take!(1)        >>  //
        (value[0])
    )
);

#[test]
fn check_parse_digits() {
    let data = &[0x40, 0x55, 1];
    let result = parse_digits(data);
    let empty_remainder: &[u8] = &[];
    assert_eq!(Ok((empty_remainder, 1)), result);
}

named!(parse_digits_many<&[u8], Vec<u8>>,
    many0!(
        do_parse!(
            tag!(&[0x40, 0x55])     >>  // skipping two-byte header
            value: take!(1)         >>  //
            (value[0])
        )
    )
);

#[test]
fn check_parse_digits_many_with_one_sequence() {
    let data = &[0x40, 0x55, 1];
    let result = parse_digits_many(data);
    let empty_remainder: &[u8] = &[];
    assert_eq!(Ok((empty_remainder, vec![1])), result);
}
#[test]
fn check_parse_digits_many_with_two_sequences() {
    let data = &[0x40, 0x55, 1, 0x40, 0x55, 2];
    let result = parse_digits_many(data);
    let empty_remainder: &[u8] = &[];
    assert_eq!(Ok((empty_remainder, vec![1, 2])), result);
}
```

I would expect the second parseer `parse_digits_many` to work identically as the first one, on same input sequence, returning just `Vec<u8>` with one value, as there is one iteration this can perform. This is not happening, the attached unit test fails with:

```
---- tests::check_parse_digits_many_with_one_sequence stdout ----
thread 'tests::check_parse_digits_many_with_one_sequence' panicked at 'assertion failed: `(left == right)`
  left: `Ok(([], [1]))`,
 right: `Err(Incomplete(Size(2)))`', nom-parser/src/tests.rs:34:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
The last unit test in the tests fails too in a similar fashion.

**Comment by Stargateur** [comment]
do_parse is only macro and is not really need in V5 and V6 and macro will be removed in V7, have you any trouble transforming this in function ?

I believe this issue should be close.

**Comment by Geal** [comment]
yes, macros are not supported anymore
