### ISSUE TITLE
Question: Is changing the error signature considered a breaking change?

### ISSUE THREAD

**Issue by mainrs** [Geal/nom#1281]
Hey! I am a little bit unsure if the following is a breaking change following the migration from v5 to v6:

```rust
// v6
fn func<
    'a,
    E: ContextError<&'a str> + FromExternalError<&'a str, String> + ParseError<&'a str>,
>(
    i: &'a str,
) -> IResult<&'a str, Commit<'a>, E> {}

// v5
fn commit_complete<'a, E: ParseError<&'a str>>(i: &'a str) -> IResult<&'a str, Commit<'a>, E> {}
```

It seems that the earlier version of `ParseError` had actually all the same function names. I couldn't think of a better place to ask, so sorry for polluting the issue tracker!

Thanks for helping me out!

**Comment by Lucretiel** [comment]
Yes, this was changed. Many of the methods inherent to `ParseError` were split out into separate traits, allowing more flexibility in error implementations.

Whether or not this actually breaks your dependent code in practice varies, of course; if you're only using the methods names themselves you might be okay. But `ParseError` did have several methods removed, meaning that this is certainly a technically breaking change.
