### ISSUE TITLE
Bitvec 0.22.1 is out. We should rollback fix for funty 1.2

### ISSUE THREAD

**Issue by getreu** [Geal/nom#1302]
[bitvec](https://crates.io/crates/bitvec)  = "0.22.1" is out.

This should make #1284 obsolete.

**Comment by nuttycom** [comment]
Please fix this! I have an unresolvable dependency tree because of this issue.

**Comment by collinc97** [comment]
Any updates on this?

**Comment by Geal** [comment]
this is fixed in the next release, hopefully out in a few days

**Comment by Geal** [comment]
bitvec input types are now in the nom-bitvec crate, since the release of nom 7: https://crates.io/crates/nom/7.0.0
