### ISSUE TITLE
Update lexical-core for 5.1

### ISSUE THREAD

**Issue by Stargateur** [Geal/nom#1306]
Can we do a little patch to update lexical-core to `0.7.6` ?

Some breaking change after nightly stabilization https://github.com/Alexhuszagh/rust-lexical/issues/55

**Comment by Stargateur** [comment]
nevermind a cargo update did it.

**Comment by baoyachi** [comment]
cargo update -p lexical-core 
`lexical-core `: 0.7.4 -> 0.7.6
