### ISSUE TITLE
Many `xxxxxc` combinators (ones that takes input and returns result directly) have not been update to using the `Parser` trait

### ISSUE THREAD

**Issue by changhe3** [Geal/nom#1307]
Like this one:
https://github.com/Geal/nom/blob/38bb94e7bc45c2b4ef0c473e0e5c03ab134cdff3/src/combinator/mod.rs#L85-L92

Is this intentional or is it due to no one having submitted any PR yet?

**Comment by Geal** [comment]
those combinators are there only for use inside macros. Are there cases where you want to use them?

**Comment by Geal** [comment]
They will be removed in nom 7
