### ISSUE TITLE
Consider Migrating to Minimal-Lexical

### ISSUE THREAD

**Issue by Alexhuszagh** [Geal/nom#1309]
## Background

[lexical-core](https://github.com/Alexhuszagh/rust-lexical/tree/master/lexical-core) has become more of a general-purpose number formatter and parser, used in some applications for parsing a wide variety of float formats (everything from duodecimal, to C++'s hexadecimal floats, to JSON, etc.). However, this increased support for a wide variety of formats also leads to increased compile times, and Nom only uses the default features. Although these compile times will be improved in v0.80, it will still not compare to minimal-lexical.

[minimal-lexical](https://github.com/Alexhuszagh/minimal-lexical) is a barebones, performant, and correct float parser (but not tokenizer) that focused on minimal compile times while maintaining a reasonable level flexibility. It was developed for integration into serde-json, has a stable API, and has similar performance and the same correctness as lexical-core. Compile times for minimal-lexical are ~0.8s compared to ~2.5s for lexical-core, and the resulting binaries are similar.

**Pros:**
- Faster compile times.
- Stable API with a single exported trait and function.
- Dependency-free when disabling `no_alloc` feature.
- Stable on `no_std` (coming to lexical-core in v0.8).
- Uses the Eisel-Lemire algorithm, providing faster float parsing (coming to lexical-core in v0.8).
- Easier support for custom float formats (may be useful to support parsing JSON-conforming floats, which could be a valid use-case).
- Larger version support (minimal-lexical supports 1.31.0+, while lexical-core requires 1.37.0+).

**Cons:**
- Must tokenize the float in Nom.
- Does not handle special values (NaN, Infinity).

The API (which should be stable, and is only pre-1.0 in case of exceptional circumstances) consists only of:

```rust
pub fn parse_float<'a, F, Iter1, Iter2>(integer: Iter1, fraction: Iter2, exponent: i32) -> F
where
    F: Float,
    Iter1: Iterator<Item = &'a u8> + Clone,
    Iter2: Iterator<Item = &'a u8> + Clone,
{
    ...
}
```

## Code Sample

A code sample using minimal-lexical is as follows:

Cargo.toml

```toml
[dependencies]
minimal-lexical = "0.1"
```

```rust
/// Find and parse sign and get remaining bytes.
#[inline]
fn parse_sign<'a>(bytes: &'a [u8]) -> (bool, &'a [u8]) {
    match bytes.get(0) {
        Some(&b'+') => (true, &bytes[1..]),
        Some(&b'-') => (false, &bytes[1..]),
        _ => (true, bytes),
    }
}

// Convert u8 to digit.
#[inline]
fn to_digit(c: u8) -> Option<u32> {
    (c as char).to_digit(10)
}

// Add digit from exponent.
#[inline]
fn add_digit_i32(value: i32, digit: u32) -> Option<i32> {
    return value.checked_mul(10)?.checked_add(digit as i32);
}

// Subtract digit from exponent.
#[inline]
fn sub_digit_i32(value: i32, digit: u32) -> Option<i32> {
    return value.checked_mul(10)?.checked_sub(digit as i32);
}

// Convert character to digit.
#[inline]
fn is_digit(c: u8) -> bool {
    to_digit(c).is_some()
}

// Split buffer at index.
#[inline]
fn split_at_index<'a>(digits: &'a [u8], index: usize) -> (&'a [u8], &'a [u8]) {
    (&digits[..index], &digits[index..])
}

/// Consume until a an invalid digit is found.
///
/// - `digits`      - Slice containing 0 or more digits.
#[inline]
fn consume_digits<'a>(digits: &'a [u8]) -> (&'a [u8], &'a [u8]) {
    // Consume all digits.
    let mut index = 0;
    while index < digits.len() && is_digit(digits[index]) {
        index += 1;
    }
    split_at_index(digits, index)
}

// Trim leading 0s.
#[inline]
fn ltrim_zero<'a>(bytes: &'a [u8]) -> &'a [u8] {
    let count = bytes.iter().take_while(|&&si| si == b'0').count();
    &bytes[count..]
}

// Trim trailing 0s.
#[inline]
fn rtrim_zero<'a>(bytes: &'a [u8]) -> &'a [u8] {
    let count = bytes.iter().rev().take_while(|&&si| si == b'0').count();
    let index = bytes.len() - count;
    &bytes[..index]
}

/// Parse the exponent of the float.
///
/// * `exponent`    - Slice containing the exponent digits.
/// * `is_positive` - If the exponent sign is positive.
fn parse_exponent(exponent: &[u8], is_positive: bool) -> i32 {
    // Parse the sign bit or current data.
    let mut value: i32 = 0;
    match is_positive {
        true => {
            for c in exponent {
                value = match add_digit_i32(value, to_digit(*c).unwrap()) {
                    Some(v) => v,
                    None => return i32::max_value(),
                };
            }
        },
        false => {
            for c in exponent {
                value = match sub_digit_i32(value, to_digit(*c).unwrap()) {
                    Some(v) => v,
                    None => return i32::min_value(),
                };
            }
        },
    }

    value
}

/// Parse float from input bytes, returning the float and the remaining bytes.
///
/// * `bytes`    - Array of bytes leading with float-data.
fn parse_float<'a, F>(bytes: &'a [u8]) -> (F, &'a [u8])
where
    F: minimal_lexical::Float,
{
    // Parse the sign.
    let (is_positive, bytes) = parse_sign(bytes);

    // Note: this does not handle special float values.
    // You will have to handle NaN, Inf, and Infinity
    // on your own.

    // Extract and parse the float components:
    //  1. Integer
    //  2. Fraction
    //  3. Exponent
    let (integer_slc, bytes) = consume_digits(bytes);
    let (fraction_slc, bytes) = match bytes.first() {
        Some(&b'.') => consume_digits(&bytes[1..]),
        _ => (&bytes[..0], bytes),
    };
    let (exponent, bytes) = match bytes.first() {
        Some(&b'e') | Some(&b'E') => {
            // Extract and parse the exponent.
            let (is_positive, bytes) = parse_sign(&bytes[1..]);
            let (exponent, bytes) = consume_digits(bytes);
            (parse_exponent(exponent, is_positive), bytes)
        },
        _ => (0, bytes),
    };

    // Note: You may want to check and validate the float data here:
    //  1). Many floats require integer or fraction digits, if a fraction
    //      is present.
    //  2). All floats require either integer or fraction digits.
    //  3). Some floats do not allow a '+' sign before the significant digits.
    //  4). Many floats require exponent digits after the exponent symbol.
    //  5). Some floats do not allow a '+' sign before the exponent.

    // We now need to trim leading and trailing 0s from the integer
    // and fraction, respectively. This is required to make the
    // fast and moderate paths more efficient, and for the slow
    // path.
    let integer_slc = ltrim_zero(integer_slc);
    let fraction_slc = rtrim_zero(fraction_slc);

    // Create the float and return our data.
    let mut float: F =
        minimal_lexical::parse_float(integer_slc.iter(), fraction_slc.iter(), exponent);
    if !is_positive {
        float = -float;
    }

    (float, bytes)
}
```

## Build Times

Using `cargo build -Z timings` on `rustc 1.53.0-nightly` for `x86_64-unknown-linux-gnu`, we get the following build time differences:

![Screenshot_20210510_095138](https://user-images.githubusercontent.com/9440903/117678950-7bb9db80-b175-11eb-96c8-9476abd022de.png)
![Screenshot_20210510_095155](https://user-images.githubusercontent.com/9440903/117678952-7bb9db80-b175-11eb-8ce3-5a5c050e869c.png)

## Relevant Issues

Fixes #1298 and #1299.

## Sample Feature Enhancements

Parsing JSON strings is different than Rust strings, although both can be trivially supported with minimal-lexical. For example, the following are annotated numbers in JSON:

```rust
0.1     // valid
0.      // invalid, must have digits after the decimal point
.1      // invalid, must have digits before the decimal point
01      // invalid, leading zeros
01.0    // invalid, leading zeros
NaN     // invalid, no special values
+1.0    // invalid, no + sign allowed
-1.0    // valid
1.0e15  // valid
1.0e+15 // valid
```

Meanwhile, Rust strings support the following:

```rust
0.1     // valid
0.      // valid
.1      // valid
01      // valid
01.0    // valid
NaN     // valid
nan     // invalid, case-sensitive special
+1.0    // valid
-1.0    // valid
1.0e15  // valid
1.0e+15 // valid
```

Since minimal-lexical only requires a trimmed, input iterator consisting of the significant digits, it's trivial to add support for both formats.

## Maintenance

In the case I need to take a break from open source maintenance for mental health reasons, @myrrlyn has also offered to co-maintain minimal-lexical.

**Comment by Geal** [comment]
alright, I've run some tests, the performance is great! Going from around 25ns to 2.5ns to parse a float, even when offloading the tokenization to nom, that's awesome.

It needs a bit of work on my part to make the interface nice enough, but I think that'll ship in 7.0

**Comment by Geal** [comment]
is it necessary to pass iterators of `&u8` instead of `u8` directly? That's one of the parts that will be hard to fit with nom's input traits

**Comment by Geal** [comment]
ok, not an issue anymore :)

**Comment by Alexhuszagh** [comment]
> is it necessary to pass iterators of `&u8` instead of `u8` directly? That's one of the parts that will be hard to fit with nom's input traits

I can try to change that for sure, since any iterator of `&[u8]` can go to `u8` via `cloned()`, so that may be worthwhile.

**Comment by Geal** [comment]
that could be nice. In the meantime, I've found a workaround. current work is in https://github.com/Geal/nom/commit/baf5e015b97ec883f1445fefca2630145f5a4d89

**Comment by Geal** [comment]
released in nom 7: https://crates.io/crates/nom/7.0.0
