### ISSUE TITLE
Upgrade to a newer version of bitvec 

### ISSUE THREAD

**Issue by Fiono11** [Geal/nom#1311]
Any prevision of when the crate will be updated to a newer version of bitvec?

**Comment by ValHeimer** [comment]
I would need this too, because when I try to run "cargo tarpaulin" on my crate (using nom) with Rust 1.52.1, I have the following error:

```Rust
error: Broken pipe (or error 32)
error: could not compile `bitvec`
ERROR: cargo_tapaulin: Failed to compile tests! Error: cannot find attribute `skip` in this scope
```

and I hope (let me hope) that it will fix this issue :)

**Comment by orhun** [comment]
Same issue with the tarpaulin here.

**Comment by ValHeimer** [comment]
> I would need this too, because when I try to run "cargo tarpaulin" on my crate (using nom) with Rust 1.52.1, I have the following error:
> 
> ```rust
> error: Broken pipe (or error 32)
> error: could not compile `bitvec`
> ERROR: cargo_tapaulin: Failed to compile tests! Error: cannot find attribute `skip` in this scope
> ```
> 
> and I hope (let me hope) that it will fix this issue :)

@orhun seems to be a Tarpaulin issue, in fact... https://github.com/xd009642/tarpaulin/issues/756

**Comment by Geal** [comment]
erf, that tarpaulin issue is caused by nom https://github.com/xd009642/tarpaulin/issues/756#issuecomment-834249299
and appears in nom's CI too https://github.com/Geal/nom/runs/2865070181?check_suite_focus=true

**Comment by damccull** [comment]
This doesn't happen for me on wsl2 but it's happening with actions-rs on github actions. Anyone know how to fix?

**Comment by Geal** [comment]
bitvec input types are now in the nom-bitvec crate, since the release of nom 7: https://crates.io/crates/nom/7.0.0
