### ISSUE TITLE
Doc comments in number module refer to nom::Endianness enum which does not exist

### ISSUE THREAD

**Issue by delosrogers** [Geal/nom#1314]
- Rust version : `1.54.0-nightly (79e50bf77 2021-05-10)`
- nom version : 6.1.2
- nom compilation features used: default features

## Issue

the docs of many parsers in the `number` module specify that they take either `nom::Endianness::Big` or `nom::Endianess::Little` to specify endianness but the `nom::Endianness` enum doesn't exist. Instead, all the code in the `number` module uses `nom::number::Endianness`

## Possible Fixes

Either update all the docs to use `nom::number::Endianness` or reexport `nom::number::Endianess` in `lib.rs`

I'd be happy to update the docs if that's what you think is the best solution.

**Comment by Geal** [comment]
thank you for the report, it's fixed in 9aa8459
