### ISSUE TITLE
Better name for combinator parameters

### ISSUE THREAD

**Issue by kaoet** [Geal/nom#1317]
The [`flat_map`](https://docs.rs/nom/6.1.2/nom/combinator/fn.flat_map.html), [`map`](https://docs.rs/nom/6.1.2/nom/combinator/fn.map.html), [`map_res`](https://docs.rs/nom/6.1.2/nom/combinator/fn.map_res.html), [`map_opt`](https://docs.rs/nom/6.1.2/nom/combinator/fn.map_opt.html) and [`map_parser`](https://docs.rs/nom/6.1.2/nom/combinator/fn.map_parser.html) combinators just named their parameters `first` and `second`, which provides no information about what should I pass in that parameter.

When using IDE auto-completion, I'm always trying to figure out which order should I pass my inner parser and my mapping function. Should I write `map(my_parser, |x| x.to_string())` or `map(|x| x.to_string(), my_parser)`?

We'd better change the name of parameter to something like `fn map(parser :..., f :...)`.

**Comment by Geal** [comment]
done in 834a2ca
