### ISSUE TITLE
Specifically call out the same or ascending length order required by alt!()

### ISSUE THREAD

**Issue by wraithan** [Geal/nom#132]
#113 mentioned it specifically but then in the docs it implies that you need to make it ascending length order by mentioning the first incomplete will cause an incomplete return. Because it is a pretty easy to make mistake (or maybe I'm just dense) it might be good to call out this constraint very specifically.

**Comment by Geal** [comment]
Hi! What do you mean by call out? Making it more explicit in the documentation?

**Comment by wraithan** [comment]
@Geal yeah, more explicit, such as:

"Make sure to put the parsers in ascending byte length order. If one of the parsers returns Incomplete, alt will return Incomplete, to retry once you get more input. Note that it is better for performance to know the minimum size of data you need before you get into alt."

The docs already let you know this might happen, but making it more explicit would be nice.

**Comment by dirk** [comment]
Also, please correct me if I'm wrong, but there is not a version of `alt!` that tries the next parser on both incomplete and error. It would be really nice to have something like `alt!` that ignored both incomplete and error. (That is, it would try all its parsers and only returns error if none of them match.)

@Geal: If you're not opposed to the above proposal then I'm happy to code it up and open a PR. :smile:

**Comment by Geal** [comment]
Alright, I added a bit more documentation, with examples, in c60b82e.

@dirk that would be great!

**Comment by dirk** [comment]
@Geal: That documentation is great, thanks for adding it! (I only wish I had starting using nom after you had added it. :wink: )

**Comment by dirk** [comment]
@Geal, @wraithan: The `alt_complete!` combinator is now implemented in #168. This—and @Geal's extra documentation—should alleviate the problems people have been having with using `alt!` without fully understanding the internal operation of that combinator. (I know I can't wait to replace my funky `alt!` logic with `alt_complete!`.)

**Comment by wraithan** [comment]
Neat, thanks. Yes the new documentation is very helpful!
