### ISSUE TITLE
map combinator doc example dosn't compile

### ISSUE THREAD

**Issue by vadimcn** [Geal/nom#1321]
- Rust version : 1.52.1 
- nom version : 6.1.2
- nom compilation features used: default

```
use nom::character::complete::digit1;
use nom::combinator::map;
use nom::{error::ErrorKind, Err};
fn main() {
    let mut parser = map(digit1, |s: &str| s.len());
    assert_eq!(parser.parse("123456"), Ok(("", 6)));
    assert_eq!(parser.parse("abc"), Err(Err::Error(("abc", ErrorKind::Digit))));
}
```

Result: "error[E0599]: no method named `parse` found for opaque type `impl FnMut<(&str,)>` in the current scope"

Also, the doc example is missing `use nom::{error::ErrorKind, Err};`

**Comment by Geal** [comment]
the doc is hiding some of the imports since they appear everywhere, maybe I should add them back. What you're missing here is the `nom::Parser` trait.
I updated the doc for map in 275047c
