### ISSUE TITLE
Unnecessary generic parameter restrictions on `nom::combinators::map_parser`

### ISSUE THREAD

**Issue by lilyball** [Geal/nom#1322]
When looking at [`nom::combinator::map_parser`](https://docs.rs/nom/6.1.2/nom/combinator/fn.map_parser.html) from nom 6.1.2, there are multiple trait bounds on the generic parameters that appear to be completely unnecessary. In particular, it requires `I: Clone` even though it never clones the input, and it requires `O1: InputLength` even though it never even touches `O1`, it just passes it directly to the second parser (which has no such requirement). Inspecting the latest source on `master` this is still the case.

https://github.com/Geal/nom/blob/8e09f0c3029d32421b5b69fb798cef6855d0c8df/src/combinator/mod.rs#L215-L229

## Prerequisites

Here are a few things you should provide to help me understand the issue:

- nom version : 6.1.2
- nom compilation features used: default

**Comment by Geal** [comment]
thank you for pointing it out, it is fixed in bbcc41e
