### ISSUE TITLE
Nom 6.2 documentation on docs.rs broken

### ISSUE THREAD

**Issue by maxburke** [Geal/nom#1324]
Hi,

I've been having a pretty difficult time finding documentation for the latest version of nom on docs.rs because all the links to the documentation are broken, for example this link: https://docs.rs/nom/6.2.0/nom/bytes/complete/fn.escaped_transform.html leads to a "no-such-resource" page.

I also noticed that there's a banner on the main project page that said the doc build is broken: https://docs.rs/crate/nom/6.2.0/builds/401812

**Comment by Geal** [comment]
hello, I just published nom 6.2.1 that should fix this. Let me know if you still find some problems

**Comment by maxburke** [comment]
Thank you so much! That is a great help! :slightly_smiling_face:
