### ISSUE TITLE
memchr version constraint makes `nom` incompatible with `regex`

### ISSUE THREAD

**Issue by kpcyrd** [Geal/nom#1330]
hey!

it seems nom is specifically requiring `memchr < 2.4.0`, this makes nom difficult to use with other crates, aho-corasick depends on `memchr >= 2.4.0`, which is required by the latest regex crate:

```
% cargo outdated -R
error: failed to select a version for `memchr`.
    ... required by package `nom v6.2.0`
    ... which is depended on by `der-oid-macro v0.4.0`
    ... which is depended on by `der-parser v5.1.0`
    ... which is depended on by `oid-registry v0.1.3`
    ... which is depended on by `x509-parser v0.9.2`
    ... which is depended on by `sn0int-std v0.21.0 (/tmp/cargo-outdatedRFZFXw/sn0int-std)`
    ... which is depended on by `sn0int v0.21.1 (/tmp/cargo-outdatedRFZFXw)`
versions that meet the requirements `>=2.0, <2.4` are: 2.3.4, 2.3.3, 2.3.2, 2.3.0, 2.2.1, 2.2.0, 2.1.3, 2.1.2, 2.1.1, 2.1.0, 2.0.2, 2.0.1, 2.0.0

all possible versions conflict with previously selected packages.

  previously selected package `memchr v2.4.0`
    ... which is depended on by `aho-corasick v0.7.18`
    ... which is depended on by `regex v1.5.4`
    ... which is depended on by `sn0int v0.21.1 (/tmp/cargo-outdatedRFZFXw)`

failed to select a version for `memchr` which could resolve this conflict
```

## Prerequisites

- nom version : 6.2.0

**Comment by roblabla** [comment]
Why is nom 6.2+ using this bound? Is it an MSRV thing? If so, I feel like this is causing more trouble than it's fixing. If a minor update in a dependency is causing MSRV breakage, the solution is to tell the users *not* to upgrade those dependencies. Otherwise, this causes builds to break due to incompatible ranges, which is a huge pain for people who *are* keeping their rust compilers up to date. I have to pin nom 6.1.2 to workaround the issue...

**Comment by Geal** [comment]
yes, this is a MSRV thing. The real issue is that different libraries have different policies. I tried to make a guarantee for nom 6 and keep it, but memchr and regex broke it. nom 7 will have a different guarantee around MSRV and it'll have some workarounds to avoid dependency issues

**Comment by Geal** [comment]
regex are separated in the nom-regex from nom 7: https://crates.io/crates/nom/7.0.0

**Comment by Ten0** [comment]
If you're unfamiliar with `nom` it's not trivial to get rid of all the macros and those were removed in nom `7`, so the dependency picking failing to accept memchr > 2.4 is super annoying, considering that with old nom versions and new rust compiler versions the compiler will also complain that nom is using patterns that will stop compiling.
It seems weird that MSRV is more a concern than compatibility with newer compiler versions.

**Comment by Geal** [comment]
The last nom 6 was released 3 years ago, are you expecting it to still be supported? Is there a specific issue preventing you from migrating to nom 7, except the lack of macros?

**Comment by Geal** [comment]
Ha, actually I released one a year ago. That should still not be an expectation of long term support though

**Comment by Ten0** [comment]
> Is there a specific issue preventing you from migrating to nom 7, except the lack of macros?

Yes, the additional issue besides the lack of macros would be that it's not my crate. 😅

> That should still not be an expectation of long term support though

I understand. I also wouldn't like to have to maintain all old versions of my crates... The previous version still seems like it was quite usable. Would you mind a PR to the dedicated branch that does the unpinning?
I don't think people should expect maintenance for their Rust version from 5 years ago either...
