### ISSUE TITLE
removing macros

### ISSUE THREAD

**Issue by Geal** [Geal/nom#1343]
nom 7 will finally remove the old parser macros, to focus on functions and traits. Let's synchronize work on macro removal in that issue

**Comment by Geal** [comment]
I'm currently working on the `tests/` directory first

**Comment by nickelc** [comment]
> I'm currently working on the `tests/` directory first

i just finished mp4

**Comment by Geal** [comment]
oh well, thanks :)

**Comment by Geal** [comment]
going through `src/branch/` now

**Comment by Geal** [comment]
since most `macros.rs` files contain the tests, I'll rename the file to `tests`rs` after removing the macros

**Comment by nickelc** [comment]
> since most `macros.rs` files contain the tests, I'll rename the file to `tests.rs` after removing the macros

ok, i'll do that with `src/characters/` too

**Comment by Geal** [comment]
maybe do sequence first, since parsers in char will probably affect a lot of other tests

**Comment by nickelc** [comment]
> maybe do sequence first, since parsers in char will probably affect a lot of other tests

yeah, makes sense. I'll stick to replacing the macros with functions before remove anything

**Comment by Geal** [comment]
done for `branch/` in e95faa4, I'm doing `multi/` now

**Comment by nickelc** [comment]
i have to pause/stop for now and marked my pr as ready for review.

**Comment by Geal** [comment]
alright, thanks

**Comment by Geal** [comment]
done for `multi/` in ff95cff, stopping for now

**Comment by Geal** [comment]
going through `sequence/` now

**Comment by nickelc** [comment]
i take `bytes/`

**Comment by djc** [comment]
Sorry that I don't have much time to actually contribute code, just know that I'm cheering for all of your hard work!

**Comment by Geal** [comment]
it's done for `sequence/` and `bytes/`, I'm taking `character/` now.

no worries @djc , you gave a good push to that effort :)

**Comment by Geal** [comment]
now doing `combinator/`

**Comment by Geal** [comment]
combinator is done too. According to a quick grep on `macro_rules`, we went from 140 macros to 27 :partying_face:

**Comment by Geal** [comment]
none of the remaining ones are parsers though, they are mainly there for internal implementation details

**Comment by nickelc** [comment]
I noticed that with the removal of the `parse_to` macro `ErrorKind::ParseTo` is no longer used.

**Comment by Geal** [comment]
removed in a2b683b

**Comment by Geal** [comment]
released in nom 7: https://crates.io/crates/nom/7.0.0
