### ISSUE TITLE
Make nom a happy library for text based formats

### ISSUE THREAD

**Issue by Binero** [Geal/nom#135]
Right now nom doesn't really like text based formats as much as it likes byte based formats. To make nom easier to use with text based formats, a few additions are needed:

 * A Consumer that handles `str` well should be added. It could parse as much UTF-8 as possible with the current amount of data, and then attempt to parse that. 
 * `str`-based parsers are needed. I already started work on this. #134

**Comment by Geal** [comment]
A few `&str`-related combinators are available in [src/str.rs](https://github.com/Geal/nom/blob/master/src/str.rs), and the functions `alpha`, `digit`, `alphanumeric`, `space`, `multispace`, `eof`, `non_empty` have been updated to take `&[u8]` or `&str` without breaking existing code.

Did you advance on your parsers?

**Comment by joelself** [comment]
Currently the str module doesn't play well with UTF-8 outside of ASCII characters. #156 fixes this and adds more str handling macros and tests.

**Comment by jugglerchris** [comment]
I've just started trying to use nom for parsing a string.  Is there something like `one_of!("abc")` that works with `&str` that I'm missing?

**Comment by Phlosioneer** [comment]
I haven't had any issues using &str in nom. I take UTF-8, convert it into [u8], run it through nom, and use str::from_utf8 at the end.

**Comment by Geal** [comment]
There has been a lot of work on string parsing, and now they are merged with byte slice parsing
