### ISSUE TITLE
Document improvement: length_value

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [Geal/nom#1359]
## Prerequisites

Here are a few things you should provide to help me understand the issue:
- nom version : 6.2.1

There are two arguments, but only the first one was listed.

**Comment by Stargateur** [comment]
I don't understand what you talk about.

Doc:

> Gets a number from the first parser, takes a subslice of the input of that size, then applies the second parser on that subslice. If the second parser returns Incomplete, length_value will return an error. [Source](https://docs.rs/nom/6.2.1/nom/multi/fn.length_value.html)
