### ISSUE TITLE
Cleaver way to avoid code duplication implementing streaming and complete parser

### ISSUE THREAD

**Issue by Stargateur** [Geal/nom#1368]
I work on `abnf-core` https://github.com/duesee/abnf-core/issues/14, it's an utils crate that implement abnf core rule, I currently almost copy paste streaming and complete implementation.

My current idea are:

- use `build.rs`, not great
- Use a macro, not great

Do anyone have a solution to avoid code duplication ?

The diff between two are:

- Trait bound for `I`
- one function error return. (not important)

**Comment by Geal** [comment]
I tried varying on the input before, it did not end well. You could use the [complete](https://docs.rs/nom/7.0.0/nom/combinator/fn.complete.html) combinator to wrap the streaming version, but it could be too general for the use case (especially for cases like many0, etc)
