### ISSUE TITLE
Add example code for switch!

### ISSUE THREAD

**Issue by Geal** [Geal/nom#138]

**Comment by Geal** [comment]
Fixed in 4d3e040

**Comment by Timmmm** [comment]
An example of how to switch on constants would be nice. I can't work out how to make something like this work:

```
named!(parse_stuff,
	switch!(take!(1),
		1u8 => tag!("Foo") |
		2u8 => tag!("Bar") |
		_ => tag!("Unknown")
	)
);
```

**Comment by Geal** [comment]
Please be more specific. What did you write, what's the expected result,
what's the actual result?


Le 23 avr. 2017 23:03, "Tim" <notifications@github.com> a écrit :

An example of how to switch on constants would be nice. I can't work out
how to make something like this work:

named!(parse_stuff,
	switch!(take!(1),
		1u8 => tag!("Foo") |
		2u8 => tag!("Bar") |
		_ => tag!("Unknown")
	)
);

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/Geal/nom/issues/138#issuecomment-296488501>, or mute
the thread

**Comment by Timmmm** [comment]
Err, I basically wrote this:

```
const FOO: u8 = 1;
named!(parse_stuff,
	switch!(take!(1),
		FOO => tag!("Foo") |
		_ => tag!("Unknown")
	)
);
```

And I tried several other things:  `tag!(FOO)`, `value!(FOO)`, `&FOO`. All of them give compilation errors because the switch expects `&[u8]` and none of those are byte slices.

I was expecting there to be a fairly simple way to parse tagged unions like this - I certainly can't see any more appropriate macro than `switch()` but as I said there aren't any examples of using it in this way. Only of switching between byte slices which I'd expect is only really useful in text-based formats (or maybe ones with text tags like wav).

**Comment by Geal** [comment]
Ok, so, two things: if you get compilation errors, include them in the
issue, there's almost no way to debug if you don't give any info.
Second, `take!` returns a slice, so you should match on a slice.


Le 23 avr. 2017 23:18, "Tim" <notifications@github.com> a écrit :

Err, I basically wrote this:

const FOO: u8 = 1;
named!(parse_stuff,
	switch!(take!(1),
		FOO => tag!("Foo") |
		_ => tag!("Unknown")
	)
);

And I tried several other things: tag!(FOO), value!(FOO), &FOO. All of them
give compilation errors because the switch expects &[u8] and none of those
are byte slices.

I was expecting there to be a fairly simple way to parse tagged unions like
this - I certainly can't see any more appropriate macro than switch() but
as I said there aren't any examples of using it in this way. Only of
switching between byte slices which I'd expect is only really useful in
text-based formats (or maybe ones with text tags like wav).

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/Geal/nom/issues/138#issuecomment-296489414>, or mute
the thread
