### ISSUE TITLE
Participating to the Hacktoberfest 2021

### ISSUE THREAD

**Issue by kompass** [Geal/nom#1426]
Hello ! I love your project, and I would like to be able to participate in it as part of the hacktoberfest 2021. https://hacktoberfest.digitalocean.com

Could you add the #hacktoberfest tag to this repo ? That way my participation in this project will be counted and maybe other participants will join us.

**Comment by Stargateur** [comment]
I'm not a big fan of the concept of hacktoberfest.

**Comment by Geal** [comment]
@kompass nom won't be participating in hacktoberfest this year, I wasn considering making a good list of issues for that but had other priorities. I'll see if it can happen next year
