### ISSUE TITLE
Need way to distinguish incomplete input from eof

### ISSUE THREAD

**Issue by jsgf** [Geal/nom#144]
Something like `chain!(tag!("1")? ~ eof, ...)` will return `Incomplete` if given an empty string, because there's no way to distinguish between giving it a partial input and a complete input which will match `eof`. If the input is represented with `&[u8]` I don't think there is a way to do it without some hack like making a magic marker sequence for EOF. 

I guess one way to do it is have a Eof trait which the input can implement which can indicate whether a short input is just incomplete or EOF, and have the `eof` query that rather than directly looking at the input length. Similarly, other functions would only ever return `Incomplete` if the input hasn't hit EOF, otherwise they return errors.

**Comment by mbr** [comment]
possibly related:

```rust
#[macro_use]
extern crate nom;

use std::str;
use nom::digit;

named!(num_f64<f64>,
    map_res!(map_res!(
        recognize!(
            chain!(digit ~ chain!(tag!(".") ~ digit, ||{})?, ||{})
        ),
    str::from_utf8), str::parse)
);

fn main() {
    let input = b"123";
    println!("Result: {:?}", num_f64(input));
}
```

will output

```
Result: Incomplete(Size(4))
```

Changing the `input` to `b"123 "` (extra space) will cause the parser to match:

```
Result: Done([32], 123)
```
