### ISSUE TITLE
Idea: ParseError add into_input

### ISSUE THREAD

**Issue by Stargateur** [Geal/nom#1449]
A lot of nom function require `Clone` on `Input`, many do it to be able to return the input in case of failing, a lot of code in nom do:

```rust
match f.parse(input.clone()) {
  Err(Err::Error(_)) => break Ok((input, acc)),
```

We could instead add a method `into_input` or require `Into<Input>` on generic `Error` to allow such code:

```rust
match f.parse(input) {
  Err(Err::Error(error)) => break Ok((error.into_input(), acc)),
```

This have several pro:

- save CPU cycle, indeed we only need to retrieve the input from the error when needed. (depend on optimization but this could be totally free with this feature)
- Avoid cloning that could be very costly (For example [`nom_locate::LocatedSpan`](https://docs.rs/nom_locate/4.0.0/nom_locate/struct.LocatedSpan.html) could be costly)
- Remove the need for `Input` to implement `Clone`

Con:

- Require either `ParseError` implement a consumed method and so require every `Error` implementation to have this feature or require every `Error` to implement `Into<Input>` (I don't see obvious case where this would be a problem)
- only return the "last" input
- can't be implemented for `()` (that would favorite use `Into` and `AsRef`)

```rust
pub trait ParseError<Input>: Sized {
  fn into_input(self) -> Input;
}
```

---

Some parser also do:
```rust
return Err(Err::Error(E::append(input, ErrorKind::Count, error)));
```

so maybe also have a ` fn input(&self) -> &Input;` too or `AsRef<Input>`

**Comment by Geal** [comment]
There's no guarantee that the error type could return the exact input needed, as some of them immediately convert to an error string (or even just a static message).
So far cloning the input does not cost much: `&[T]`, `&str` and `LocatedSpan` are `Copy` so the cloning is essentially free.
