### ISSUE TITLE
take_split return is not intuitive

### ISSUE THREAD

**Issue by Stargateur** [Geal/nom#1450]
[`take_split()`](https://docs.rs/nom/7.0.0/nom/trait.InputTake.html#tymethod.take_split) doesn't precise what is returned and implementation do:

```rust
fn take_split(&self, count: usize) -> (Self, Self) {
  let (prefix, suffix) = self.split_at(count);
  (suffix, prefix)
}
```

That really not intuitive when you are expected std nomenclature and it's more logical to return it as std do it. Plus, I think this function should return either a Result or a Option (like std should) to avoid unexpected panic.

Open https://github.com/rust-lang/rust/issues/90410.

**Comment by Geal** [comment]
I don't think there's an issue with `take_split`, it's consistent with the rest of nom. Could you avoid opening an issue then immediately opening a PR for an architecture change or new feature without waiting for my opinion? This was not necessary
