### ISSUE TITLE
Can't find is_ascii_hexdigit() in the document

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [Geal/nom#1465]
The `string.rs` demo In the main branch contains a function `is_ascii_hexdigit()`. I can't find it in the document. Does it mean to say `is_hex_digit()`?

**Comment by ThomasdenH** [comment]
[`is_ascii_hexdigit`](https://doc.rust-lang.org/std/primitive.char.html#method.is_ascii_hexdigit) is a function on `char`'s from the standard library!
