### ISSUE TITLE
Tutorials are needed

### ISSUE THREAD

**Issue by SirVer** [Geal/nom#147]
While the example parsers are nice and everything, a lot of the features of this library are rather opaque and hard to grasp. I would appreciate a written tutorial for a streaming parser (i.e. the file to be parsed is to big to fit in memory) and a step by step tutorial how some of the more complex example parsers came together. I think this would help a great deal to make Nom more accessible to newcomers.

**Comment by SirVer** [comment]
After a bit of digging, I found https://fnordig.de/2015/07/16/omnomnom-parsing-iso8601-dates-using-nom/ which is a nice start. But I do not see it linked on this repo anywhere. Did I just miss it?

**Comment by SirVer** [comment]
This is mention of a streaming parser: https://www.reddit.com/r/rust/comments/3tkc0a/parsing_from_file_with_nom/. A solution seems to have been developed in an IRC conversation, but seems like nothing leaked into the examples.

**Comment by SirVer** [comment]
@Geal and I just had a quick discussion in IRC. Summary of the discussion:

- Streaming can be done cheaply by mmaping a file and working directly on the slice of the full file. No state machine like in [the current streaming example](https://github.com/Geal/nom/blob/master/tests/omnom.rs) is then needed. This is not necessarily a portable solution though.
- `try_parse!` is useful in combining parsers in a function. It short-circuits the function on `IResult::Incomplete` and `IResult::Error`, and a returns tuple of `(remaning, value)` on `Done`. There are no easy examples showing this macro off - all simple examples only use macros for all parsers.
- `apply!` can be used to pass additional arguments to functions that take more than just input: `map_res!(apply!(my_function, "hello"))` for `fn my_function(input: &[u8], word: &str) -> IResult<>`. That is useful in many places, but was not apparent to me.
- @geal sees the use for a "from" parser that would take a &[u8] or &str as input and transform directly in what people need with a IResult. He looks into doing that.
- It would be useful to have a simple toy example of a parser that can run over arbitrary long files. An example we discussed is a simple state machine calculator. Each line consists of "ADD 0, 1, 2, 3", with the count of the numbers varying. The binary should intepret such files.

**Comment by Geal** [comment]
closing this now, since there's more documentation available. I'm planning to write more tutorials in the following months

**Comment by brainstorm** [comment]
This one is excellent, by the way, it should be mentioned in the official docs IMHO: https://github.com/benkay86/nom-tutorial
