### ISSUE TITLE
GetOutput trait does not work on IResult<&[u8], &str>

### ISSUE THREAD

**Issue by aphistic** [Geal/nom#148]
After including `use nom::GetOutput` in my code I keep getting the following compile error when I try to call `.output()` on an `IResult<&[u8], &str>`:

no method named `output` found for type `nom::internal::IResult<&[u8], &str>` in the current scope

I tried to fix it myself to send a pull request but I think I don't know enough about rust and traits yet to fix it. =/

**Comment by Geal** [comment]
Fixed in 58b22d7

**Comment by pjungwir** [comment]
@aphistic I'm curious if 1.1.0 fixes the problem for you? I'm having the same issue in my parser here (using 1.1.0):

https://github.com/pjungwir/pjchess/blob/nom-error/src/board.rs#L579

Here is the error for me:

    src/board.rs:579:58: 579:66 error: no method named `output` found for type `nom::internal::IResult<&[u8], board::Board>` in the current scope
    src/board.rs:579     let b = fen(&b"1k6/8/8/8/4Q3/8/8/1K6 w - - 0 1"[..]).output().expect();

**Comment by aphistic** [comment]
@pjungwir I would have to try it again.  I rewrote my code to work around that so I would have to double back and change it.

**Comment by pjungwir** [comment]
Okay thanks for chiming in! @Geal any chance you can follow my link and see if I'm doing something wrong or if it's a problem with nom? I am saying `use nom::GetOutput` but the method still isn't being found. This is my first rust project, but I think I'm doing everything right here. At least there isn't much code to look at. :-)

**Comment by pjungwir** [comment]
Btw feel free to add my project (a parser for chess FEN notation) to the list of example projects. It is text-based and very simple, so I think it'd be a great example for someone to learn from.

And if you have any suggestions to make the nom stuff more idiomatic, let me know! :-)
