### ISSUE TITLE
How to make grammars DRYer?

### ISSUE THREAD

**Issue by Xion** [Geal/nom#149]
I've noticed some repetition in the parser I'm writing, so I tried to write my own combinator by following the pattern used by existing ones:
```rust
/// Parses values that are optionally surrounded by arbitrary number of
/// any whitespace characters.
macro_rules! multispaced (
    ($i:expr, $submac:ident!( $($args:tt)* )) => (
        delimited!(opt!(multispace), $submac!($i, $($args)*), opt!(multispace));
    );
    ($i:expr, $f:expr) => (
        multispaced!($i, call!($f));
    );
);

// intended usage:
multispaced!(char!(","))
multispaced!(is_a!("+-*/"))
multispaced!(alphanumeric)
// etc.
```

This doesn't seem to work: compiler complains about the comma after `$i`, which I interpret as `$submac` being expanded too early into actual parser code.

If there is a way to create simple custom combinators like that easily, it'd be great to have that in the docs.

**Comment by Geal** [comment]
Hi!
could you show me the exact error message you get?

**Comment by Xion** [comment]
Here you go:
```
src/parse.rs:37:49: 37:50 error: no rules expected the token `,`
src/parse.rs:37         delimited!(opt!(multispace), $submac!($i, $($args)*), opt!(multispace));
                                                                ^
```

Thanks for looking into this!

**Comment by Geal** [comment]
The error happens because you have to pass the input to `delimited!`, not directly to `submac`:

```rust
macro_rules! multispaced (
    ($i:expr, $submac:ident!( $($args:tt)* )) => (
        delimited!(opt!(multispace), $submac!($i, $($args)*), opt!(multispace));
    );
    ($i:expr, $f:expr) => (
        multispaced!($i, call!($f));
    );
);
```

See how it is applied by using the `trace_macros` feature:
```rust
trace_macros!(true);
named!(comma<char>, multispaced!(char!(',')));
```

```
named! { a < char > , multispaced ! ( char ! ( ',' ) ) }
multispaced! { i , char ! ( ',' ) }
delimited! { i , opt ! ( multispace ) , char ! ( ',' ) , opt ! ( multispace ) }
opt! { i , multispace }
opt! { i , call ! ( multispace ) }
call! { i , multispace }
delimited1! { i1 , char ! ( ',' ) , opt ! ( multispace ) }
char! { i1 , ',' }
delimited2! { i2 , o2 , opt ! ( multispace ) }
opt! { i2 , multispace }
opt! { i2 , call ! ( multispace ) }
call! { i2 , multispace }
```

`multispaced!` passes its input to `delimited!` which gives it to `opt!(multispace)`, then if successful, gives the remaining input to `char!`.

Is it clear enough? Do you think I should add this to the wiki?

**Comment by Xion** [comment]
I believe you meant:
```rust
delimited!($i, opt!(multispace), $submac!($($args)*), opt!(multispace));
```

That indeed works, and now I can see why! Basically, the chain of passing `$i`nput down the macro wrappers must not be broken, since every parser macro expects it while taking care of its arguments while they are themselves macros.

Something to this effect could definitely be helpful in the wiki. Even linking to this issue would probably help if anyone struggled with the same problem :)

**Comment by Geal** [comment]
It is now documented in [the wiki](https://github.com/Geal/nom/wiki/How-nom-macros-work)
