### ISSUE TITLE
Network producer

### ISSUE THREAD

**Issue by Geal** [Geal/nom#15]
nom should be able to get data from the network and parse it as soon as it is available

**Comment by tupshin** [comment]
As soon as this is supported, I plan on using it for a native rust [CQL transport](https://github.com/apache/cassandra/blob/trunk/doc/native_protocol_v3.spec) client.

**Comment by Geal** [comment]
I'm taking a look, then!

**Comment by Geal** [comment]
768ebebdf81928c56ee47a517fb4cc29a5fce3a8 should do what you want. Instead of a network producer, this is a ReadProducer. It is more general, and can be tested without a network connection.

For now, it does not seek, but it could be possible to add forward seeking.

**Comment by tupshin** [comment]
Awesome,  thanks.  I'll give it a try within the next few days.

**Comment by Geal** [comment]
Hi!

How is it going for you? Did you try the ReadProducer?

**Comment by benaryorg** [comment]
I did look for the `ReadProducer` pretty long, just to find that it was removed in b314b5739c00316c81dffb7108354b61bd40bbc9. Is there any replacement for it?

**Comment by Geal** [comment]
The stream feature will be removed in the next nom version (4.0), since commit 564a93432b52ab99. If someone wants to extract the code and maintain it, feel free to do it, it's in `src/stream.rs`. Otherwise, I would recommend that you check out the (currently in nightly) generators feature, which is much nicer to use. Here's an [example of using nom with generators](https://github.com/geal/generator_nom).
