### ISSUE TITLE
Question: XML parsing for React.js to Solid.js conversion

### ISSUE THREAD

**Issue by rrjanbiah** [Geal/nom#1505]
(Apologies for posting question. Enabling 'Discussion' tab may be better... but, you decide)

nom is suggested in https://www.reddit.com/r/rust/comments/t37twl/hey_rustaceans_got_an_easy_question_ask_here_92022/hyy26ri/?utm_source=reddit&utm_medium=web2x&context=3 But, can't seem to find any XML parsing. Is that possible or any comments on that?

**Comment by rrjanbiah** [comment]
@Xiretza Thanks for your quick reply. Reason is that I'm also interested to create a converter. I'd thought that grammar based parsers will be helpful for writing converters. Looks like I'm wrong with the available set of parsers in Rust

**Comment by LoganDark** [comment]
> @Xiretza Thanks for your quick reply. Reason is that I'm also interested to create a converter. I'd thought that grammar based parsers will be helpful for writing converters. Looks like I'm wrong with the available set of parsers in Rust

Nom is used when you want to write your own XML parser, not when you want to grab one off the shelf. I'd recommend using something else like babel (or similar) for converting between JavaScript frameworks because the ecosystem is so much more mature there.

**Comment by rrjanbiah** [comment]
@LoganDark Thanks a lot for your suggestion

**Comment by LoganDark** [comment]
> @LoganDark Thanks a lot for your suggestion

Babel is what's used by frameworks like React to convert from JSX or TSX syntax into regular JavaScript for the browser, so it's way better suited to source code transformation. Downside is that it's also written in JavaScript, so you can't use Rust for it

**Comment by rrjanbiah** [comment]
@LoganDark Thanks again!

**Comment by Geal** [comment]
I confirm, it would work better to look at an existing XML parser (writing an XML compliant parser from scratch is a *specific* kind of fun)
