### ISSUE TITLE
"Branch master was renamed to main" banner

### ISSUE THREAD

**Issue by LoganDark** [Geal/nom#1508]
The documentation links to this repository using the master branch, causing GitHub to display a "Branch master was renamed to main" banner at the top of the screen. The link should probably still be updated, there's no need to advertise it to everyone.

I know that at least this link in the documentation is affected:

https://github.com/Geal/nom/blob/e99f9e0e7e8ba5670ecc4c0dc89b1d90ff7ba865/src/lib.rs#L61

**Comment by Xiretza** [comment]
Fixed by #1481.

**Comment by LoganDark** [comment]
Wow that's been sitting for a whole quarter 😱

**Comment by Geal** [comment]
fixed in 7f2531d
