### ISSUE TITLE
Why does nom explicitly use 2 space indentation (formatting)?

### ISSUE THREAD

**Issue by dark-fusion** [Geal/nom#1509]
Hello! First of all, I sincerely apologize if this question has been asked before. I performed a few dozen searches through the issue history but found nothing that referred to my question.

Why does `nom` use 2-space indentation for its formatting? I notice that it's not an accident as the [project rustfmt](https://github.com/Geal/nom/blob/main/rustfmt.toml) applies this setting.

I apologize for asking such a trivial question. I have never seen 2-space indentation in a project before and thought it was interesting. I am curious if there is a reason beyond personal preference?

It also makes it a bit more difficult (visually) to read the code as the examples and source code tend to be more tightly packed than I'm used to.

- Rust version : 1.59.0
- nom version : 7.1.0
- nom compilation features used: "default"; so "std" is enabled, which enables "alloc", "memchr/std" and "minimal-lexical/std"

## Test case

N/A

Example test case:

N/A

**P.S.**: I am planning on getting involved in this project as I absolutely love it. I'm absolutely blown away by the code quality. It's really quite a beautiful project.

Thank you!

**Comment by LoganDark** [comment]
Indentation is always just personal preference. Google and some other companies mandate 2-space indentation in all their projects, which I also find quite hard to read, but that's not going to change anything.

**Comment by dark-fusion** [comment]
That's very true. I didn't mean that I'd never seen 2-space indentation in any project; simply not in a Rust project. I believe you're right and that it's just a preference thing. I use the same indentation style myself in some other languages.

It doesn't seem like worthwhile nor productive to keep this ticket open. 4-space indentation is not a hard rule. It's a guideline. 1-space indents sounds awful btw. 😞

Closing this ticket as it's answered / resolved.

Thanks!
