### ISSUE TITLE
`fold_many1` returns `Err` even when successfully applying parser one or more times

### ISSUE THREAD

**Issue by jdidion** [Geal/nom#1538]
rustc 1.62.0 (a8314ef7d 2022-06-27)
nom = "7.1.1"

Calling the `parse_chunk` function errors with "Parsing requires 4 bytes/chars". The input array always has at least 8 bytes and always has a multiple of 8 bytes. All of the bytes in the array are parsed successfully and then it errors when there are zero bytes remaining. The expected behavior is for the function to return the accumulated objects once all the bytes are consumed.

```
extern crate nom;
use nom::multi::fold_many1;
use nom::number::streaming::{le_f64, le_u16, le_u32};
use nom::sequence::tuple;
use nom::IResult;

pub struct MyStruct {
    pub id: u32,
    pub x: u16,
    pub y: u16,
}

fn parse_chunk(i: &[u8]) -> IResult<&[u8], Vec<MyStruct>> {
    fold_many1(
        tuple((le_u32, le_u16, le_u16)),
        Vec::new,
        |mut acc: Vec<_>, (id, x, y)| {
            acc.push(MyStruct { id, x, y });
            acc
        },
    )(i)
}
```

**Comment by Xiretza** [comment]
If that's the behaviour you want, you should use `complete` parsers instead of `streaming`.

**Comment by jdidion** [comment]
I see, thanks. It looks like I've misunderstood how the streaming parsers work. I'll go back and RTFM.
