### ISSUE TITLE
Recursive alt! parsers whose terminal chain! has multiple optional parsers fails

### ISSUE THREAD

**Issue by joelself** [Geal/nom#154]
Phew, that's a mouthful. Here's code to illustrate what I mean:

``` rust
named!(comma<&[u8], &[u8]>, tag!(","));
named!(dot<&[u8], &[u8]>, tag!("."));

named!(recurse<&[u8], ()>,
    alt!(
        complete!(
        chain!(
            tag!("a") ~
            comma ~
            dot ~
            recurse ,
            ||{}
        )) |
        complete!(
        chain!(
            tag!("b") ~
            comma? ~
            dot? ,
            ||{}
        ))
    )
);
```

This will parse strings with multiple `"a,."`'s terminated by a `"b"` with optional comma and optional dot. `recurse("a,.a,.b,.")` and `recurse("a,.a,.b.")` both parse fine, but `"a,.a,.b,"` and `"a,.a,.b"` don't. I've tried this with `opt!` instead of the `?` operator and it works the same way.

The workaround is to add alt chains for just `"b"` and for `"b"` then `comma`, but that kind of defeats the purpose of optional specifier.

**Comment by Geal** [comment]
hello, is this bug still happening?
