### ISSUE TITLE
Might need new module to deal with grapheme clusters according to Unicode Standard Annex #29 rules

### ISSUE THREAD

**Issue by joelself** [Geal/nom#157]
I discovered grapheme clusters while fixing up the str module to handle Unicode and at one point had a copy of the str module except it dealt unicode-segmentation and graphemes instead of just chars (graphemes can be composed of multiple characters for example "\r\n" is a technically a single grapheme, not two characters). Unfortunately, when moving the unicode-segmentation code to a new branch I accidentally deleted the file. It should be pretty easy to recreate though.

Is there any interest in this? I assume since it's a part of Unicode 8 we'll eventually have to support it.

**Comment by Geal** [comment]
Hi, sorry for answering this late.
This might be interesting, can you tell me more about it? Is it something that works on current `&str` type in Rust, or does it need other libraries or traits?

**Comment by joelself** [comment]
I should've linked to the article(s) that I read: here's one talking about [processing grapheme clusters in Perl](https://www.effectiveperlprogramming.com/2011/06/treat-unicode-strings-as-grapheme-clusters/). Also I think I was wrong about being in Unicode 8. It looks like it has been in Unicode for a while. Right now Rust has an unstable iterator for [iterating over grapheme clusters](https://doc.rust-lang.org/1.3.0/std/str/struct.Graphemes.html).

It doesn't look like you can get a slice or array element or elements of grapheme clusters, so it might not even work with Nom as it is. I'm just going to close this unless there's some big demand for parsing based on grapheme clusters.
