### ISSUE TITLE
Add a tuple! macro

### ISSUE THREAD

**Issue by gsingh93** [Geal/nom#159]
I'm currently using nested `pair!` calls to work around limitations with `take_bits!`. This means I'm accessing data like `foo.0.1` and `foo.1`. Maybe we could get a `tuple!` macro? I don't know if this could handle all sizes, if not something like `tuple3`, `tuple4`, etc. wouldn't be too bad.

**Comment by Geal** [comment]
Fixed in 39ec227. `tuple!` can get as many parsers as you want in its arguments (limited by Rust's maximal tuple size, of course)
