### ISSUE TITLE
is_alpha different for char and u8

### ISSUE THREAD

**Issue by tstorch** [Geal/nom#173]
The return values for is_alpha for char and u8 are different. For u8 it`s implemented in nom as

```rust
fn is_alpha(self)    -> bool {
  (*self >= 0x41 && *self <= 0x5A) || (*self >= 0x61 && *self <= 0x7A)
}
```

and for char

```rust
fn is_alpha(self)    -> bool { self.is_alphabetic() }
```

which uses the std library function is_alphabetic for char. But this will also return true for non-Latin characters (see [here](https://doc.rust-lang.org/std/primitive.char.html#method.is_alphabetic)), which is not true for the nom function is_alpha for u8.

**Comment by Geal** [comment]
this is coherent with the way chars work. Most formats have specific needs for their basic tokens, and they can't all be supported in nom.
