### ISSUE TITLE
Separate naming of rules from definition of rules

### ISSUE THREAD

**Issue by eternaleye** [Geal/nom#21]
Simple enough; it'd really just be the following + the closure-based stuff:

```
#[macro_export]
macro_rules! named (
    ($name:ident<$i:ty,$o:ty>, $rule:tt) => (
        fn<$i,$o>( i: $i ) -> IResult<$i,$o> {
            ($rule)( i )
        }
    );
    ($name:ident, $rule:tt) => (
        named!( $name<&[u8], &[u8]>, $rule )
    );
);
```

If you wanted to be really fancy, you could abstract the `_parser!` stuff like so:

```
#[macro_export]
macro_rules! parser (
    (alt, $i:ident, $($rest:tt)*) => ( alt_parser!( $i | $rest ) );
    ...
);
```

and then replace `$rule:tt` and `($rule)( i )` with `$rule:ident, $($rest:tt)*` and `parser!( $rule, i, $rest )` in named.

Then you'd be able to say `named!( foo, take, 3 )` and it wouldn't even have any closure overhead :smiley:

**Comment by Geal** [comment]
It is done now :smile:
