### ISSUE TITLE
Returning IResult::Error when IResult::Incomplete is correct

### ISSUE THREAD

**Issue by ketralnis** [Geal/nom#226]
I have a parser that checks for the word "VALUE" and then some stuff after it. If I match "V" or "VA" or "VAL", I get IResult::Incomplete. But if I match "VALUE", I get IResult::Error. Because this is a network protocol parser, this is a very likely scenario to actually happen and it's important to be able to tell these cases apart. A test case that fails:

    use nom::{space, crlf};

    named!(pub parse<&[u8], &[u8]>,
        chain!(
            tag!("VALUE") ~
            space ~
            message: is_not!(" \r\n") ~
            crlf,
            || {
                message
            }
        )
    );

    #[cfg(test)]
    mod tests {
        use super::*;
        use nom::IResult;
        use nom::Needed;

        #[test]
        pub fn tests() {
            let tests: Vec<(&str, IResult<&[u8], &[u8]>)> = vec![
                ("V", IResult::Incomplete(Needed::Size(5))),
                ("VA", IResult::Incomplete(Needed::Size(5))),
                ("VAL", IResult::Incomplete(Needed::Size(5))),
                ("VALU", IResult::Incomplete(Needed::Size(5))),
                ("VALUE", IResult::Incomplete(Needed::Size(5))),
                ("VALUE ", IResult::Incomplete(Needed::Size(5))),
                ("VALUE h", IResult::Incomplete(Needed::Size(5))),
                ("VALUE hello\r\n", IResult::Done(b"", b"hello")),
            ];

            for &(ref response, ref expected_result) in &tests {
                println!("response: {:?}", *response);
                let parsed = parse(response.as_bytes());
                println!("expect:  {:?}", expected_result);
                println!("got:     {:?}", parsed);
                if *expected_result == parsed {
                    println!("good!");
                } else {
                    println!("bad :(");
                }
                assert_eq!(*expected_result, parsed);
            }
        }
    }

Which fails like:

    response: "V"
    expect:  Incomplete(Size(5))
    got:     Incomplete(Size(5))
    good!
    response: "VA"
    expect:  Incomplete(Size(5))
    got:     Incomplete(Size(5))
    good!
    response: "VAL"
    expect:  Incomplete(Size(5))
    got:     Incomplete(Size(5))
    good!
    response: "VALU"
    expect:  Incomplete(Size(5))
    got:     Incomplete(Size(5))
    good!
    response: "VALUE"
    expect:  Incomplete(Size(5))
    got:     Error(Position(Space, []))
    bad :(
    thread 'protocol2::tests::tests' panicked at 'assertion failed: `(left == right)` (left: `Incomplete(Size(5))`, right: `Error(Position(Space, []))`)', protocol2.rs:52

    failures:
    protocol2::tests::tests

    test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured

**Comment by ketralnis** [comment]
As you'd expect, changing `tag!("VALUE") ~ space` to `tag!("VALUE ")` (with an extra space) shifts the failure to the next `"VALUE "` (also with an extra space) test case

**Comment by Geal** [comment]
Indeed, I should look into `space` and other combinators

**Comment by ketralnis** [comment]
It does look like [space](https://github.com/Geal/nom/blob/master/src/nom.rs#L210-L230) can never return `Incomplete`. But note my previous comment that even eliminating `space` doesn't fix the problem

**Comment by ketralnis** [comment]
This patch fixes my issue:

    diff --git a/src/nom.rs b/src/nom.rs
    index fc1b898..9793af1 100644
    --- a/src/nom.rs
    +++ b/src/nom.rs
    @@ -129,7 +129,7 @@ pub fn digit<'a, T: ?Sized>(input:&'a T) -> IResult<&'a T, &'a T> where
         &'a T: IterIndices+InputLength {
       let input_length = input.input_len();
       if input_length == 0 {
    -    return Error(Position(ErrorKind::Digit, input))
    +    return Incomplete(Needed::Size(1))
       }
    
       for (idx, item) in input.iter_indices() {
    @@ -213,7 +213,7 @@ pub fn space<'a, T: ?Sized>(input:&'a T) -> IResult<&'a T, &'a T> where
         &'a T: IterIndices+InputLength {
       let input_length = input.input_len();
       if input_length == 0 {
    -    return Error(Position(ErrorKind::Space, input));
    +    return Incomplete(Needed::Size(1));
       }
    
       for (idx, item) in input.iter_indices() {

However it breaks the `issue_142` test

    thread 'issue_142' panicked at 'assertion failed: `(left == right)` (left: `Incomplete(Size(12))`, right: `Done([32], [12, 34, 5689])`)', tests/issues.rs:97

That test is so simple:

   let subject = parse_ints(&b"12 34 5689"[..]);
   let expected = IResult::Done(&b""[..], vec![12, 34, 5689]);
   assert_eq!(subject, expected);

   let subject = parse_ints(&b"12 34 5689 "[..]);
   let expected = IResult::Done(&b" "[..], vec![12, 34, 5689]);
   assert_eq!(subject, expected)

That I suspect that more is going on there

**Comment by Geal** [comment]
as of 7ee5d15, `space` and other functions return `Incomplete` on empty input. This will appear in nom 2.0
