### ISSUE TITLE
nom::hex_u32 overflows silently

### ISSUE THREAD

**Issue by lgvz** [Geal/nom#234]
Give `hex_u32` a really long hex string and it won't warn you it doesn't fit into a `u32`. It should probably return Error. If it returned Done it would mean the parsed numbers would be delimited by nothing but *length*.

```rust
src = "ae444453234be1a313456";
let x = nom::hex_u32(src.as_bytes());
assert!(x.is_err());
```
Side notes:
* IMO, using the `<<` operator in numerical (as opposed to binary) computations is bad style, because it will overflow silently while `*` would panic in debug builds.
* `is_a` is a complete misnomer.

**Comment by Geal** [comment]
Thanks for the report. It should be fixed in bde81e1
