### ISSUE TITLE
Inconsistency between not_line_ending and line_ending

### ISSUE THREAD

**Issue by weiznich** [Geal/nom#245]
not_line_ending seems to match anything which is not \r or \n, whereas line_ending matches only \n.
I thing both should use the same set of line ending sequences.

See [this gist](https://gist.github.com/weiznich/eef28628d21a8ff5140bae5f84340ff1) for an example. The testcase full_line_windows fails for me with the following error message:
```
thread 'tests::full_line_windows' panicked at 'assertion failed: 
`(left == right)` (left: `Error(Position(Tag, [13, 10]))`, right: `Done([], ([97, 98, 99], [13, 10]))`)', lib.rs:29
```

**Comment by Geal** [comment]
You're right. I'll have to check that it does not break existing code before updating it. You can write your own line ending parsers in the meantime.
