### ISSUE TITLE
Case insensitive tag!

### ISSUE THREAD

**Issue by Yamakaky** [Geal/nom#251]
Is it possible to match a tag! in a case-insensitive matter?

**Comment by log0ymxm** [comment]
I had this problem too, I came up with [this](https://gist.github.com/log0ymxm/d9c3fc9598cf2d92b8ae89a9ce5341d8) which works great for me. I'm not sure that's the best way to write them, any feedback would be appreciated. Additionally I noticed that there are 4 files with various tag related macros, I'm not sure on what their purpose is. I think I based this one off the macro in `src/bytes.rs`. I'll put this into a PR if I can get some feedback on it.

**Comment by Geal** [comment]
Hi!

this implementation results in 2 allocations (when you call `to_lowercase`). There's a solution without allocations for ASCII strings, that I'll add soon. In the meantime, this one could be used for the `&str` parsers in `src/str.rs` (although the lowercase and uppercase operations for unicode chars are tricky issues).

**Comment by Bobo1239** [comment]
Any updates on this?

**Comment by Geal** [comment]
This is now done in 6f6f80f3a0080e96. The ASCII (`&[u8]`) version should be ok, but the `&str` does not use proper case folding yet
