### ISSUE TITLE
eol parser fails on newline at end of input

### ISSUE THREAD

**Issue by pdewacht** [Geal/nom#252]
The eol parser fails to accept a Unix newline at end of input:

```
nom::eol(b"\n")
=> Incomplete(Size(2))
```

This seems to be due to incorrect use of the `alt` combinator.

**Comment by dommynik** [comment]
`named!(pub eol<char>, alt!(crlf | newline));`

I think the `alt!` should be `alt_complete`. This would generate an `Error` @ crlf instead of `Incomplete`.

**Comment by Geal** [comment]
if you only get one a `\r` and the rest of the input comes later, eol should not return an error. Maybe writing `named!(pub eol<char>, alt!(newline | crlf));` would be better, but generally, you should decide exactly how you want to parse the newlines, instead of relying on the default function.

**Comment by jugglerchris** [comment]
I think this would be fixed by making `crlf` return `Error` instead of `Incomplete` if it's given a single byte which isn't `'\r'`.

**Comment by Geal** [comment]
hi!
As of 7764ad8, this should be fixed, could you test your code with master?
