### ISSUE TITLE
balance tags

### ISSUE THREAD

**Issue by azerupi** [Geal/nom#253]
Is there a way to balance tags in an easy way?

For my use case I want to balance brackets, I have this code:

```rust
fn brackets(input: &[u8]) -> nom::IResult<&[u8], &str> {
    let mut balance: u32 = 0;
    let mut is_unbalanced = |c| {
        match c as char {
            '[' => balance += 1,
            ']' if balance > 0 => balance -= 1,
            ']' => return false,
            _ => {}
        }
        true
    };

    chain!(input,
            tag!("[") ~
        s:  map_res!(
                take_while!( is_unbalanced ), str::from_utf8) ~
            tag!("]"),
        || { s }
    )
}
```

It works fine but I wonder if there is a better, more general way to do this?

**Comment by Geal** [comment]
You can parse that with the `delimited!` combinator and recursive functions ( cf http://rust.unhandledexpression.com/nom/#example for the arithmetic expression parsing example).
