### ISSUE TITLE
namespaces in macros give an error (`tuple!` macro)

### ISSUE THREAD

**Issue by azerupi** [Geal/nom#254]
When using namespaced functions in the `tuple!` macro I got an obscure error.

```rust
named!(pub link <&[u8],(&str,&str)>,
    tuple!( parse::common::brackets, parse::common::parentheses )
);
```

gives the following error:

```
<nom macros>:2:40: 2:41 error: no rules expected the token `,`
<nom macros>:2 { tuple_parser ! ( $ i , 0usize , (  ) , $ ( $ rest ) * ) } ) ;
                                                      ^
```

But when I change that code snippet to

```rust
use parse::common::{brackets, parentheses};

named!(pub link <&[u8],(&str,&str)>,
    tuple!( brackets, parentheses )
);
```

It works!

It looks like the macros (at least the `tuple!` macro) do not play nice with namespaces.

**Comment by Geal** [comment]
Yes, it's an issue related to the type of argument Rust macros can accept. Either it's an expression (which allows closures, variable names, function names, etc), an ident (limited to named things without prefix) or a path (with the namespaces). I have no way to fix it right now.
