### ISSUE TITLE
latest release broke semver's build

### ISSUE THREAD

**Issue by steveklabnik** [Geal/nom#258]
https://travis-ci.org/steveklabnik/semver/jobs/128980487

<- TL;DR: nom now emits a warning, where it didn't before.

**Comment by Geal** [comment]
This is puzzling. I found the culprit in `tuple_parser!`, but cannot find it in `chaining_parser!` :/

**Comment by Geal** [comment]
Ok, no more annoying warnings :) https://travis-ci.org/Geal/nom/jobs/129111209

**Comment by Geal** [comment]
this should work with nom 1.2.3, let me know if it is fixed for you

**Comment by steveklabnik** [comment]
Builds great now! Thanks :heart: https://travis-ci.org/steveklabnik/semver/builds/128980486
