### ISSUE TITLE
Public named functions/parsers

### ISSUE THREAD

**Issue by thehydroimpulse** [Geal/nom#26]
I guess re-exporting would be an alternative to adding a public export option to named parsers. What do you think of adding something like `named!(pub foo<&u8>, ...)`?

**Comment by Geal** [comment]
I see, rust-lang/rust#17436 is now closed and macros can contain pub. This is definitely a good idea. I may not have much time to add it this week, could you try a PR?

**Comment by Geal** [comment]
Now, you can add the pub keyword. It works with the 3 syntaxes:

- `named!(pub tst, tag!("abcd"));`
- `named!(pub tst<&[u8],&[u8]> , tag!("abcd"));`
- `named!(pub tst(input: &[u8]) -> IResult<&[u8], &[u8]>, tag!("abcd"));`

**Comment by thehydroimpulse** [comment]
@Geal Thanks a ton!
