### ISSUE TITLE
How to perform negative lookahead?

### ISSUE THREAD

**Issue by gtors** [Geal/nom#262]
I'm trying to translate this Scala code to Rust:

```scala
def kw(s: String) = s ~ !(letter | digit | "_")
```

But I can't find similar combinator like this http://www.lihaoyi.com/fastparse/#NegativeLookahead . 

```rust
fn kw(input: &[u8], s: &str) -> IResult<&[u8],&[u8]> {
    recognize!(tuple!(input, tag!(s)  ????))
    // In ideally, I think, it should be like this:
    // recognize!(tuple!(input, tag!(s), not!(lookahead!(alt!(alphanumeric | char!('_'))))))```
}
```

**Comment by abiggerhammer** [comment]
FWIW this is basically Hammer's [`h_not`](https://github.com/UpstandingHackers/hammer/blob/master/src/parsers/not.c).

**Comment by gtors** [comment]
@abiggerhammer thx for the tip

**Comment by Geal** [comment]
merged

**Comment by vwkd** [comment]
Was this ever implemented?
