### ISSUE TITLE
Incomplete vs end of input

### ISSUE THREAD

**Issue by jugglerchris** [Geal/nom#271]
I have a `chain!()` parser where if I add an `opt!(foo)` to the end.  If I try to run it with some input where the optional part isn't present, I actually get `Incomplete`, since (as I understand it) the thought is that there may be more input which would make `foo` match.

Is there a way of indicating that this really is the end of the input (eg EOF for a file) so that the `opt!()` can return None and be finished (or something similar)?

**Comment by acatton** [comment]
I used `complete!`, but I think this breaks stream handling (see the function `float_parser`):

```rust
#[macro_use]
extern crate nom;

use nom::is_digit;
use nom::eof;

#[inline]
fn bytes_to_i32(b: &[u8]) -> Result<i32, &str> {
    std::str::from_utf8(b)
        .map_err(|_| "Could not parse utf-8 bytes")
        .and_then(|s| i32::from_str_radix(s, 10).map_err(|_| "Could not parse number"))
}

named!(digits, take_while1!(is_digit));

named!(signed_integer<i32>, chain!(
    sign_chr: one_of!(b"-+")? ~
    n: digits,
    || {
        let sign : i32 = sign_chr.map_or(1, |c|
            match c {
                '-' => -1,
                '+' => 1,
                _ => panic!("This should never happen"),
            }
        );
        bytes_to_i32(n).unwrap() * sign
    }
));

named!(float_parser<f64>, chain!(
    integral: signed_integer ~
    decimal_chr: complete!(preceded!(char!('.'), digits))? ~
    exp: complete!(preceded!(one_of!(b"eE"), signed_integer))?,
    || {
        let mut x = integral as f64;
        let x = x + match decimal_chr {
            Some(d) => {
                let n = bytes_to_i32(d).unwrap() as f64;
                n / (10_f64).powf(d.len() as f64)
            },
            None => 0 as f64,
        };
        // TODO: Handle exponent
        return x;
    }
));


#[cfg(test)]
mod tests {
    use nom::IResult;
    use float_parser;

    #[test]
    fn test_integer() {
        assert_eq!(float_parser(b"1"), IResult::Done(&b""[..], 1_f64));
    }

    #[test]
    fn test_decimal() {
        assert_eq!(float_parser(b"1.2"), IResult::Done(&b""[..], 1.2_f64));
    }
}
```

**Comment by acatton** [comment]
Actually, I just realized that this is the way @Geal recommends to use `complete!()`, since this issue is the same than #144 , which is linked to #145, where [Geoffroy explains](https://github.com/Geal/nom/pull/145#issuecomment-165408356): 

> This idea is interesting. Usually, I recommend that people use the complete! combinator, to transform a `IResult::Incomplete` in an `IResult::Error`.

**Comment by jugglerchris** [comment]
As a simple example, say I have:

```rust
named!(bananas<&str, ()>,
    chain!(
        tag_s!("ba") ~
        many1!(tag_s!("na")),
        || { () }));
```

This will correctly match the start of `"banaX"` or `"banananaX"`, but returns `Incomplete` for just `"banana"`, since it might later be followed by more that matches.  That's correct for a streaming parser, but doesn't work for a non-streaming one if that can appear at the end of the input.

I can make it work for non-streaming input:

```rust
named!(bananas<&str, ()>,
    chain!(
        tag_s!("ba") ~
        many1!(complete!(tag_s!("na"))),
        || { () }));
```

but now it's no longer correct when streaming.

I can't see a way to have the same parser work in both situations - the parser needs to know the difference between "end" and "end so far".

**Comment by jugglerchris** [comment]
Also, when parsing a large file in chunks (what I'd want to use a streaming parser for), this would mean you'd need to call a different parser when you've got the last chunk (since you're now effectively not streaming anymore).

I'm hoping I've missed something obvious that makes this all work.  :-)

**Comment by Geal** [comment]
The end of file is an annoying case. Like, source files that may or may not finished with a line feed, which was an undefined behaviour in some C compilers IIRC.
nom parsers work on buffers, and it is the calling code that must know if we reached the end of the stream or just the end of the currently available data.

I think you could use `switch!` to indicate which parser you use depending on a parameter to the parser, like this:

```
fn line(input:&str, eof: bool) -> IResult<&str, ()> {
    terminated!(input,
        tag_s!("hello"),
        switch!(value!(eof)),
          false => opt_complete!(tag_s!("\n")) |
          true  =>  tag_s!("\n")
        )
    )
}
}
```

I could adapt `switch!` and `cond!` to make that kind of pattern easier

**Comment by jugglerchris** [comment]
I've come back to this, and I think I understand your proposed solution.  I hadn't thought of passing extra arguments into a parser function - that's a useful thing to be able to do!

I'm having problems getting things to actually build after converting a `named!()` into an explicit function.  Unfortunately the macro errors aren't as good as the usual Rust error messages.

I've got as far as this:

```rust
fn header(input: &[u8], at_eof: bool) -> IResult<&[u8], Option<Header>> {
    (closure!(alt!(map!(header_line, Some) |
                   switch!(value!(at_eof),
                       false => map!(header_end, |_| None) |
                       true => map!(header_end_eof, |_| None)))))(input)
}
```

The `closure!()` is my possibly clumsy attempt to convert the `alt!(...)` into something I could call with the input.  That got past some `unexpected end of macro invocation` type errors, but now I have:

```
error[E0001]: unreachable pattern
   --> src/maildir/mod.rs:355:6
    |
355 |     (closure!(alt!(map!(header_line, Some) |
    |      ^ this is an unreachable pattern
    |
    = note: this error originates in a macro from the standard library
```

Any insights that reduce my confusion welcome!

**Comment by jugglerchris** [comment]
Ok, I've used `--pretty expanded` and dropped the expanded version into my source.  The problem is that `switch!()` always adds a default `_ => Error` rule to the match, and since my rules are already exhaustive (for `true` and `false`), that error rule can't ever be hit.

Searches gets me to: https://github.com/rust-lang/rust/issues/4112, which suggests working around this by adding a dummy guard to one of the `match` rules.  `switch!()` doesn't seem to let me do this; if I change the above to match `true if true` I get:

```
no rules expected the token `if`
```

**Comment by jugglerchris** [comment]
FWIW, I worked around it by changing it to:
```rust
    switch!(value!(Some(at_eof)),
         Some(false) => ...,
         Some(true) => ...,
    )
```

**Comment by jugglerchris** [comment]
...and things seem to be working fine now, thanks!  :-)

**Comment by jugglerchris** [comment]
Closing this issue; I'll open a new one for the `switch!()` thing.

**Comment by brandur** [comment]
Hey guys, I've tried to follow this thread through, but am relatively new to nom, and can't quite wrap my head around what the suggested solution for the original problem actually.

The question is regarding the combination of `chain!` and `opt!`. Here's a parser that I've tried to simplify as much as possible to match `(hello|hellothere)`:

``` rust
named!(pub testopt<&str>,
    chain!(
        h: map_res!(tag!("hello"), str::from_utf8) ~
        opt!(tag!("there"))
        ,
        || h
    )
);
```

And a test case:

``` rust
#[cfg(test)]
mod tests {
    use nom::IResult;
    use super::*;

    #[test]
    fn it_parses_testopt() {
        assert_eq!(testopt(b"hellothere"), IResult::Done(&b""[..], "hello"));
        assert_eq!(testopt(b"hello"), IResult::Done(&b""[..], "hello"));
    }
}
```

This allows the first assert to pass, but fails the second with a `Incomplete(Size(10))`.

I don't care about the streaming case, so I tried wrapping my `opt!` in a `complete!` (which seems to have been suggested above), but that just moves the error to a `Error(Position(Complete, []))` instead.

I see that a lot of the suggested solutions have moved away from `chain!` and into the realm of `terminated!` and `closure!`, the use of which I admittedly don't understand given the context. Would someone mind enlightening me in explaining what exactly it would take to get my simple test case doing what I want it to do? Thanks!

**Comment by jugglerchris** [comment]
Hi,

You need to put `complete!()` *inside* the `opt!()`. This means the `Incomplete` at the end of input becomes `Error`, which tells `opt!()` that the optional part isn't there.

**Comment by brandur** [comment]
> You need to put complete!() inside the opt!(). This means the Incomplete at the end of input becomes Error, which tells opt!() that the optional part isn't there.

Ugh. Okay, in retrospect that makes perfect sense and I can't believe that I didn't see it before. Thanks for the help!
