### ISSUE TITLE
Update lazy_static to 0.2.x

### ISSUE THREAD

**Issue by jakeleeme** [Geal/nom#274]
`lazy_static` 0.2.x was released in April 2016. This issue is a TODO to update the dependency in `nom`.

https://github.com/rust-lang-nursery/lazy-static.rs/compare/43739b0d1ca383dc68817f504252359bd1319693...master

At glance, it looks like the code was reorganized and project moved to `rust-lang-nursery`.

**Comment by Geal** [comment]
Fixed in fbb6776
