### ISSUE TITLE
Question about producer / consumer

### ISSUE THREAD

**Issue by antoyo** [Geal/nom#286]
Hello.
I have a question about the producer / consumer pattern.
I am not sure to understand how to use this pattern.

For instance, building upon the `arithmetic` example, I have the following code:
```rust
fn main() {
    let mut data = vec![];
    let mut buffer = [0; 3];
    let mut file = File::open("expression").unwrap();

    loop {
        {
            let result = expr(&data);
            if let nom::IResult::Done(_, _) = result {
                break;
            }
            println!("{:?}", result);
        }
        file.read_exact(&mut buffer);
        data.extend_from_slice(&buffer);
    }
}
```
where `expression` is a file containing `3 + 3`.

This code produces the following result:
```
Incomplete(Size(1))
Incomplete(Size(4))
```
Which, I think, makes sense.

Moreover, after the loop, I can get the expected result `Done(&[], 6)`.

I tried using a producer and a consumer to do exactly the same:
```rust
fn main() {
    let mut producer = FileProducer::new("expression", 3).unwrap();
    consumer_from_parser!(Consumer<i64>, expr);
    let mut consumer = Consumer::new();

    for _ in 0 .. 2 {
        let result = producer.apply(&mut consumer);
        println!("{:?}", result);
    }
}
```
But I get this unexpected result:
```
Continue(Await(Size(4)))
Continue(Await(Size(4)))
```
and I cannot get the expected `6` result.

Could you explain me how `Producer` and `Consumer` work and guide me to make the last code work as the first, please?

Thanks.

**Comment by Geal** [comment]
when you do `FileProducer::new("expression", 3)`, the internal buffer of the producer is fixed to 3 bytes, and the parser tells you it needs 4 bytes. In your original example, you read the file 3 bytes at a time, and extend `data`, so the buffer grows. You can use the `resize()` method of the file producer.

Right now, I would not recommend using the producers and consumers of nom, and instead switching to something based on streams in futures-rs or tokio. It's still a bit young, but it's much more flexible that what I built.

**Comment by antoyo** [comment]
Thanks, you were right: using `resize` fixes this example:
```rust
fn main() {
    let mut buffer_size = 3;
    let mut producer = FileProducer::new("expression", buffer_size).unwrap();
    consumer_from_parser!(Consumer<i64>, expr);
    let mut consumer = Consumer::new();

    for _ in 0 .. 2 {
        {
            let result = producer.apply(&mut consumer);
            println!("{:?}", result);
        }
        buffer_size += 3;
        producer.resize(buffer_size);
    }
}
```

I will look at `futures-rs` soon.

Thanks for your help.
