### ISSUE TITLE
length_value! with tuple! results in compilation error

### ISSUE THREAD

**Issue by fuine** [Geal/nom#293]
I'm trying to build a simple parser, but compiler yields this error:
```
error[E0308]: mismatched types
  --> src/main.rs:20:67
   |
20 | named!(f<&[u8], Vec<(u64, u64)> >, length_value!( be_u64, tuple!( be_u64 , be_u64 ) ) );
   |                                                                   ^^^^^^ expected &[u8], found fn item
   |
   = note: expected type `&[u8]`
   = note:    found type `fn(&[u8]) -> nom::IResult<&[u8], u64> {nom::be_u64}`
```
Is this some kind of bug or am I doing something wrong?
My nom version is 1.2.4 and i'm compiling code with rustc 1.13.0-nightly (1576de0ce 2016-08-21)

**Comment by vickenty** [comment]
It seems that `length_value!` currently does not support a macro as a repeated value, only a function or a named parser: http://play.integer32.com/?gist=dbb0f5390ff1bbb2e41ff06a02660dc8
