### ISSUE TITLE
Use nom with futures

### ISSUE THREAD

**Issue by antoyo** [Geal/nom#295]
Hello.
I wonder how to use `nom` with a `Stream` from the `futures` crate.
Do I need to implement the `GetInput` trait for [`BufReader`](https://docs.rs/futures-io/0.1.0/futures_io/struct.BufReader.html)?
Do you have any code example using `nom` with `futures`?
Thanks.

**Comment by Geal** [comment]
Not yet, but this is something I want to work on. In the meantime, I experimented with the tokio-minihttp code to see if I can replace the parser with a nom one: https://gist.github.com/Geal/c138e9f1e538bbf373f8d083de1c9c9e
the nom parser for HTTP requests is not released yet, but it will be soon.

**Comment by bschwind** [comment]
I'd just like to say I'm very interested in this as well. I've been working on using Nom with Mio and trying out the Producer/Consumer functionality of Nom, but in a previous [issue](https://github.com/Geal/nom/issues/286#issuecomment-241019910) you recommended against that in favor of something like streams from futures-rs.

I'm kind of a newbie for the lower level parts of Rust, but let me know if there's anything I can do to help! I see a lot of promise in combining Nom with async byte streams.

**Comment by jugglerchris** [comment]
Futures and tokio seem to be aimed at network I/O; are they at all useful as a replacement for FileProducer/MemProducer?  Asking in the hope of reducing my ignorance in this area.  :-)

**Comment by antoyo** [comment]
I've used futures and tokio.
@jugglerchris is right: tokio is for network I/O (or at least, non-file asynchronicity, since it uses epoll).
So, while it might be useful for parsing data from the network, it's probably useless to combine tokio with nom to parse files.

An idea could be that nom implements its own event loop (to replace `tokio-core`) so that we can spawn futures on it. This event loop would read part of the file into a buffer when needed and end when the end of file is reached.
I'm not sure if that makes sense.

**Comment by Geal** [comment]
I think an event loop to use nom would be a separate project, and that would be a lot of work. In the meantime, I have a good example of nom usage with tokio-io in the lapin AMQP client: https://github.com/sozu-proxy/lapin/blob/master/futures/src/transport.rs#L18-L104
