### ISSUE TITLE
take_bits documentation bug

### ISSUE THREAD

**Issue by gz** [Geal/nom#297]
The documentation for take_bits has an example with take_pair instead:
https://github.com/Geal/nom/blob/a23684e3f8939b1f651001fd8c557701c8a778d0/src/bits.rs#L111

**Comment by jdeeny** [comment]
The line 
```rust
named!( take_pair<(u8, u8)>, bits!( pair!( take_bits!( u8, 3 ), take_bits!(u8, 5) ) ) );
```
from the example defines the function `take_pair` using `named!`. The definition of `take_pair` makes use of the `take_bits!` macro, but I can see how it could help clarity if `take_bits!` was used directly in an assert somewhere in the example.

**Comment by gz** [comment]
Meanwhile, I figured out how to use take_bits! for my problem :) --  I can submit a pull request that makes some additions to the documentation...
