### ISSUE TITLE
Making a function generic over producers

### ISSUE THREAD

**Issue by jugglerchris** [Geal/nom#333]
This might be another "not using as intended" problem.  I've got a function which takes a `FileProducer` and applies it to a (actually two) `Consumer`.  Now I've tried to make it more generic so that it works with `MemProducer` too, but I think their lifetime parameters are not compatible.

If I try to have a function:

```
pub fn consume_from<'a, 'b, 'c, T: Producer<'a, &'b [u8], Move>>(producer: &'c mut T) { }
```

then actually use the consumer in the function, I start getting conflicting lifetime requirements; but I can get it to work passing concrete types in.  FWIW, here's a cut-down example of the kind of thing I'm trying to do (which doesn't compile).  I'd understand if this is closed with a pointer to an example of using futures that I could start trying out.

``` rust
#[macro_use]
extern crate nom;
use nom::*;

fn from_file_producer(prod: &mut FileProducer) {
    unimplemented!()
}
fn from_mem_producer(prod: &mut MemProducer) {
    unimplemented!()
}
// These are the options: 
// impl<'x, 'b> Producer<'b, &'x [u8], Move> for MemProducer<'x>
// impl<'x> Producer<'x, &'x [u8], Move> for FileProducer

struct MyConsumer {
}
impl<'a> Consumer<&'a [u8], (), (), Move> for MyConsumer {
    fn handle(&mut self, input: Input<&'a [u8]>) -> &ConsumerState<(), (), Move> {
        unimplemented!()
    }
    fn state(&self) -> &ConsumerState<(), (), Move> {
        unimplemented!()
    }
}

fn from_producer<'a, 'b, 'c, T: Producer<'b, &'a [u8], Move>>(prod: &'c mut T) {
    also_from_producer(prod)
}
fn also_from_producer<'a, 'b, 'c, T: Producer<'b, &'a [u8], Move>>(prod: &'c mut T) {
    let mut consumer = MyConsumer{};
    loop {
        let result = prod.apply(&mut consumer);
        match result {
            _ => unimplemented!(),
        }
    }
}

fn blah() {
    let mut mem = MemProducer::new(b"asdf", 4096);
    from_mem_producer(&mut mem);
    let mut file = FileProducer::new("asdf", 4096).unwrap();
    from_file_producer(&mut file);

    from_producer(&mut file);
    from_producer(&mut mem);
}

```

**Comment by Geal** [comment]
The stream feature will be removed in the next nom version (4.0), since commit 564a93432b52ab99. If someone wants to extract the code and maintain it, feel free to do it, it's in `src/stream.rs`. Otherwise, I would recommend that you check out the (currently in nightly) generators feature, which is much nicer to use. Here's an [example of using nom with generators](https://github.com/geal/generator_nom).
