### ISSUE TITLE
char_if!(Fn(char) -> bool)

### ISSUE THREAD

**Issue by ghost** [Geal/nom#334]
A parser that reads one symbol/char, evaluates the passed function, and returns Done/Error depending on the result.
The behavior of char_if!(|c| true) is equal to char! .

**Comment by Evrey** [comment]
You mean the behaviour of `char_if!(|c| c == 'C')` is equal to `char!('C')`. I implemented that macro today and wanted to write a similar issue. Here's my impl, which can be used as shown above to re-implement `char!` *(changed lines highlighted)*:

```Rust
macro_rules! char_if (
    ($i:expr, $c: expr) => ({
        use nom::lib::std::result::Result::*;
        use nom::lib::std::option::Option::*;
        use nom::{Err,Needed,ErrorKind,Context,need_more};

        use nom::Slice;
        use nom::AsChar;
        use nom::InputIter;

        match ($i).iter_elements().next().map(|c| {
            let chr = c.as_char(); // <== we need that later
            let b = ($c)(chr); // <== call fn instead of ==
            (b, chr) // <== need both now
        }) {
            None             => need_more($i, Needed::Size(1)),
            Some((false, _)) => { // <== specific char is irrelevant
                let e: ErrorKind<u32> = ErrorKind::Char;
                Err(Err::Error(Context::Code($i, e)))
            },
            Some((true,  c)) => Ok(( // <== use c to not do double work
                $i.slice(c.len()..), // <== calculating the length changed
                c // <== no more iter elements etc needed
            )),
        }
    });
);
```

**Comment by Geal** [comment]
not sure this is still useful, I'm closing this now, feel free to reopen if there's a good case for this combinator

**Comment by gavrilikhin-d** [comment]
There is a good case:
In my language types must start from uppercase letter. I've never imagined that parse single uppercase letter would be this hard

**Comment by gavrilikhin-d** [comment]
Currently I use:
```rs
verify(anychar, |c: &char| c.is_uppercase())
```
This looks more like a hack

**Comment by Geal** [comment]
you can use [satisfy](https://docs.rs/nom/latest/nom/character/complete/fn.satisfy.html)
