### ISSUE TITLE
Documentation: missing examples for some macros

### ISSUE THREAD

**Issue by pashinin** [Geal/nom#337]
I'd like to have not only description of what macros does but also to see basic situations (examples) of how would I use it.

Just for example:
- http://rust.unhandledexpression.com/nom/macro.closure!.html
- http://rust.unhandledexpression.com/nom/macro.flat_map!.html
- http://rust.unhandledexpression.com/nom/macro.separated_list!.html
- ...

Documentation would be really better with examples for each macros

**Comment by Geal** [comment]
thanks for the report, I'll add those documentation bits for the 2.0 release

**Comment by pashinin** [comment]
thanks for nom

**Comment by keeperofdakeys** [comment]
In a related case, it would be good for named! to be able to insert documentation for the functions it generates. IIRC this is possible, but I can't recall how off hand (I think using a doc attribute). Especially in the nom library itself, there are some parsers generated with named that have no documentation.

**Comment by Geal** [comment]
there's more documentation for combinators now, feel free to reopen if you see some of them missing
