### ISSUE TITLE
Easy way to do case-insensitive tag!() matching?

### ISSUE THREAD

**Issue by ms705** [Geal/nom#339]
Hi!

I am writing a SQL parser that would ideally be able to match on all sorts of keyword capitalization variants (e.g., `SELECT` vs. `select` vs. `Select` vs. `SeLeCt`), since SQL keywords are case-insensitive. Is there an easy way to do this with nom? I'm currently using `tag!("select")` etc. to match keywords in [the parser](https://github.com/ms705/nom-sql).

Options I have considered:
1. Transform the whole input (query) string into lowercase before processing. This is what my parser currently does, but it is incorrect, since SQL table and column names are typically case-sensitive (although this depends on the database and its configuration).
2. Write a parser that takes a specific number of bytes as input, transforms them to lowercase, and then matches them against an expected string. This seems like a sensible approach, but I'm not sure how to best express it in nom -- I tried a few things that didn't end up working, but that may well be due to still limited familiarity with nom.

Parser code example:

``` rust
named!(pub selection<&[u8], SelectStatement>,
    chain!(
        tag!("select") ~
        space ~
        distinct: opt!(tag!("distinct")) ~
        space? ~
        fields: fieldlist ~
        space ~
        tag!("from") ~
        space ~
        table: table_reference ~
        space? ~
        cond: opt!(where_clause) ~
        space? ~
        limit: opt!(limit_clause) ~
        space? ~
        alt!(eof | tag!(";") | line_ending),
        || {
            SelectStatement {
                table: String::from(table),
                distinct: distinct.is_some(),
                fields: fields.iter().map(|s| String::from(*s)).collect(),
                where_clause: cond,
                group_by: None,
                order: None,
                limit: limit,
            }
        }
    )
);
```

Here, I would like the matching on literal keywords ("select", "distinct", and "from") to be case-insensitive.

**Comment by Geal** [comment]
This is planned for the 2.0 release, see #251 and #289

**Comment by Geal** [comment]
this is done in 6f6f80f, but the implementation does not do proper case folding for utf8 strings yet. This should be fine for SQL statements, though

**Comment by ms705** [comment]
Awesome, thanks a lot! :smile: 

I used @log0ymxm's solution from #251 for the moment, but I'll migrate to `tag_no_case!` in due course.

**Comment by Geal** [comment]
for byte slices, tag_no_case is nice, since there's no allocation :)
