### ISSUE TITLE
error: macro undefined: 'named!'

### ISSUE THREAD

**Issue by RReverser** [Geal/nom#343]
I'm apparently missing something very simple, but I've created a sample lib create with following code:

```rust
#![macro_use]
extern crate nom;

named!(TAB, char!('\u{0009}'));
```

and getting following error:

```
error: macro undefined: 'named!'
 --> src\lib.rs:4:1
  |
4 | named!(TAB, char!('\u{0009}'));
  | ^^^^^
```

As I've installed & referenced the crate, and added `macro_use`, what else I might be missing?

**Comment by RReverser** [comment]
Nevermind, was a silly mistake to use `#!` instead of just `#` for this case :(

**Comment by Geal** [comment]
don't worry, it happens :)
