### ISSUE TITLE
No rules expected the token `,` for nom::alphanumeric is used in alt! macro

### ISSUE THREAD

**Issue by KalitaAlexey** [Geal/nom#345]
The compiler emits error:

```
error: no rules expected the token `,`
 --> <nom macros>:2:22
  |
2 | { alt_parser ! ( $ i , $ ( $ rest ) * ) } ) ;
  |                      ^
```

for code:

``` rust
#[macro_use]
extern crate nom;

named!(mark, alt!(
    tag!("-") |
    tag!("_") |
    tag!(".") |
    tag!("!") |
    tag!("~") |
    tag!("*") |
    tag!("'") |
    tag!("(") |
    tag!(")")
));

named!(unreserved, alt!(nom::alphanumeric | mark));
```

I found a workaround:

``` rust
use nom::alphanumeric;
named!(unreserved, alt!(alphanumeric | mark));
```

I think this is a bug. Probably in rustc. I opened the issue in this repository, because I think that you know more about macro.

**Comment by SnirkImmington** [comment]
> ```rust
named!(unreserved, alt!(nom::alphanumeric | mark));
```

> ```rust
named!(unreserved, alt!(alphanumeric | mark));
```

I've run into this as well, could the macro be changed to request a `path` instead of an `ident`?

@KalitaAlexey This isn't a rustc bug. Macro errors suck.

**Comment by KalitaAlexey** [comment]
@SnirkImmington This is why I opened this issue here.

**Comment by eugene-bulkin** [comment]
Any update on this? This bug is still present and can be somewhat annoying if the path is ambiguous without the namespace.

**Comment by Geal** [comment]
@eugene-bulkin this requires changing all the combinators, and may be a breaking change in some cases. I have other bugs I need to work on before I get to this one, but this will probably go in the next major version.

**Comment by eugene-bulkin** [comment]
@Geal Gotcha. It's only a problem if you're doing something like I was where you do `alt!(foo::thing | bar::thing)` and it gets confused, which is a relatively niche case. In the meantime the earlier fix works.

**Comment by Geal** [comment]
This was done in 8dd0bf4, this should be fixed for `alt` and others. For `do_parse`, it's not possible because a `path` macro matcher cannot be followed by `>>`
