### ISSUE TITLE
Why are `apply!` and `apply_m!` separate?

### ISSUE THREAD

**Issue by azerupi** [Geal/nom#360]
In the combinators, a distinction is being made between `X!` and `X_m!` combinators, that work on functions and methods respectively:
- `apply!` vs `apply_m!` 
- `call!` vs `call_m!`

Is there a technical reason for separating them instead of allowing one macro to handle both cases? If not, I think it's worth merging corresponding variants into one macro in order to make it less confusing for users.

**Comment by Geal** [comment]
the `*_m` macros work when you want to make a parser as a method of a struct (to access and modify state while parsing). I don't remember what was the issue, but apparently folding them in the same macro made some errors in token parsing. Anyway, I'd like to keep them separated, but they probably could be renamed to something less confusing with the other macros.
