### ISSUE TITLE
Provide some way to turn an `IResult` to a `Result`.

### ISSUE THREAD

**Issue by AndyShiue** [Geal/nom#371]
I can't find an easy way to turn an `IResult` to a `Result`. Is there an easy way to do that? I would want  to turn incompleteness into an error like `complete!` does.

**Comment by Geal** [comment]
there are traits for that, but it is not released yet https://github.com/Geal/nom/blob/149a50d586fb8ef4e11a1a46401565031de90676/src/simple_errors.rs#L31-L48
