### ISSUE TITLE
Best way to disallow keywords when parsing an identifier

### ISSUE THREAD

**Issue by bouk** [Geal/nom#377]
Hi!

I'm having a lot of fun playing around with nom.

I have something like this:

```
named!(identifier<&str>, map_res!(
  recognize!(many1!(one_of!("abcdefghijklmnopqrstuvwxyz"))),
  str::from_utf8
));
```

How do I make sure that it doesn't match the following:

```
named!(keyword, alt_complete!(
  tag!("def") |
  tag!("else") |
  tag!("if")
  // ...
));
```

I've tried doing something like this:

```
named!(identifier<&str>, map_res!(
  tuple!(
    peek!(not!(keyword)),
    recognize!(many1!(one_of!("abcdefghijklmnopqrstuvwxyz"))),
  )
  str::from_utf8
));
```

This will also disallow stuff like `ifa` though. What's the best way to go around this?

**Comment by Geal** [comment]
what kind of input do you want to recognize? Anything made of lowercase letters, but not any of the keywords?

**Comment by bouk** [comment]
Correct, it should Error of the result of matching all subsequent lowercase characters matches any of the keywords

**Comment by bouk** [comment]
Any help with this? Should I just wrap identifier in a function that checks the result byteslice against all the identifiers and error if it matches any of them?

**Comment by Geal** [comment]
this should probably be done with `verify!`
