### ISSUE TITLE
`take_while1_s!` behaves like `take_while1!`

### ISSUE THREAD

**Issue by panicbit** [Geal/nom#392]
Expected behavior:
`take_while1_s!` accepts `char -> bool` and returs `&str`

Actual behavior:
`take_while1_s!` accepts `u8 -> bool` and returs `&[u8]`

nom: 2.0.1

**Comment by Geal** [comment]
could you share the code you're using and the errors you get? Because this works:
```rust
fn alphabetic(chr: char) -> bool { (chr >= 0x41 as char && chr <= 0x5A as char) || (chr >= 0x61 as char && chr <= 0x7A as char) }
named!( alpha<&str,&str>, take_while1_s!( alphabetic ) );
let r = alpha("abcd\nefgh");
assert_eq!(r, Done("\nefgh", "abcd"));
```

**Comment by panicbit** [comment]
Hm weird. I probably made a mistake. I don't have the problematic code (probably should have posted it :disappointed:) and wasn't able to recreate it because I'm getting other difficult to debug errors that I don't feel like dealing with right now.
Since your code negates my claim I'm closing this.
