### ISSUE TITLE
On Custom Errors

### ISSUE THREAD

**Issue by nickbabcock** [Geal/nom#394]
I've been playing around with nom and rust, I'm far from an expert but I wanted to address what I think is a major hurdle for nom users: errors. I think I've yet to see comprehensive error reporting with nom. Maybe it's just because I'm not familiar with parse combinators, but I feel like if recursive descent parsers can provide good error messages then so can parser combinators :smile:

Here's a toy example: decoding a utf8 string that is length prefixed and null terminated -- taken from a project I'm working on: [boxcars](https://github.com/nickbabcock/boxcars) 

```rust
/// Text is encoded with a leading int that denotes the number of bytes that
/// the text spans.
named!(text_encoded<&[u8], &str, BoxcarError>,
    fix_error!(BoxcarError,
    complete!(do_parse!(size: le_i32 >> data: apply!(decode_str, size) >> (data)))));

/// Reads a string of a given size from the data. The size includes a null
/// character as the last character, so we drop it in the returned string
/// slice. It may seem redundant to store this information, but stackoverflow
/// contains a nice reasoning for why it may have been done this way:
/// http://stackoverflow.com/q/6293457/433785
fn decode_str(input: &[u8], size: i32) -> IResult<&[u8], &str> {
    do_parse!(input, data: take_str!(size - 1) >> take!(1) >> (data))
}
```

What are all the errors that one may want to expose from just these two functions:

- Not enough data to read size of string (context: how much more data is needed)
- Nonsensical size of string (negative or too large)
- Not enough data to read string (context: how much more data is needed, and maybe even stringify what was read)
- String is not valid utf8 (context: what bytes were invalid and location of invalid bytes in string)
- String contains nonsensical characters (context: what's the string and invalid characters, and location of said characters)
- String does not end with a null character

So an enum like the following could be appropriate for errors (pseudocode):

```rust
#[derive(PartialEq, Debug, Clone, Copy)]
pub enum BoxcarError {
    SizeIncomplete(i32),
    InvalidSize(i32),
    StringIncomplete { decoded: String, needed: i32 },
    NonUtf8String { location: i32, invalid: &[u8] },
    InvalidString { decoded: String, invalid: char },
    MissingNullTermination
}
```

The end goal would be propagate all these errors (with the mentioned context) to upstream callers. Besides writing the actual code to map these errors, I've also encountered other problems:

- The custom error type is viral. I'm assuming most people, when using nom, focus on the happy path first until satisfaction. Then when they go to add in custom errors to the lowest level combinator, find a whole swath of compiler errors, as higher level functions now need to reflect that they need to return a custom error type, and convert default errors to the custom type. This may be a turn off, as any non-trivial parser would need a hefty amount of code changes. To fix this, it could be prudent to introduce error handling in [Making a new parser from scratch](https://github.com/Geal/nom/blob/80a1deab58d1faf41c05a5d741d9e3f51bde3a55/doc/making_a_new_parser_from_scratch.md). It's hard to make a solid house when the foundation is shaky :house:

- `fix_error` is viral. All low level combinators return the default custom error type, which means that I have to `fix_error` in order to get a combinator to return my custom error type. I could wrap all the low level combinators like `le_u32` inside another function that simply wraps it in `fix_error`, but duplicating this code for all the low level combinators seems a bit like drudgery. Since the low level combinators should never return a custom error code, maybe there is some inference magic where they can return the custom error type of their neighbors in `do_parse`.

- This may be more of a bug report but `fix_error` should not overwrite `ErrorKind` that is not custom because seeing a bunch of nom errors converted into `Fix` is very hard to look at.

- Less of a problem, and more of a feature request, but for [boxcars](https://github.com/nickbabcock/boxcars), backtracking is not needed, and remembering to wrap everything in `complete!` is a bit cumbersome. Disabling backtracking would be a pipedream :smile:

Sorry for this wall of text -- how to act on it may be a bit nebulous.

Anyways, I hope I've conveyed some places where I see some great improvement, but hopefully it's not anything that a little bit of doc + code change can't fix. Nom's been a great library so far, I'm just interested in seeing it to the next mile

**Comment by Geal** [comment]
hey!

I'm sorry, I don't have the time to answer in length today, but in the meantime, did you take a look at http://rust.unhandledexpression.com/nom/error_management.html ? There might be some things to improve in that guide as well

**Comment by Geal** [comment]
so now this should work better (in the "result" branch). The custom error type will work correctly as long as it implements `From<u32>`, then all combinators should take care of conversion.

**Comment by mikolajpp** [comment]
I just found this thread, and perhaps some information on how to handle 
custom errors be best added to documentation, at least it was non-obvious to 
me that I need From trait on my error type.
