### ISSUE TITLE
Recommended approach to backslash escaping?

### ISSUE THREAD

**Issue by zslayton** [Geal/nom#395]
I'm trying to parse a JSON-like language and am having difficulty figuring out a good way to parse strings that contain escaped versions of their delimiters.

This snippet, from the [`json.rs`](https://github.com/Geal/nom/blob/master/tests/json.rs), only seems to support strings with letters and numbers; punctuation and whitespace appear to be illegal:
```rust
named!(string<&str>,
  delimited!(
    tag!("\""),
    map_res!(escaped!(call!(alphanumeric), '\\', is_a!("\"n\\")), str::from_utf8),
    tag!("\"")
  )
);
```
I tried replacing `alphanumeric` above with `is_not_s!("\"")`. This permits a variety of characters, but still does not allow me to have escaped quote characters in string. (e.g. `"An 8\" sub sandwich"`). The escaped quote `"` becomes `\"`, which still contains a `"`.

Is there a prescribed approach for achieving this in 2.0? Or would I need to roll my own solution somehow?

Thanks! `nom` is really impressive!

**Comment by Geal** [comment]
I have difficulties understanding what you're trying to achieve here. Which quote is escaped? There are two versions: `escaped!` recognizes a string with escaped chars, `escaped_transform!` recognizes the string and replaces the escaped chars by their real version.

**Comment by zslayton** [comment]
Ah, [`escaped_transform!`](http://rust.unhandledexpression.com/nom/macro.escaped_transform.html) appears to be what I want. Thanks!
