### ISSUE TITLE
Macro compile error: is_a!

### ISSUE THREAD

**Issue by thehydroimpulse** [Geal/nom#4]
Not sure if this was an accident or not: https://github.com/Geal/nom/blob/0f5ef87483ed45c0cc623a9f5d4403bc645b9aba/src/nom.rs#L375

**Comment by Geal** [comment]
Thank you for catching that one. This is indeed a bug, but I did not see it because there are no unit tests for the `is_a!` macro. I'll add some.

Fixed in 4949f71156b1c01ac3845abc13ad1e1eb5702cc5.
