### ISSUE TITLE
Permutation parser

### ISSUE THREAD

**Issue by Geal** [Geal/nom#40]

**Comment by filipegoncalves** [comment]
What exactly does this mean?

**Comment by Geal** [comment]
That's a combinator already present in [Parsec](https://hackage.haskell.org/package/parsec-permutation-0.1.2.0/docs/Text-Parsec-Permutation.html).

Basically, it will return a tuple of results of its children, but its children can be called in arbitrary order. This is useful for formats like PNG or MP4.
