### ISSUE TITLE
Problem when using with missing_docs attribute

### ISSUE THREAD

**Issue by xpe** [Geal/nom#404]
In some Rust projects, I use `#![deny(missing_docs)]` or `#![warn(missing_docs)]` [attributes][2] as explained in the Rust book's [Missing Documentation section][1]:

> Sometimes you want to make sure that every single public thing in your project is documented, especially when you are working on a library. Rust allows you to to generate warnings or errors, when an item is missing documentation.

On my early attempts, it is not clear how to add `///` documentation to functions generated by Nom macros; e.g. `named!`. For example, this does not work:

```rust
/// Parse.
named!(pub parse, delimited!(char!('('), is_not!(")"), char!(')')));
```

[1]: https://doc.rust-lang.org/book/documentation.html#missing-documentation

[2]: https://doc.rust-lang.org/beta/book/attributes.html

**Comment by xpe** [comment]
This looks like a possible solution: http://stackoverflow.com/a/33999625/109618

>  It is possible to capture doc comments in macro invocations. It is not very wide-known, but Rust documentation is actually represented as a special kind of attribute on an item.

> ...

> Note the `$(#[$attr:meta])*` part of the pattern. It captures all attributes placed before the respective item in the pattern. If you write a doc comment there, it will actually be converted to the doc attribute and will be passed to rustdoc, as usual.

**Comment by log0ymxm** [comment]
The `named!` macro does look like it can have a meta attribute:
https://github.com/Geal/nom/blob/e26f92adecf3ce81d599656e28028ea7d890f088/src/macros.rs#L177

**Comment by xpe** [comment]
@log0ymxm yes, I *just* saw that too, I will try it.

**Comment by Geal** [comment]
@xpe: using `///` above does not work, but IIRC it can work in some cases like this:

```rust
named_attr!(/// Parse.
pub parse, delimited!(char!('('), is_not!(")"), char!(')')));
```

because the rust compiler will translate the `///` to an attribute.
