### ISSUE TITLE
Permutation with multiple optional parsers

### ISSUE THREAD

**Issue by log0ymxm** [Geal/nom#416]
It seems that there's an error with permutation when we have multiple optional parsers in the permutation.

Here's an example (note, I have to pull out the opt parsers to avoid the `unable to infer enough type information about _` errors):

```rust
#[macro_use]
extern crate nom;
use nom::{IResult, ErrorKind, Needed};

named!(opt_hi<Option<&[u8]>>,
    opt!(complete!(tag!("hi")))
);

named!(opt_efg<Option<&[u8]>>,
    opt!(complete!(tag!("efg")))
);

named!(opt_perm<(&[u8], Option<&[u8]>, Option<&[u8]>)>,
   permutation!(tag!("abcd"), call!(opt_efg), call!(opt_hi))
);

#[test]
fn test_permutation() {
    let expected = (&b"abcd"[..], Some(&b"efg"[..]), Some(&b"hi"[..]));

    let a = &b"abcdefghijk"[..];
    assert_eq!(opt_perm(a), IResult::Done(&b"jk"[..], expected));
    let b = &b"efgabcdhijk"[..];
    assert_eq!(opt_perm(b), IResult::Done(&b"jk"[..], expected));
    let c = &b"hiefgabcdjk"[..];
    assert_eq!(opt_perm(c), IResult::Done(&b"jk"[..], expected));

}
```

We'd expect `c` to be correctly parsed, but since it's got the two optional pieces of the parser first, it fails with `Error(Permutation)`. This works if we have something like just the "hi" parser as optional.

I'm thinking it's an error here: https://github.com/Geal/nom/blob/master/src/branch.rs#L502. Since there are optional parsers, when we reach this conditional we get `acc!($it, $res)` with the value `Some(None)`, which skips checking the macro later input assuming it's been checked. Thus we error on the input when we hit "efg" having the output tuple at 1 already set to `Some(None)` and we can't finish consuming the input.

**Comment by Geal** [comment]
I got one I can extract from https://github.com/rust-av/matroska

**Comment by Geal** [comment]
it works! f9c11d1
To mark a parser as optional, you need to add a `?` in the call
