### ISSUE TITLE
Consider exposing a "std" feature that adds items, instead of a "core" feature that removes them

### ISSUE THREAD

**Issue by lfairy** [Geal/nom#417]
Cargo features are additive: if one crate enables the "core" feature on nom, then it will be enabled for every other dependent crate as well. For this reason, it would be more flexible if we expose a default-enabled `std` feature instead -- so that a crate can advertise `#![no_std]` support without imposing it on everyone else.

See rust-lang/rfcs#1841.

**Comment by Geal** [comment]
good idea. I'll add this in the next major release

**Comment by Geal** [comment]
Fixed in d8dde827e6437c768e20
