### ISSUE TITLE
Add a parser to recognize floats

### ISSUE THREAD

**Issue by s3bk** [Geal/nom#421]
Suggested functions:
- **float:**
    `float::<f32>("12.34e4") => IResult::Done("", 12.34e4f32)`
- **float_str:**
    `float_str("12.34 end") => IResult::Done(" end", "12.34")`

**Comment by log0ymxm** [comment]
This could definitely be cleaned up but here's my parser for this: https://gist.github.com/log0ymxm/0c82aca73008066f9d723b8bf419d75d

**Comment by Geal** [comment]
there's an example here https://github.com/Geal/nom/blob/master/tests/float.rs
but I'm not sure it would need to be a directly accessible parser?

**Comment by s3bk** [comment]
I have seen quite a number of float parsers (in nom) and almost every one of them is missing a small detail.
```rust
tuple!(
    opt!(alt!(tag!("+") | tag!("-"))
    alt!(
        tuple!(digit, tag!("."), opt!(digit))
      | tuple!(opt!(digit), tag!("."), digit)
    ),
    opt!(tuple!(
        alt!(tag!("e") | tag!("E")),
        opt!(alt!(tag!("+") | tag!("-"))),
        digit
    ))
)
```
So having a correct float parser in nom could avoid some bugs.

**Comment by Geal** [comment]
Added in 3196f1a74a8d63. I had to make different methods for `&[u8]` and `&str`, I'll find a way to merge them later.
