### ISSUE TITLE
New macros

### ISSUE THREAD

**Issue by antoyo** [Geal/nom#422]
As mentioned [here](https://www.reddit.com/r/rust/comments/5oknnw/peg_parser_combinators_using_operator_overloading/#siteTable_t1_dck339t), it seems some people needs a `named!` macro accepting parameters.

So here I propose to add [the version I wrote in one of my project](https://github.com/antoyo/uncbv/blob/master/src/macros.rs#L24).

I copy the code here:

```rust
/// Makes a function from a parser combination with arguments.
macro_rules! named_args {
    (pub $func_name:ident ( $( $arg:ident : $typ:ty ),* ) < $return_type:ty > , $submac:ident!( $($args:tt)* ) ) => {
        pub fn $func_name(input: &[u8], $( $arg : $typ ),*) -> IResult<&[u8], $return_type> {
            $submac!(input, $($args)*)
        }
    };
    (pub $func_name:ident < 'a > ( $( $arg:ident : $typ:ty ),* ) < $return_type:ty > , $submac:ident!( $($args:tt)* ) ) => {
        pub fn $func_name<'a>(input: &'a [u8], $( $arg : $typ ),*) -> IResult<&'a [u8], $return_type> {
            $submac!(input, $($args)*)
        }
    };
    ($func_name:ident ( $( $arg:ident : $typ:ty ),* ) < $return_type:ty > , $submac:ident!( $($args:tt)* ) ) => {
        fn $func_name(input: &[u8], $( $arg : $typ ),*) -> IResult<&[u8], $return_type> {
            $submac!(input, $($args)*)
        }
    };
    ($func_name:ident < 'a > ( $( $arg:ident : $typ:ty ),* ) < $return_type:ty > , $submac:ident!( $($args:tt)* ) ) => {
        fn $func_name<'a>(input: &'a [u8], $( $arg : $typ ),*) -> IResult<&'a [u8], $return_type> {
            $submac!(input, $($args)*)
        }
    };
}
```

[Here](https://github.com/antoyo/uncbv/blob/master/src/cbv.rs#L240) is an example usage.

There are also other macros in this file, like `foreach!` that may be useful to other people.

Thanks to add the macros you think might benefit to `nom` users.

**Comment by Geal** [comment]
could you make a PR to add `named_args!`? I'll release a 2.1 early next week, and I'd want that parser in :)
