### ISSUE TITLE
macros like `char!` with multibyte characters

### ISSUE THREAD

**Issue by derekdreery** [Geal/nom#425]
What would happen if you passed something like 简 to the `char!` macro?

**Comment by Geal** [comment]
in its current implementation, it would not work :(

**Comment by mp4096** [comment]
@Geal Actually, what was your reason to write `none_of!`/`one_of!`/`char!` for `char`s and not for `u8`s?

I needed something like `none_of!` but for bytes and I didn't want to typecast every time when processing the results. So I ended with copy-pasting `nom`'s macros and rewriting them to return `u8`.

Apart from this, thank you very much for the great library! :heart_eyes:

**Comment by Geal** [comment]
it should be fixed with 59ef690

**Comment by mp4096** [comment]
Awesome, thanks! I'm looking forward to the next release.
