### ISSUE TITLE
Why take_till_s/take_till1_s doesn't exists ?

### ISSUE THREAD

**Issue by Kerollmops** [Geal/nom#434]
Hello,

I tried to use `take_till_s` and I realize that it can create empty output, that I don't want.
I search in the doc: `take_while1_s` does what I want but I didn't see any `take_till1_s` macro, is it possible to combine some to simulate one ?

Thanks

**Comment by Geal** [comment]
they are available with f1a65f3, would you like to test?

**Comment by Kerollmops** [comment]
Ho thank you, I can't test it for now, but I will this week probably !

**Comment by Geal** [comment]
up

**Comment by Kerollmops** [comment]
I have not actual project to test it right now, sorry !
