### ISSUE TITLE
take_while1 returns IResult::Error on empty input

### ISSUE THREAD

**Issue by jhutchins** [Geal/nom#438]
I would expect to get a result of type `IResult::Incomplete` in the case were the input is empty, but this macro (and possibly others like it) return an `IResult::Error` instead.

https://github.com/Geal/nom/blob/master/src/bytes.rs#L422

As an example I would expect this to work but it does not
```rust
use nom::IResult::Incomplete;                                                    
use nom::Needed::Size; 

named!(tag, take_while1!(nom::is_alphanumeric));

#[test]
fn test_tag() {
    assert_eq!(tag(&b""[..]), Incomplete(Size(1)));
}
```

**Comment by RReverser** [comment]
Sounds relevant to #397

**Comment by Geal** [comment]
this should be fixed by 3000d54, could you test please?

**Comment by Geal** [comment]
up

**Comment by Geal** [comment]
Hello, this should be fixed by 484f672

**Comment by jhutchins** [comment]
The fix seems to have worked.

**Comment by jhutchins** [comment]
Thanks, and sorry for the really slow response.

**Comment by Geal** [comment]
great, thanks :)
