### ISSUE TITLE
`alt!` fails on the first case on `IResult::Incomplete`

### ISSUE THREAD

**Issue by valarauca** [Geal/nom#442]
Simple error for parsing AMD64 register name

```rust
named!(parse_name, alt!(
    recognize!(do_parse!(peek!(tag!(b"bpl")) >> a: tag!(b"bpl") >> (a))) |
    recognize!(do_parse!(peek!(tag!(b"bp")) >> a: tag!(b"bp") >> (a)))
));
```

For the input `b"bp"` this fails with `IResult::Incomplete(Needed::Size(3))`. this is coming from the `peek!` macro. Wouldn't it make sense to match the next `alt!` branch before reporting failure?

If not what would be the idiomatic way to parse these values... other then writing a re-cursive decent function?

**Comment by Geal** [comment]
If it went to the next branch, for the input `"bpl"` chunked as `"bp"` then `"l"`, it would go through the second branch, then the next parser would get a `"l"` it wouldn't expect, for a valid input.
BTW, why do you do a `recognize!(do_parse!(peek!(tag!(b"bpl")) >> a: tag!(b"bpl") >> (a)))`? That's equivalent to `tag!(b"bpl")`

**Comment by valarauca** [comment]
>if it went to the next branch, for the input "bpl" chunked as "bp" then "l", it would go through the second branch, then the next parser would get a "l" it wouldn't expect, for a valid input.

I don't understand isn't `b"bp l"` a different string? or if `b"bpl"` is processed in chunks isn't that just explaining the core fault of the bug I'm posting? 

>BTW, why do you do a recognize!(do_parse!(peek!(tag!(b"bpl")) >> a: tag!(b"bpl") >> (a)))? That's equivalent to tag!(b"bpl")

I was just throwing crap the compiler and seeing what stuck out of relatively extreme frustration.

**Comment by Geal** [comment]
The `Incomplete` stuff is there to handle cases where you don't get the full data at once. So if the full data was `bpl`, but for various reasons (slow network packets, file reading buffer full), you only get `bp`, but once more data is accumulated, you get the full `bpl`, you want to have to correct result. And the correct result is recognizing `bpl`, not recognizing the second case `bp` then see a trailing `l`.

If you're in the case where you don't care about incomplete data, you can wrap a parser with `complete!()`, and it will transform `IResult::Incomplete` in `IResult::Error`.
