### ISSUE TITLE
float, float_s, double, double_s missing from documentation

### ISSUE THREAD

**Issue by joliss** [Geal/nom#452]
The functions `float`, `float_s`, `double`, `double_s` are [documented in the source](https://github.com/Geal/nom/blob/3000d54cc643289cc1d75e48a0f49a659a8dbe4a/src/nom.rs#L598), but do not seem to show up on the [documentation page](http://rust.unhandledexpression.com/nom/).

**Comment by Geal** [comment]
the documentation was synchronized again, they appear now
