### ISSUE TITLE
Documentation and source listings out of sync

### ISSUE THREAD

**Issue by joliss** [Geal/nom#453]
The "src" link on http://rust.unhandledexpression.com/nom/macro.value.html links to http://rust.unhandledexpression.com/src/nom/src/macros.rs.html#581-599, which seems to be off by a few lines. I'm guessing the documentation and source files have gone out of sync somehow?

**Comment by Geal** [comment]
yes, they were out of sync. I just released nom 2.2 and updated the docs, it should be fixed now

**Comment by joliss** [comment]
Cool, thanks! :)
