### ISSUE TITLE
Add a flat_map method on IResult for manual use

### ISSUE THREAD

**Issue by TyOverby** [Geal/nom#454]
I've never been able to get `flat_map!(...)` or `do_parse!(...)` to compile correctly, so I'd like to be able to use a flat_map method on raw IResults

**Comment by TyOverby** [comment]
Here's my static function helper that I'm using:

```rust
    fn flat_map<I, O, E, S, F>(r: IResult<I, O, E>, f: F) -> IResult<I, S, E>
    where F: FnOnce(I, O) -> IResult<I, S, E> {
        match r {
            IResult::Done(i, o) => f(i, o),
            IResult::Error(e) => IResult::Error(e),
            IResult::Incomplete(e) => IResult::Incomplete(e),
        }
    }

```

**Comment by Geal** [comment]
now `IResult` is replaced with a standard `Result`, so you will be able to use `and_then` and others on it
