### ISSUE TITLE
add take_while_m_n!

### ISSUE THREAD

**Issue by Geal** [Geal/nom#472]
take_while with lower and higher limits on elements

**Comment by target-san** [comment]
I somehow think that having many such "narrow" combinators may be not very convenient. Especially looking at how standard 'alpha', 'digit' etc. parsers are implemented - with lots of code copy-pasting.
Maybe we simply need combinator 'match' or 'take_if' which turns boolean predicate into a parser, with that parser consuming exactly one item if it matches predicate. Then, combinators like 'take_while' are just `many0!(match!(...))`, and parsers like `alpha`, `digit` are simply implemented in terms of `take_while1`.

As a more general idea, `nom` can have 'basic' and 'compound' parsers. Basic set would contain 'atomic' parsers and combinators like 'match', 'many_m_n' with optional upper limit, 'alt', 'sequence' and a few more. And compound parsers will be constructed solely in terms of basic ones.

**Comment by Geal** [comment]
done in 1b4ec7e
