### ISSUE TITLE
#[no_std] and cross compilation

### ISSUE THREAD

**Issue by richo** [Geal/nom#473]
hi!

I'm trying to get nom working on an embedded device.

Enabling the `core` feature works as expected natively, but fails unable to find a crate for `core` when cross targeting.

The toolchain and HAL I'm using for the embedded device use https://github.com/hackndev/rust-libcore to provide core, but evidently it has no collections crate.

I'm reaching out to you first to see if you have any intuitions about what's going on here, but at a glance it looks as though nom is consuming `std::collections` as an extern crate because it's in the search path for the compiler?

I can try to repackage `std::collections` in some way so I can pull it in, or build a full cross compiler stage instead of merely using the llvm backend, or have a look at what's involved in reducing the dependency on `collections` for a subset of nom (Which might be ideal for my embedded usecase, since allocating is expensive)

**Comment by Geal** [comment]
it seems collections moved out of core some time ago https://github.com/rust-lang/rust/commit/21ac985af4
I have not worked with no_std for a long time and didn't notice :(

The correct path would be to isolate parts of nom that use collections behind a `collections` compilation feature. It would remove a lot of useful combinators though

**Comment by richo-stripe** [comment]
That's fine for my usecase (We're building for an embedded platform without a ton of memory or power).

I am happy to help, can I literally just add a collections feature and start making items conditional on it>

**Comment by richo** [comment]
I spent a little time fiddling with this this morning.

There's some fairly intrinsic plumbing that depends on some stuff that no longer belongs to core.

I've successfully pulled liballoc and librustc_unicode out of rustc and built without collections, by creating a new feature for collections. I mostly need some feedback from you on how best to upstream it.

1. What should the feature be called? Dependencies and features can't share a name, so collections is out.
2. Are you comfortable with a dependency on those crates that fetches and builds itself at compiler time, in a similar manner to https://github.com/hackndev/rust-libcore ?
3. Do you have any infra in place to test permutations of features? I get a clean build of nom now with the features that I want, I'll test actually running a parser on hardware today, but Idon't have much confidence that I haven't subtly broken some configurations

**Comment by Geal** [comment]
Hello,

with current master (since commit 9b12a2d ) it should be better, could you test?

**Comment by richo** [comment]
I'll endeavour to have a look, but I haven't been actively working on this for a while. I think it's reasonable to close this as fixed and I'll reopen if it isn't.

Or I'm happy to explain how to repro if I can remember.
