### ISSUE TITLE
Unclear incomplete when parsing optional suffix

### ISSUE THREAD

**Issue by eugene-bulkin** [Geal/nom#496]
In the following code:

```rust
#[macro_use]
extern crate nom;

use nom::digit;
use nom::IResult::*;

named!(digits_suffix (&[u8]) -> &[u8],
    recognize!(do_parse!(
        digit >>
        opt!(alt_complete!(tag!("AB") | tag!("A") | tag!("C"))) >>
        ()
    ))
);

fn main() {
    assert_eq!(Done(&[][..], &b"2A"[..]), digits_suffix(b"2A"));
    assert_eq!(Done(&[][..], &b"2AB"[..]), digits_suffix(b"2AB"));
    assert_eq!(Done(&[][..], &b"2"[..]), digits_suffix(b"2"));
}
```

the last assert fails because of an `Incomplete`. This is because, as @Geal explains [here](https://github.com/Geal/nom/pull/145#issuecomment-165408356), the parser can't tell if there's more data necessary.

By surrounding the `alt_complete!()` with a `complete!()` call, everything works fine.

The issue here is mostly just that it's not super clear *how* to fix the parser initially. For example, using `dbg_dmp!()` around the `opt!()` call initially just gives this:

```
Incomplete(Size(1)) at 7 by ' opt ! ( alt_complete ! ( tag ! ( "AB" ) | tag ! ( "A" ) | tag ! ( "C" ) ) ) '
```

which doesn't help a whole lot.

**Comment by target-san** [comment]
nom: 3.2.0
Refined example:
```rust
    println!("{:?}", 
        do_parse!("123".as_bytes(),
            name: call!(nom::digit) >> opt!(tag!("!")) >> (name)
        )
    );
```
results in
```
incomplete(Size(4)
```

**Comment by target-san** [comment]
nom: 3.2.0
Refined example:
```rust
    println!("{:?}", 
        do_parse!("123".as_bytes(),
            name: call!(nom::digit) >> opt!(tag!("!")) >> (name)
        )
    );
```
results in
```
incomplete(Size(4)
```

**Comment by Geal** [comment]
Hello,

nom 4.0 will fix those kind of issues by introducing the `CompleteStr` and `CompleteByteSlice` input types, which will tell parsers there is no more input coming afterwards
