### ISSUE TITLE
separated_nonempty_list type error when separator enclosed in opt!

### ISSUE THREAD

**Issue by jsdw** [Geal/nom#498]
I am relatively new to nom (and Rust) and am trying to parse a list of things separated optionally by spaces (tho not necessary).

This works fine (but requires spaces):

```
separated_nonempty_list!( space, my_parser )
```

This leads to a type error (cannot infer type for E):

```
separated_nonempty_list!( opt!(space), my_parser )
```

My workaround thus far is to do:

```
many1!( do_parse!( val: my_parser >> opt!(space) >> (val) ) )
```

This handles spaces, but also eats up spaces after the thing (which is OK for me but not equivalent). However, I feel I am probably missing something pretty basic which would enable the separated_nonempty_list approach to work?

A reproducible example that fails in the same way as above:

```
named!(
    test< Vec<&[u8]> >,
    separated_nonempty_list!( opt!(tag!(" ")), tag!("hello") )
);
```

Again, removing `opt!` from this example allows it to compile.

If it helps, I'm using nom 2.2.1!

**Comment by juanibiapina** [comment]
I get the same error but with a different case:

```rust
fn make_my_type(parts: Vec<&str>) -> MyType {...}

map!(separated_nonempty_list!(space, map_res!(not!(space), str::from_utf8)), make_my_type)
```

**Comment by juanibiapina** [comment]
Got it even another time with a usage of `map!`.

**Comment by juanibiapina** [comment]
I have a temporary solution for this: Make `named` parsers with intermediate results so that the compiler can infer the types correctly.

Got it from here: https://github.com/Geal/nom/pull/484#issuecomment-297983806

**Comment by Geal** [comment]
about the type inference error, I'm working on it, this will go in the next nom release

**Comment by Geal** [comment]
the type inference error should be fixed in #484, please test again with nom master

**Comment by Geal** [comment]
nevermind, I just tested, it is not fixed yet

**Comment by Geal** [comment]
with 0b19553582c0b0118d11 it should be fixed now, please test with master

**Comment by Geal** [comment]
great!

**Comment by Geal** [comment]
nom 3.0 is released
