### ISSUE TITLE
CI is lacking coverage of previous rustc versions and feature flag combinations

### ISSUE THREAD

**Issue by danburkert** [Geal/nom#500]
Nom 2.2.x requires rustc 1.9.0 due to a [deprecated annotation](https://github.com/Geal/nom/commit/b5e21c00e8a52b7dfec485245ba2dceafe5ecaa5).  Nom 2.0.0 passes the test suite with rustc 1.8.0.  The travis configuration appears to be targeting rustc 1.2 and passes, so there is almost certainly something wrong with the CI setup.

**Comment by danburkert** [comment]
It was actually f996485979aa which introduced the deprecated annotation.

**Comment by Geal** [comment]
so, now, since `chain!` has completely disappeared, the annotation was removed too, so I guess I can close this issue :)

**Comment by danburkert** [comment]
I wouldn't personally consider this fixed since it's still a regression on the 2.x line.  If you don't want to push fixes to previous major version branches I can understand that though.

@geal there's still an underlying issue that 'nom' is not properly ci testing with previous 'rustc' versions, so this is likely to happen again.

**Comment by danburkert** [comment]
Also noticed from a quick look at .travis.yml that the three [ENV declarations|https://github.com/Geal/nom/blob/master/.travis.yml#L19-L21] seem to be overwriting each other.  I think they need to be defined in a 'matrix'.
