### ISSUE TITLE
`escaped_transform!` suppresses errors within enclosing function

### ISSUE THREAD

**Issue by yodaldevoid** [Geal/nom#504]
I have included a [gist](https://gist.github.com/yodaldevoid/f72b4727933bda2e348295cdab607b08) as I think it helps to see working vs. failing code.

It seems that if `escaped_transform!` is within a function and errors, that error is treated as success until the enclosing function is returned from. This effects `alt!` as shown in the example, but it has also caused `dbg!` to not print the error. Simply moving `escaped_transform!` off to a wrapper function and `call!`ing that solves this issue.

**Comment by Geal** [comment]
I'm sorry, I don't really understand the issue here. Could you make a smaller test case? What do you expect `escaped_transform!` to return in which case?

**Comment by yodaldevoid** [comment]
I believe I have made almost as small a test case as is possible, but I will attempt to shrink it. At the same time, let me try to explain better what is going on in both parsers.

In both cases I am trying to parse an empty quoted string and I expect back an empty string at the end. In both cases I expect the `escaped_transform!` section to return an error, thus trying the second branch of the `alt!` starting with `map!(verify!(`.

Now, in the failing case the second branch is not run, and if you put a `dbg!` like so
```
named!(pub escape_c_string<String>, dbg!(map_res!(
```
you will see no error, but if you put a `dbg!` at the same time here
```
delimited!(
        char!('"'),
        dbg!(escape_c_string),
        char!('"')
)
```
a EscapedTransform error will be found.

In the passing case the only change made has been to move the `escaped_transform!` statements out to a separate function. Now, `dbg!` statements still show no error from the `escaped_transform!` if placed within this new separate function, but if placed around the function's call site like so
```
dbg!call!(transform)) |
```
the same error that was eventually found in the failing case will be printed, the second branch of the `alt!` statement will be run, and the test will pass.

**Comment by Geal** [comment]
Hello,

This should be fixed by c413ce2

**Comment by yodaldevoid** [comment]
`escaped_transform` is currently broken due to a missing `use $crate::Needed;` in the main body of `escaped_transform`.

When the `use` statement is added (And when all the `IResult`s are updated to just being `Result`, that is. The errors `rustc` spat at me due to that change nearly gave me a heart attack.) the test I have to track this issue passes.

In short, as soon as that `use` statement is added this will be fixed!

**Comment by yodaldevoid** [comment]
I should also note that I tested with commit f40a40ad2 as I saw that the master branch is currently not building on CI.
