### ISSUE TITLE
Regression: separated_list! no longer works after commit 1a0267e

### ISSUE THREAD

**Issue by doomrobo** [Geal/nom#505]
Here is a small testcase
```rust
#[macro_use]
extern crate nom;

named!(foo<Vec<&[u8]>>, separated_list!(tag!(","), nom::alpha));

fn main() {
    println!("result: {:?}", foo(&b"abdef"[..]));
}
```
Before commit 1a0267e this gave `Done([], [[97, 98, 100, 101, 102]])`. After the commit, it gives `Incomplete(Size(6))`.

I've added the following lines to `src/multi.rs::tests::separated_list()` to demonstrate the regression.
```rust
named!(multi_alpha<&[u8],Vec<&[u8]> >, separated_list!(tag!(","), alpha));
// ...
let res5 = vec![&b"abcdef"[..]];
let res6 = vec![&b"abcd"[..], &b"abcdef"[..]];
assert_eq!(multi_alpha(a), Done(&b""[..], res5));
assert_eq!(multi_alpha(b), Done(&b""[..], res6));
```

**Comment by Geal** [comment]
this is actually not a regression, but the proper behaviour. If you get your input chunked as `abcdef`, then the next chunk is `,ghijk`, you would get an error for a correct input.
There are two ways around this: either you wrap `alpha` with `complete!()` to indicate you consider `Incomplete` as an error, or your format has a terminating token after the list, and this token should be part of the input.

**Comment by doomrobo** [comment]
I see, that makes sense. I tried doing `named!(foo<Vec<&[u8]>>, separated_list!(tag!(","), complete!(nom::alpha)))` but I'm still getting `Incomplete(Size(6))`. I looked at the source, and it seems that it should only return `Incomplete` when the item parser returns `Incomplete`. But that only happens on the first parse, and I've checked using another parser that the first parse succeeds. So I'm not sure where this is coming from.

**Comment by eugene-bulkin** [comment]
Is there any other workaround if we don't want a terminating token?

**Comment by doomrobo** [comment]
My current workaround is just copying the old macro into my library and
using that instead, bugs and all.

**Comment by pashinin** [comment]
@Geal your suggestion (`complete!()`) doesn't work for me either. Always `Incomplete`

**Comment by Keruspe** [comment]
```
extern crate nom;

#[cfg(test)]
mod tests {
    use nom::*;

    named!(foo<Vec<&[u8]>>, separated_list!(tag!(","), alpha));
    named!(bar<Vec<&[u8]>>, separated_list!(tag!(","), complete!(alpha)));
    named!(baz<Vec<&[u8]>>, separated_list!(complete!(tag!(",")), complete!(alpha)));

    #[test]
    fn works_2_fails_3() {
        assert_eq!(foo(&b"abc"[..]), IResult::Done(&b""[..], vec![&b"abc"[..]]));
    }

    #[test]
    fn works_2_fails_3_too() {
        assert_eq!(bar(&b"abc"[..]), IResult::Done(&b""[..], vec![&b"abc"[..]]));
    }

    #[test]
    fn works_2_and_3() {
        assert_eq!(baz(&b"abc"[..]), IResult::Done(&b""[..], vec![&b"abc"[..]]));
    }
}
```

With nom 2
```
test tests::works_2_fails_3 ... ok
test tests::works_2_and_3 ... ok
test tests::works_2_fails_3_too ... ok
```

With nom 3
```
test tests::works_2_and_3 ... ok
test tests::works_2_fails_3 ... FAILED
test tests::works_2_fails_3_too ... FAILED
```

**Comment by Geal** [comment]
I get the same result with this test I just added to nom: https://github.com/Geal/nom/commit/a946f9af4f0a2facb2b35a374d562622ecb7c774#diff-14efff2f3aefda9c3e6c71ed4a391280R1195

`complete!` must be added to both child parsers of `separated_list!`

**Comment by eugene-bulkin** [comment]
@Geal Hm, so if `complete!` needs to be added to both, perhaps we could have a `separated_list_complete!` and `separated_nonempty_list_complete!` that wraps both in `complete!` automatically, like `alt_complete!`?

**Comment by Geal** [comment]
yes, that's possible

**Comment by doomrobo** [comment]
The above commit should resolve the issue.
