### ISSUE TITLE
Document ConsumerState variant values

### ISSUE THREAD

**Issue by daboross** [Geal/nom#51]
Although there are comments describing the variants of `ConsumerState::Await` and `ConsumerState::Seek` in https://github.com/Geal/nom/blob/master/src/consumer.rs#L76, there are no documentation comments on these variants, and thus no indication at all as to what these variants do in the documentation.

Fixing this would be as simple as adding `/// (amount_consumed, buffer_needed)` before Await and `/// (consumed, new_position, buffer_needed)` before Seek. That wouldn't be very much documentation, but it would be hugely useful for those trying to figure out `ConsumerState` from just looking at documentation.

**Comment by Geal** [comment]
I added those suggestions in 9e17cd4. Could you tell me which parts of the consumers you found confusing? It will help me fix the docs

**Comment by daboross** [comment]
I just missed the part in the README documenting what the parameters were doing, and couldn't find it in the docs. I think adding that definitely helps, thank you! 

I think I can understand the Consumer system pretty effectively, it was just that I couldn't find what those parameters did without looking at the source.
