### ISSUE TITLE
verify!() on non-copy data?

### ISSUE THREAD

**Issue by kaj** [Geal/nom#510]
I have a parser returning a `String` that I want to wrap in `verify!` and do some stuff on the result with a `map!`.  Is that possible?

My non-working code:

```
named!(my_parser<MyType>,
       map!(verify!(parser_that_returns_string,
                    |s: String| !s.is_empty()),
       |s| MyType::CaseType(s))
```

As is, the compiler complains about "value used after move", which seems right.  But if I change to `|s: &String|` (or `|s: &str|`) the compiler complains that it expected type &String (or &str) but got String.

Is there an alternative version of `verify!` that borrows the value instead of expecting it to be a copy type?  Or could there be?

**Comment by Geal** [comment]
oh, a verify that would borrow would be good. I'll look into it, maybe there's a way to add one while keeping it backward compatible

**Comment by kaj** [comment]
Yes, `verify_ref` sounds good.

**Comment by Geal** [comment]
it is done in 717e7f0595de for the upcoming nom 5

**Comment by Geal** [comment]
(the `verify` combinator will take a reference in all cases)
