### ISSUE TITLE
Question: how to track line number and position in line while parsing?

### ISSUE THREAD

**Issue by pashinin** [Geal/nom#517]
Can you point me to an example or write one.
While parsing some data I need to know where I am now in a file (line number, position in line).
For example if I'm in the beginning of a new line I want to apply a `parser 1` and if I'm not in the line beginning - a `parser 2`.

**Comment by Geal** [comment]
paging @Hywan for this, he has very good examples of how to achieve this :)

The idea is to make your own input type, that must implement those traits: https://github.com/Geal/nom/blob/master/src/traits.rs
your input type would contain the line number and position.

**Comment by Hywan** [comment]
Hello @pashinin,

I am writing a blog post about this feature in nom. Until its' published, you can look this PR, https://github.com/tagua-vm/parser/pull/101, or this code directly, https://github.com/tagua-vm/parser/blob/e7aa96322c4abe0a758286a5033dcec90cf28a21/source/tokens.rs#L759-L1189.

@fflorent is working on a generic version of this!

**Comment by fflorent** [comment]
Hello there,

Yup! Here is my version of the same feature:
https://github.com/fflorent/espadon/blob/input_slice/src/input_slice.rs

I am currently focusing on making it work for my case to identify cases where it wouldn't work… But thinking of it, that's not the philosophy of open-source (Release early, release often). I'll make a separate crate soon and will notice you for that, even if that's far from being perfect.

Cheers!
Florent

**Comment by fflorent** [comment]
Hello everyone! 

I've just published an unstable version of nom_locate for this purpose. By « unstable », I mean that I need some feedback and that upcoming breaking changes may be brought soon.

Here is the repository:
https://github.com/fflorent/nom_locate/

Feedback welcome (@Hywan already gave me some, thanks to him!). 
For example on the vocabulary (I am not very familiar with the parsing one).

Thanks!
Florent

**Comment by Geal** [comment]
this is awesome :)

**Comment by fflorent** [comment]
Thanks @geal :). I'll probably make a 0.1.0 release with the hope that it'll receive feedback from some users.

Cheers!
Florent

**Comment by fflorent** [comment]
I've published [version 0.1.0](https://crates.io/crates/nom_locate), as it seems to me to be functional. The only remarkable change is the update to nom 3.1.0.

@pashinin What do you think of this crate? Does it respond to your needs?

Florent

**Comment by pashinin** [comment]
@fflorent Thank you. I'm in a russian forest now) Will test it later =) We may close this issue for now
