### ISSUE TITLE
Unknown problem with tag!

### ISSUE THREAD

**Issue by ParkMyCar** [Geal/nom#524]
Hey everyone,

I'm pretty new to Rust and I wanted to start working with the nom library. I can get this basic example to work: **Output [97, 98, 99, 100]**

`#[macro_use]`
```
extern crate nom;

use std::str;
use nom::IResult::{Done, Error, Incomplete};
use nom::AsBytes;

fn main() {
    named!(x, tag!("abcd"));
    let msg = "abcdefghi";
    let r = x(msg.as_bytes());
    match r {
        Done(I, O) => println!("Output {:?}", O),
        Error(err) => println!("Error {:?}", err),
        Incomplete(n) => println!("Incomplete {:?}", n),
        _ => println!("something went wrong"),
    }
}
```

But once I change the sequence tag looks for, and the msg I get an error: **Error Tag**

```
#[macro_use]
extern crate nom;

use std::str;
use nom::IResult::{Done, Error, Incomplete};
use nom::AsBytes;

fn main() {
    named!(x, tag!("type"));
    let msg = "abcdetypefghi";
    let r = x(msg.as_bytes());
    match r {
        Done(I, O) => println!("Output {:?}", O),
        Error(err) => println!("Error {:?}", err),
        Incomplete(n) => println!("Incomplete {:?}", n),
        _ => println!("something went wrong"),
    }
}
```

This really has me confused, and after looking through the documentation I can't get anything out of the error "Tag", other than I assume the error has to do with the tag! macro. If someone could provide any guidance that would be great

**Comment by Geal** [comment]
hello,

tag is trying to find the token (here, "type") at the beginning of the input you pass it. It does not scan the whole input to find it.
Which format are you trying to parse? There might be a more appropriate way for what you want to do.

**Comment by ParkMyCar** [comment]
Thank you for the help!

I am trying to parse a file type similar to Google's protobuf format. Basically I want to scan a txt document for types and then use the name that comes after the type keyword, and the fields inside the curly braces to build a rust equivalent of the object. Here's an example:

```
type foo {
        int32 bar;
}
```

And from there determine there is a type foo named bar, that has an int32 as a field.
