### ISSUE TITLE
exact! combinator?

### ISSUE THREAD

**Issue by sunshowers** [Geal/nom#526]
Is there a combinator that fails if the input isn't completely consumed? If not, would it make sense to add one? (I like `exact!` as a name for it, but I'm not tied to the name.)

While `nom!` is great for parsing incomplete input (thanks for all your hard work!), in some cases the programmer already knows upfront that the entire input is (a) available and (b) must be consumed completely.

In some sense `exact!` is a sort of dual of `complete!` -- `complete!` returns an error on `Incomplete`, while `exact!` would return an error on `Done(remaining, _)` where `remaining` is non-empty.

**Comment by kamarkiewicz** [comment]
You can just wrap your parser with `complete!` and terminate it with [`eof!`](http://rust.unhandledexpression.com/nom/macro.eof.html). It works out the same as you wish.

**Comment by Geal** [comment]
now there's a concept of EOF in the input type of nom. You can always wrap your root parser like this: `terminated!(parser, eof!())`. This will return an error if there's input remaining (and will show which part of the input was still there. Maybe the `exact` combinator would be a good idea now

**Comment by Geal** [comment]
so there's an `exact!` combinator now, that came with 246c7e1
