### ISSUE TITLE
do_parse error

### ISSUE THREAD

**Issue by gsquire** [Geal/nom#527]
I'm trying to write a simple parser for the [RESP](https://redis.io/topics/protocol) and am writing a function for the bulk string section.

My function looks like this:
```rust
named!(bulk_str,
    do_parse!(
        tag!("$") >>
        len: nom::be_u64 >>
        nom::line_ending >>
        res: take!(len) >>
        (res)
    )
);
```

When I compile it, I see this error which seems odd:
```sh
error: no rules expected the token `i_`
  --> src/lib.rs:14:1
   |
14 | / named!(bulk_str,
15 | |     do_parse!(
16 | |         tag!("$") >>
17 | |         len: nom::be_u64 >>
...  |
21 | |     )
22 | | );
   | |__^
```

To double check, I compiled the example  `do_parse!` macro and had the same issue. Am I missing something obvious?

My Rust version is:
```sh
rustc 1.18.0 (03fc9d622 2017-06-06)
binary: rustc
commit-hash: 03fc9d622e0ea26a3d37f5ab030737fcca6928b9
commit-date: 2017-06-06
host: x86_64-apple-darwin
release: 1.18.0
LLVM version: 3.9
```

And my nom version is 3.1.0.

**Comment by Geal** [comment]
I think the error appears because the macros does not recognize a module path. Try to add a `use nom::{be_u64, line_ending}` and pass the `be_u64` and `line_ending` without the path prefix

**Comment by gsquire** [comment]
Awesome, that was it. Good catch and thanks for the help!

**Comment by snowcrshd** [comment]
I'm having a similar problem, not sure what is wrong here.

The code I have is:

```rust
use nom::digit;

use std::str;
use std::str::FromStr;

use lisp_val::LispVal;

named!(parse_number,
       do_parse!(
           n: map_res!(digit, str::from_ut8) >>
           LispVal::Number(FromStr(n))
       )
);
```

`LispVal` is basically:

```rust
pub enum LispVal {
    Number(i64)
}
```

when I try to compile, I get:

```
error: no rules expected the token `i_`
  --> src/parser.rs:8:1
   |
8  |   named!(parse_number,
   |  _^ starting here...
9  | |        do_parse!(
10 | |            n: map_res!(digit, str::from_ut8) >>
11 | |            LispVal::Number(FromStr(n))
12 | |        )
13 | | );
   | |__^ ...ending here
   |
   = note: this error originates in a macro outside of the current crate
```

**Comment by Geal** [comment]
@snowcrshd you're missing parens around `LispVal::Number(FromStr(n))`

**Comment by snowcrshd** [comment]
@Geal oh,  I didn't notice that. Thank you! :)

**Comment by Hwatwasthat** [comment]
I'm having this issue. I don't see any missing parentheses, and I have all the types and macros pulled in.

    use nom::{ named, do_parse, tag };

    named!(register<&str, Token>,
    do_parse!(
        tag!("$") >>
        reg_num: &str >> 
        (
            Token::Register {
                num: reg_num.parse::<u8>().unwrap()
            }
        )
    ));

**Comment by Geal** [comment]
@Hwatwasthat try replacing `reg_num: &str` with `parse_to!(u8)`. Then you won't need to call `.parse()` and unwrap it

**Comment by Hwatwasthat** [comment]
@Geal I have done this, which helps remove the parse requirement, but I still have the error showing. Any ideas how I can solve that?
