### ISSUE TITLE
broken factor parsing combinator in tests/arithmetic_ast.rs

### ISSUE THREAD

**Issue by jaupe** [Geal/nom#528]
The implementation of the `factor` parser is broken for integers without any spaces because the `opt!` is not wrapped in a `complete!` macro. The rationale for using `complete!` is documented [here](https://github.com/Geal/nom/issues/406#issuecomment-274256680)

**Comment by Geal** [comment]
Hello,
this has been fixed in 47deaa1 by using the `CompleteStr` type, which fixes most issues around incomplete parsing. That type assumes we havce all the input and there will be no refill
