### ISSUE TITLE
Convert from bits to bytes

### ISSUE THREAD

**Issue by demurgos** [Geal/nom#536]
Hi,
This a feature request to add the `bytes` macro to act as the reverse of the `bits` macro.

I am currently writing a parser for the SWF file format. This is a complex format that mixes byte-aligned and bit-oriented data structures.
One of the problems that I encountered recently is that I have byte-aligned data inside of a bit-oriented structure.

The `bits` macro allows to "locally" switch the parser to use bits:
>  transforms its byte slice input into a bit stream for the underlying parsers

What I'd need is the reverse, to "locally" switch the parser from bits to bytes. I propose the name `bytes` to mirror the name of the `bits` macro.

Regarding alignment, I think that it should keep the same behavior as currently when returning from the bits stream to the byte slice: any partially consumed byte should be discarded. (If the bit pos is 0, keep the current byte slice, otherwise use `&input[1..]`.
Once the parsers inside the `byte` macro are done, the remaining input is a bit stream with its bit pos set to 0.

**Comment by Geal** [comment]
hi, it was done in #532

**Comment by demurgos** [comment]
Great!
It also uses the same name and rule for partial bytes that I had in mind so I'm happy that it was the "expected" behavior.
