### ISSUE TITLE
can't compile without 'std' feature on stable rustc

### ISSUE THREAD

**Issue by isonmad** [Geal/nom#539]
Since d8dde827e6437c768e2028eab5a7f4eb09b456bd (#417), running `cargo build --no-default-features` gives the error:

> error[E0554]: #[feature] may not be used on the stable release channel

    386 | #![cfg_attr(not(feature = "std"), feature(no_std))]
        |                                   ^^^^^^^^^^^^^^^

    387 | #![cfg_attr(not(feature = "std"), feature(collections))]
        |                                   ^^^^^^^^^^^^^^^^^^^^

Is that expected?

**Comment by Geal** [comment]
yes. How is that a bug?
