### ISSUE TITLE
tag! and byte arrays

### ISSUE THREAD

**Issue by niclashoyer** [Geal/nom#54]
What is the correct way to use tag! with a fixed byte array? `tag!([42u8, 42u8])` fails, as AsBytes is not implemented for `[u8; 2]`.

**Comment by Geal** [comment]
Well, you can do `tag!(&[42u8, 42u8][..])` but it looks very ugly :unamused: 

Could you wait a bit? I'm writing the AsBytes implementation for fixed length arrays.

**Comment by niclashoyer** [comment]
Of course :smile:
Is it true, that there is no simpler way than implementing the same function for every fixed size `[T; 0]`, `[T; 1]`, ...? At least it is done this way in [`std::array`](https://doc.rust-lang.org/std/primitive.array.html). Seems very tedious.

**Comment by Geal** [comment]
There are lots of cases like this in language development, any time something has a fixed number of components, like tuples or function arguments.

Oddly, it is easier to handle an array of unknown length.

**Comment by Geal** [comment]
I just published nom 0.3.7, this should work now. Let me know if you need anything else!

**Comment by niclashoyer** [comment]
works like a charm, thanks!
