### ISSUE TITLE
Question: Should `alt!` include a single parser variant

### ISSUE THREAD

**Issue by derekdreery** [Geal/nom#543]
Looking at the definition for `alt!`, it should be easy to add a macro variant for the special case

```rust
named!(test, alt!(tag!("abcd")))
```

which reduces to
```rust
named!(test, tag!("abcd"))
```

This would be useful during development when you start an `alt` chain, but only have the first parser written, and you want to test every time you add a new parser.

Do you think this would be a good addition to the library?

**Comment by kamarkiewicz** [comment]
It is worth noting that this kind of reduction changes `ErrorKind` result of `IResult::Error`.
[playground](https://play.rust-lang.org/?gist=e1f55b35ef8954b84dc17f3672e61a42&version=stable)

IMO explicit notation is better than implicit not obvious behavior as you can always add/remove a wrapping macro.

**Comment by Geal** [comment]
as @kamarkiewicz  using `alt` with a single macro changes the error type. And that combinator is really meant to test multiple alternatives, so it's not a useful addition
