### ISSUE TITLE
cargo features (verbose-errors may be other?) should be additive

### ISSUE THREAD

**Issue by Dushistov** [Geal/nom#544]
As desribed rust-lang/cargo#4323, see @kennytm comment [here](https://github.com/rust-lang/cargo/issues/4323#issuecomment-317796132):

>The problem here is that, when using "simple errors", the type `nom::simple_errors::Err<E>` is simply a type alias of `nom::ErrorKind<E>`, while with "verbose errors" the type `nom::verbose_errors::Err<E>` is a dedicated enum, so the "with-feature" and "without-feature" interfaces are incompatible.

**Comment by kennytm** [comment]
#457 😢

**Comment by Geal** [comment]
yes, that situation is annoying, but I really don't see how to make that particular feature additive. Others (std, stream, regex*) are fine, but I don't know for this one.

**Comment by kennytm** [comment]
@Geal You could turn `simple_errors::Err` into an enum containing only the `Code` variant (preferably a non-exhaustive enum). It is fine as long as the API of simple_errors is a strict subset of verbose_errors.

Yes the fix is going to be a breaking change 😞

**Comment by Geal** [comment]
so this is now done as you said, with an enum. It's much cleaner to use :)

**Comment by dathinab** [comment]
seems I have to switch to nom4, this just broke my crate 🤕 well at last I did learn something new

**Comment by leoschwarz** [comment]
This ended up biting me now too.

The docs here https://github.com/Geal/nom/blob/master/doc/upgrading_to_nom_4.md, at least `pub type Err<E=u32> = ErrorKind<E>;` should be updated to reflect the change made but I'm not sure if there is more that still needs updating.

**Comment by dtolnay** [comment]
I don't think this has been fixed. I still see this in master:

https://github.com/Geal/nom/blob/a88a6f8d3fe3cf41ef682bbfec1fd72f08edcf95/src/lib.rs#L434-L436

That means the following code would break if verbose-errors is enabled anywhere else in our dependency graph.

```rust
extern crate nom;

use nom::simple_errors;
```

Some cases of this causing breakage:

- [*A dependency compiles on it's own, but does not compile as dependency (lettre & nom)*](https://users.rust-lang.org/t/a-dependency-compiles-on-its-own-but-does-not-compile-as-dependency-lettre-nom/18097)
- [*Macro failure only when depending on a project having bindgen as a build dependency.*](https://github.com/rust-lang-nursery/rust-bindgen/issues/1287)
- [*Build 0.8.2 fails to compile against nom 3.2.1*](https://github.com/lettre/lettre/issues/298)

**Comment by dathinab** [comment]
Hm, everything from `*_errors` is re-exported so the modules could be
private.

Alternatively re-exporting them through
a common module name (`errors`) is
also an option.
