### ISSUE TITLE
Is `recognize!(fold_many0!(..., (), |_, _| {}))` an antipattern

### ISSUE THREAD

**Issue by derekdreery** [Geal/nom#545]
I find myself doing `recognize!(fold_many0!(..., (), |_, _| {}))` as a way to match some bytes passing some parser. Is there a better way to get the same result (I want to avoid allocating a vec for efficiency)?

**Comment by Geal** [comment]
there could be a combinator to do `many0!` but not accumulate anything. Could you send a PR?

**Comment by azerupi** [comment]
In a similar vein, I have used:
- `recognize!(fold_many1!(..., (), |_,_| {}))`
- `recognize!(fold_many_m_n!(min, max, ..., (), |_,_| {}))`
- `recognize!(do_parse!(... >> ()))`

We could add `many1!` and `many_m_n!` respectively for the first two. 

For the `do_parse` I wonder if we could expose a special variable to the user that represents the whole slice that was matched? 

I imagine something like:

```rust
do_parse!(tag!("y") >> opt!(tag!("es") >> (matched))
```

But I have no idea if macros let you do that + maybe this could introduce some name conflicts if someone already has something with the same name in scope?

**Comment by derekdreery** [comment]
@azerupi I'm going to do the `1` and `m_n` versions in that referenced PR once my general method has been checked.

**Comment by Geal** [comment]
closing this, it's possible to do `recognize!(many0_count(parser))` instead
