### ISSUE TITLE
anychar panics when parsing characters wider than one byte

### ISSUE THREAD

**Issue by Epsylon42** [Geal/nom#552]
I was working on my project and needed a parser for any unicode character. anychar seemed like exactly this, and for plain old ascii it is, but it panics in other cases (e.g. cyrillics).

Here's what I'm using instead, but I don't know how to make it generic enough:

```rust
fn anychar(input: &str) -> nom::IResult<&str, char> {
    if input.len() == 0 {
        nom::IResult::Incomplete(nom::Needed::Size(1))
    } else {
        let c = input.chars().next().unwrap();
        if input.chars().count() == 1 {
            nom::IResult::Done("", c)
        } else {
            nom::IResult::Done(input.split_at(input.char_indices().nth(1).unwrap().0).1, c)
        }
    }
}
```

If the current anychar is not supposed to parse complex characters, maybe we need another function for this purpose. And in any case, panicking doesn't seem like expected behaviour.

**Comment by Geal** [comment]
Hello,
thanks for the report, this is fixed in ce028b5
