### ISSUE TITLE
Consume padding

### ISSUE THREAD

**Issue by boomshroom** [Geal/nom#564]
I'm currently trying to make a .xz parser to relieve Redox of its dependency on liblzma. One part of the format is padding parts of the file to an alignment of 4 bytes. I could try parsing the entire thing as a u32 slice rather than a u8 slice, but there are still parts that are byte aligned or bit aligned.

What I'm thinking of would be a way to parse some data and then return it and the number of bytes consumed. Then I would be able to take the required number of bytes to bring it to a 4 byte alignment.

What's the best way to do this?

**Comment by Geal** [comment]
if you import `nom::Offset`, you can get the number of bytes consumed with `original_input.offset(remaining_input)`, with `remaining_input` the first element in `IResult::Done(remaining_input, value)`
