### ISSUE TITLE
alt_complete returns Incomplete

### ISSUE THREAD

**Issue by WaDelma** [Geal/nom#569]
First of all if last option in `alt_complete` returns `Incomplete` it also returns it. This makes sense even though at first glance documentation doesn't imply it.

What doesn't make sense is [this](https://play.rust-lang.org/?gist=c02791e305e9fcba4aee4d391a51e9ad&version=stable) code. Here it returns incomplete even though there another choice and it doesn't seem to fail on it based on `dbg`.

**Comment by kamarkiewicz** [comment]
I've checked unit tests for `alt_complete!` [here](https://github.com/Geal/nom/blob/master/src/branch.rs#L816) and noticed it is the tested use case.

However, in a contradiction to [the documentation](http://rust.unhandledexpression.com/nom/macro.alt_complete.html):
> If one of the parsers return Incomplete, alt_complete! will try the next alternative. If there is no other parser left to try, an Error will be returned.

In other words, I expect that `alt_complete!` should be acting the same as `alt!( complete!(...) | complete!(...) )`, but apparently it does not...

Is this an issue with current documentation or the parser?

**Comment by WaDelma** [comment]
I found what was the problem the code I linked: `try_parse` does early return which `complete` cannot catch. It seems like one should avoid `try_parse` as plague as it doesn't compose nicely.

The code in the `ident` macro was taken from [monkey-rust](https://github.com/Rydgel/monkey-rust/blob/master/lib/parser/mod.rs#L26) which is listed as example of nom used as lexer and parser.

**Comment by WaDelma** [comment]
I worked around the problem by wrapping contents of the macro into 
````rust
(|| {
    code;
})()
````

**Comment by Geal** [comment]
Fixed in #547
