### ISSUE TITLE
Why uses `IResult` instead `std::result::Result<Status<I, O>, Error>`?

### ISSUE THREAD

**Issue by kgv** [Geal/nom#57]
Why uses:

```rust
pub enum IResult<I,O> {
  Done(I,O),
  Error(Err),
  Incomplete(u32)
}
```

why not (for example):

```rust
pub enum Status<I, O> {
    Done(I, O),
    Incomplete(u32)
}

type Result<I, O> = std::result::Result<Status<I, O>, Error>
```

because of this there is no possibility to use `map_err` or `try!`...
What causes?

**Comment by Geal** [comment]
I made it that way to match Parsec's `IResult` type, although passing a closure into `Incomplete` proved too difficult for Rust.
I am not sure using `Result` would be better, since depending on the context, `Incomplete` can be an error case or a correct case.
If you need more helper functions, though, I could add them, that's not a problem.

**Comment by kgv** [comment]
understood.

**As for "more helper functions":**
In examples i found only one case that needs it ([this](https://github.com/Geal/nom/blob/master/tests/ini.rs#L49-L58)).
 
```rust
  match keys_and_values_aggregator(input) {
    IResult::Done(i,tuple_vec) => {
      for &(k,v) in tuple_vec.iter() {
        h.insert(k, v);
      }
      IResult::Done(i, h)
    },
    IResult::Incomplete(a)     => IResult::Incomplete(a),
    IResult::Error(a)          => IResult::Error(a)
  }
```
But in this code we can remove the explicit mapping (like this: `IResult::Incomplete(a)     => IResult::Incomplete(a),`) using `map!` macro?:

```rust
named!(keys_and_values_aggregator<&[u8], Vec<(&str,&str)> >, many0!(key_value));

fn keys_and_values(input: Vec<(&str,&str)>) -> HashMap<&str, &str> {
    let mut h: HashMap<&str, &str> = HashMap::new();
    for &(k,v) in input.iter() {
        h.insert(k, v);
    }
    h
}

named!(keys_and_values_hashmap<&[u8], HashMap<&str, &str> >, map!(keys_and_values_aggregator, keys_and_values));
```

In short, helper functions enough. Just instead of the standard functionality necessary to use helper functions.

**Comment by Geal** [comment]
I see what you mean. I wrote the INI parser a few months ago, and there was not as much tooling (and I did not know I could do `if let IResult::Done(i,o) = ...`).

The `map!` and `flat_map!` macros are useful for those cases. At one point, I had implemented those as a trait on `IResult`, but the generic types and the lifetimes made the code impossible to maintain.

**Comment by kgv** [comment]
Thanks for the answer.
