### ISSUE TITLE
verbose-error doesn't work with non-copy types

### ISSUE THREAD

**Issue by WaDelma** [Geal/nom#570]
If you try to parse using custom type that doesn't implement `Copy`, turning `verbose-error` feature on causes use of moved value errors.

**Comment by Geal** [comment]
Hello,
could you tell me more about this? Like, example code that triggers this?

**Comment by Geal** [comment]
I have [tests](https://github.com/Geal/nom/blob/master/tests/custom_errors.rs) using a `String` as custom error, which is not `Copy`, and it looks like it works.
If you find cases where it does not work, feel free to reopen this issue and send some code so I can debug it. Thanks for the report!

**Comment by WaDelma** [comment]
I wasn't able to minify the example, but I found the [first commit](https://github.com/WaDelma/darluca/tree/1e34ba62ad6644b8abc782bfbbf9e59627a816b8) that had the problem on my project.
