### ISSUE TITLE
Make escaped_transform! work with simple-errors

### ISSUE THREAD

**Issue by epilys** [Geal/nom#577]
`escaped_transform! `only works with `verbose-errors `enabled. This is documented in the docs but I didn't find a relevant issue.

Error message: 
```
error: cannot find macro `escaped_transform_impl!` in this scope
```

**Comment by Geal** [comment]
Hello,
this should be fixed with 727dca2. I'm not sure why enabling `verbose-errors` worked, but now it should be correct
