### ISSUE TITLE
Unexpected end of macro invocation in many_till!

### ISSUE THREAD

**Issue by rmbreak** [Geal/nom#580]
Code with `many_till!(le_u32, tag!(" DNE"))` fails to compile: https://play.rust-lang.org/?gist=440bd3d702c353f8aaa991bac1366d86&version=stable

A workaround is to wrap `le_u32` in the `call!` macro `many_till!(call!(le_u32), tag!(" DNE"))`: https://play.rust-lang.org/?gist=a88b0bd10eafae5684b4319df67c218a&version=stable

**Comment by Geal** [comment]
Hello,
this should be fixed with cf171a2 in nom 4.0

**Comment by rmbreak** [comment]
I can confirm that after changing my Cargo.toml nom dependency to
`nom = { git = "https://github.com/Geal/nom.git", rev = "cf171a2" }` and conforming to the new IResult interface, `many_till!(le_u32, tag!(" DNE"))` now works. Thanks!
