### ISSUE TITLE
Keeping mutable state when parsing

### ISSUE THREAD

**Issue by WaDelma** [Geal/nom#584]
I am creating lexer and parser for programming language, but now I want switch the identifiers that I keep with tokens to use interned strings.

I can't figure out how I can keep this mutable state while parsing with nom.

**Comment by WaDelma** [comment]
This same problem happens if you want to use some kind of arena for allocating while parsing.

**Comment by Geal** [comment]
You can add an argument to your parsers to pass your contexts. Or you can use the methods combinators to make the parsers methods of a type you defined: https://docs.rs/nom/3.2.0/nom/methods/index.html
