### ISSUE TITLE
separated_list! fails on end-of-input

### ISSUE THREAD

**Issue by steven807** [Geal/nom#587]
If a separated list reaches the end of the input, it returns Incomplete even if it has parsed a complete list.  I.e. the grammar
```
ALIST :: "a," <ALIST> | "a"
```
does not match `"a"`:

```rust
    named!(test_parser<Vec<&[u8]> >, separated_list!(tag!(","), tag!("a")));
    let empty = &[][..];
    let aslice = &(b"a")[..];
    assert_eq!(test_parser(b"a"), nom::IResult::Done(empty, vec![aslice]));
```
It similarly fails on `"a,a"`, and even an empty string.
All these cases work if there's an invalid continuation after the list, e.g. `"aX"`.

**Comment by Geal** [comment]
Hi!

The thing is, it does not fail, it just cannot decide based on the input (because you might refill your buffer and get an additional `,a` afterwards. If you know you have the full data, you should use [`separated_list_complete!`](https://docs.rs/nom/3.2.0/nom/macro.separated_list_complete.html) instead. More generally, if you have a parser returning `Incomplete` while you know you have the whole input, you can wrap that parser with the `complete!` combinator.

**Comment by Geal** [comment]
This kind of issue should be fixed by using the `CompleteStr` or `CompleteByteSlice` input types that were just introduced

**Comment by uwearzt** [comment]
Hmm, at least that is different in 3.2.1 and 4.0.0-beta1

```rust
#[macro_use]
extern crate nom;
use nom::digit;

named!(parse<&str, Vec<&str>>,
     separated_list_complete!(char!('/'), digit)
);

fn main() {
    println!("{:?}", parse("1/2/3"));
    println!("{:?}", parse("15/15/255"));
}
```

```bash
cargo run
   Compiling libc v0.2.39
   Compiling memchr v1.0.2
   Compiling nom v3.2.1
   Compiling nomtest v0.1.0 (file:///Users/uwe/repo/rust/nomtest)
    Finished dev [unoptimized + debuginfo] target(s) in 4.29 secs
     Running `target/debug/nomtest`
Done("", ["1", "2", "3"])
Done("", ["15", "15", "255"])
```

```bash
cargo run
   Compiling libc v0.2.39
   Compiling memchr v2.0.1
   Compiling nom v4.0.0-beta1
   Compiling nomtest v0.1.0 (file:///Users/uwe/repo/rust/nomtest)
    Finished dev [unoptimized + debuginfo] target(s) in 3.30 secs
     Running `target/debug/nomtest`
Ok(("/3", ["1", "2"]))
Ok(("/255", ["15", "15"]))
```

**Comment by uwearzt** [comment]
should i add a test to nom/tests/issues.rs?
