### ISSUE TITLE
Split the two syntaxes of the alt! macro into two separate macros

### ISSUE THREAD

**Issue by Etherian** [Geal/nom#588]
The alt! macro can be used in two forms: a simple syntax that simply tries a list parsers in-turn until one works and a match-like syntax that allows manipulation of the successful parser's return value.

I feel these two forms are different enough to deserve their own macros. Splitting the functionalities should make them easier to find, document, maintain, and debug.

**Comment by Geal** [comment]
it might be a good idea, but it probably won't happen until nom 5
