### ISSUE TITLE
macro/function explanations are too alike for beginners

### ISSUE THREAD

**Issue by steveeJ** [Geal/nom#592]
The differences between the variations of a macro seem to be really subtle from a beginners perspective. The wording could help significantly in understanding these differences.

An example from the docs:
1. take_until: consumes data until it finds the specified tag
2. take_until_and_consume: generates a parser consuming bytes until the specified byte sequence is found, and consumes it

Problems:
* (1) says _data_ and (2) says _bytes_
* (1) says _tag_ and (2) says _byte sequence_
* (1) and (2) appear to _consume_ the data

Fortunately I received help on IRC (thanks @s3bk!) and was explained that (1) doesn't consume the tag while (2) does, which makes a huge difference.
I'm not in a position to know and properly describe these subtleties yet so I can only file this issue about it ;-)
I'm surprised how complete the docs already are, now they just need some fine tuning 🙌

**Comment by Geal** [comment]
thank you for pointing it out! Could you send a PR to make the wording more coherent? It looks like you already grasped what those functions do anyway

**Comment by s3bk** [comment]
How about: 

take_until_and_consume:
> The parsed input and the tag are removed from the remainder. (As opposed to `take_until!` that does not remove the tag from the remainder.)

take_until:
> The remainder still contains the tag. (As opposed to `take_until!` which removes it from the remainder.)

This requires to introduce the term `reminder` somewhere.

**Comment by steveeJ** [comment]
@s3bk Once _remainder_ is introduced somewhere this explanation is accurate and simple to understand, great!
