### ISSUE TITLE
Documentation problems

### ISSUE THREAD

**Issue by vi** [Geal/nom#601]
1. [crates.io page](https://crates.io/crates/nom) points to [seemingly old documentation](http://rust.unhandledexpression.com/nom/) instead of usual [docs.rs](https://docs.rs/nom/3.2.1/nom/);
2. http://rust.unhandledexpression.com/nom/upgrading_to_nom_2.html <sup>http, not https? in 2017?</sup> is an empty page. No archived version on web.archive.org.
3. No "Migration from 2 to 3" document.

**Comment by vi** [comment]
Also the fact that nom is not best fit (am I right?) for parsing large recursive data that can't fit in memory should be documented somewhere, probably in making_a_new_parser_from_scratch.html.

**Comment by Geal** [comment]
closing this, since the documentation link is fixed and I don't really care for the tone of your other remarks
