### ISSUE TITLE
Parsing from token streams with custom token type?

### ISSUE THREAD

**Issue by Boscop** [Geal/nom#607]
Is it possible to use nom to parse from `&[Token]` where `Token` is a custom token type? :)
If so, how should it be done? Is there an example somewhere?

Bonus question: Is it also possible to parse from `syn::TokenTree` somehow?

**Comment by Geal** [comment]
hello,
it's possible with a custom input type for nom. Most combinators can work on any slices, not only `&[u8]` and `&str`. [rust-cexpr](https://github.com/jethrogb/rust-cexpr/blob/master/src/expr.rs) is a good example of this
