### ISSUE TITLE
[nom4] FindToken<&[u8]> not implemented for &[u8]

### ISSUE THREAD

**Issue by Keruspe** [Geal/nom#621]
```
the trait `nom::FindToken<&[u8]>` is not implemented for `&[u8]`
```

**Comment by kpp** [comment]
How did you fix that?

**Comment by Keruspe** [comment]
I didn't, that was me understanding the trait backward.

I tried to add a restriction T: FindToken<T> when what I needed was some impl FindToken<T> for u8.
