### ISSUE TITLE
Several parsers for one vector

### ISSUE THREAD

**Issue by ctjhoa** [Geal/nom#639]
Hi

**What were you trying to achieve**

I try to parse something like this in ebnf:
```ebnf
variant-list ::= variant* default-variant variant*
```
where `default-variant` is just variant with a different syntax.

**What is not working**

What I've got so far is to use `fold_many0` like this

```rust
named!(variant_list <&str, Vec<ast::Variant> >, 
    fold_many0!( alt!(variant | default_variant ), Vec::new(), |mut acc: Vec<_>, item| {
        acc.push(item);
        acc
    })
);
```

My issue is that it's not exactly what I expect because I do not ensure that there at least one `default-variant` in my list. What's the idiomatic way to do something like that with `nom`?

Thanks

**Comment by Geal** [comment]
it might be better to do it like your grammar proposes, parsing a vector of `variant`, one `default-variant`, then another vector of `variant`, then assembling the results
