### ISSUE TITLE
Type Parameters in named!() parser definition

### ISSUE THREAD

**Issue by transistorfet** [Geal/nom#642]
I'm having trouble specifying a named parser that uses a type parameter.
`named!(expression<AST<V>>, ...)`
where V is a type parameter and not a concrete type. Is there a way to do this without declaring the function directly?

**Comment by Geal** [comment]
Hello,

it is not possible to do that with the `named` macro, no. That macro is a shortcut to write functions, for more complex cases it is better to write your own, like this: http://rust.unhandledexpression.com/nom/how_nom_macros_work.html#passing-input
