### ISSUE TITLE
Improve compile time by factoring large parser code into functions

### ISSUE THREAD

**Issue by dtolnay** [Geal/nom#643]
Following up from https://github.com/dtolnay/syn/issues/195#issuecomment-348157176. Syn does a couple parsers differently from nom, for example `many0` which in nom is [a lot of macro code](https://github.com/Geal/nom/blob/a53febdfdf99d16c0177f5c605bd98481a4ec50f/src/multi.rs#L239-L277) and for us is [a function call](https://github.com/dtolnay/syn/blob/d67fb7572a65065015aacfe16af3004a3cfb8690/src/parsers.rs#L291) in the common case that the argument is a named parser.

**Comment by Geal** [comment]
that's a good point, thanks! I'll see if I can port that into nom

**Comment by Geal** [comment]
nom 5 is now made of functions, and the macros combinators use those functions under the hood :)
