### ISSUE TITLE
take_until_and_consume1! regression.

### ISSUE THREAD

**Issue by Pazzaz** [Geal/nom#648]
The macro `take_until_and_consume1!` isn't working in the latest version (4.0.0-alpha1). If you try to use it you'll get an error about a function expecting 2 parameters instead of 1. The function it is referring to is `need_more` which in  `take_until_and_consume1!` is used [here](https://github.com/Geal/nom/blob/a53febdfdf99d16c0177f5c605bd98481a4ec50f/src/bytes.rs#L766), like this:
```rust
need_more(Needed::Size($substr.input_len()))
```
I don't know much about macros but I think it's supposed to be the same as in the regular `take_until_and_consume!`  [here](https://github.com/Geal/nom/blob/a53febdfdf99d16c0177f5c605bd98481a4ec50f/src/bytes.rs#L723), like this:
```rust
need_more($i, Needed::Size($substr.input_len()))
```

Edit: Just saw #612, looks like it would fix this.

**Comment by Pazzaz** [comment]
It is also missing these `use` parts:
```rust
use $crate::FindSubstring;
use $crate::Slice;
```
that appear in `take_until_and_consume!`.

**Comment by Geal** [comment]
I merged the PR, this should work now
