### ISSUE TITLE
pub(crate) is not allowed in the named!()

### ISSUE THREAD

**Issue by vthriller** [Geal/nom#656]
This one is self-explanatory:

```
error: no rules expected the token `crate`
 --> src/lib.rs:4:12
  |
4 | named!(pub(crate) whatever, tag!("whatever"));
  |            ^^^^^
```

**Comment by veprbl** [comment]
#566

**Comment by vthriller** [comment]
Oh great, now I wonder why it [doesn't show up in search results](https://user-images.githubusercontent.com/176062/34944420-ee327928-fa18-11e7-979f-15bbf45ef922.png).

Closing this then.
