### ISSUE TITLE
CompleteStr/CompleteByteSlice are a bit cumbersome to use

### ISSUE THREAD

**Issue by veprbl** [Geal/nom#657]
Just finished adapting my small project to nom4. Because of breakage due to 47deaa1d037efd405d74cd63c928faf77354566f I had to switch to using CompleteStr. This required me to update a lot of the type signatures and the process was not exactly straightforward mostly due to convoluted macro expansion error messages. I'd like to share my experiences and few thoughts. I apologise if my explanations are not very clear, I'm open to making clarifications and further discussion.

One thing I noticed is that ```CompleteStr``` yields some strange notations in the tests like
```rust
assert_eq!(res, Ok((CompleteStr(&""[..], ...)));
```
The unconsumed input is being marked as ```CompleteStr```, which may make a bit of sense. But then outputs are also getting poisoned with the original type signature. Here is an example:
```rust
assert_eq!(
            delimited!(CompleteStr("foodatabar"), tag!("foo"), tag!("data"), tag!("bar")),
            Result::Ok((CompleteStr(&""[..]), CompleteStr(&"data"[..])))
            );
```
The ```"data"``` there is by no means "complete", it's just a random chunk of the input stream. In the end of the day, users will have to write boilerplate to clean these things up.

There also doesn't seem to be a way to use ```named!``` to define parsers that would instantiate to accept both ```&str``` and ```CompleteStr```. A streaming parser wrapper would need to eventually pass a ```CompleteStr``` into the same parser that previously took ```&str```. So, it appears, that a "completeness" is a property of the parser *invocation* and not a property of the *input data*. Also, ability to define parsers that accept both ```&str``` and ```CompleteStr``` would be useful for defining utility functions (e.g. ```double_s``` doesn't currently support ```CompleteStr``` because it's defined using ```named!```).

I wonder if another approach could have been taken. I'm thinking that EOF marker could be passed along with input in a separate parameter which can be preserved in combinators:
```rust
($i:expr, $eof:somekindofboolmarker, $submac:ident!( $($args:tt)* )) => (
   ...
   $submac!($i, $eof, $($args)*)
   ...
);
```

Alternatively one could introduce a type ```struct MaybeCompleteStr<'a>{ s: &'a str, eof_terminated: bool; }```, but this would require all checks to be done always at runtime. This also does not address some of the mentioned usability issues.

**Comment by Geal** [comment]
Since introducing those types, I have rewritten a lot of tests to use `CompleteByteSlice` and `CompleteStr` when necessary, sometimes even duplicating to compare the results, and it does not feel like a lot of boilerplate. nom 4 will anyway require a lot of work to upgrade for existing parsers (the move to `Result` requiring the most effort).

I'm thinking of introducing a type like the `MaybeStr` you indicate. If you want the `Complete*` version, always set eof to true, otherwise, set it when there is no more data. In any case, whether we reached eof or not is a runtime property.

The introduction of those types was discussed in #637.

**Comment by juanibiapina** [comment]
The Input type is conceptually wrong when it appears in a result. Shouldn't there be a way to unwrap the type and have a signature like?

```rust
named!(thing<CompleteStr, &str>, ...);
```

**Comment by mikolajpp** [comment]
Then how you would have to write a pipeline to turn each &str 
again into CompleteStr when it is feeded into next parser that you want to obey non-streaming nature of parsing.

If typing long CompleteStr is the problem, you can always alias it to `cstr`.

Unless you want to do streamed parsing, CompleteStr is precisely the right concept to manage that, given that nom defaults to throwing Incomplete around unless told not to.
