### ISSUE TITLE
Add to the documentation a list of the traits to implement for a proper input type

### ISSUE THREAD

**Issue by Ekleog** [Geal/nom#661]
The title says it all. Just adding this quote from IRC, just in case it could help:

geal │ ekleog: good point, open an issue, I'll add the list. The traits are in https://github.com/Geal/nom/blob/master/src/traits.rs and there's also Offset https://github.com/Geal/nom/blob/master/src/util.rs#L13
geal │ not all combinators require all traits though
geal │ like, this one is only needed for the escaped_transform combinator https://github.com/Geal/nom/blob/master/src/traits.rs#L735

Also, maybe this doesn't belong to this issue, but if one is supposed to implement `InputLength` for all input types, how would it be possible to handle the “waiting for network data” case of “This trait allows the input value to indicate whether there can be more input coming later (buffering data from a file, or waiting for network data)” ([source](https://github.com/Geal/nom/blob/master/doc/upgrading_to_nom_4.md#new-trait-for-input-types))? Is the trait just expected to return `usize::MAX` in the case of a stream of data of length unknown as of yet? (I assume here we want to have an on-demand waiting for network data packets as nom parses them, avoiding the `Incomplete` case by just adding data as required)

**Comment by Geal** [comment]
Hello,

the case where we're waiting for more data is handled by the `AtEof` trait. It has a `at_eof` method that must return true when we don't expect any more data

**Comment by Geal** [comment]
the traits re documented here: https://github.com/Geal/nom/blob/master/doc/custom_input_types.md
