### ISSUE TITLE
not! should propagate Incomplete

### ISSUE THREAD

**Issue by dlesl** [Geal/nom#665]
`not!`'s current behaviour is to return `Ok(_)` if the child parser returns `Incomplete`. Given the more strict usage of `Incomplete` in nom 4.0, I think it would be more intuitive only to succeed on `Err` and propagate `Incomplete`. 

### Example
```rust
assert_eq!(not!(&b"help"[..], tag!("hello")),
           Ok((&b"help"[..], ())));
assert_eq!(not!(&b"hel"[..], tag!("hello")),
           Err(Incomplete(Needed::Size(1)))); // returns Ok(_)
```
Side note: Should `not!` fail if it the child returns Failure?

**Comment by Geal** [comment]
Hello!
This should be fixed in a0ecc9b
