### ISSUE TITLE
nom 4.0.0-alpha2: missing pub in named_args!(pub $func_name:ident < 'a >)

### ISSUE THREAD

**Issue by blackgear** [Geal/nom#669]
https://github.com/Geal/nom/blob/master/src/macros.rs#L192

    (pub $func_name:ident < 'a > ( $( $arg:ident : $typ:ty ),* ) < $input_type:ty, $return_type:ty > , $submac:ident!( $($args:tt)* ) ) => {
        fn $func_name<'a>(
          input: $input_type, $( $arg : $typ ),*)
          -> $crate::IResult<$input_type, $return_type>
        {
            $submac!(input, $($args)*)
        }
    };

should be:

    (pub $func_name:ident < 'a > ( $( $arg:ident : $typ:ty ),* ) < $input_type:ty, $return_type:ty > , $submac:ident!( $($args:tt)* ) ) => {
        pub fn $func_name<'a>(
          input: $input_type, $( $arg : $typ ),*)
          -> $crate::IResult<$input_type, $return_type>
        {
            $submac!(input, $($args)*)
        }
    };

pub is missing in 2nd line.

**Comment by Geal** [comment]
thanks for the report, fixed in 9b2a4f8
