### ISSUE TITLE
take_until! says it has different behavior from take_until!

### ISSUE THREAD

**Issue by CAD97** [Geal/nom#670]
https://github.com/Geal/nom/blob/d6f35cc34135bbc3751ff3f92dde75cdb7229684/src/bytes.rs#L886-L902

> `take_until!(tag) => &[T] -> IResult<&[T], &[T]>` consumes data until it finds the specified tag.
> 
> The remainder still contains the tag. (As opposed to `take_until!` which removes it from the remainder.)

**Comment by petoknm** [comment]
Yea... I found it very confusing...

**Comment by Geal** [comment]
fixed in 54429544
