### ISSUE TITLE
no_std: feature guard for parsers that need alloc

### ISSUE THREAD

**Issue by kamarkiewicz** [Geal/nom#676]
Libraries that uses nom but don't have to make use of `Box` could be built on stable rust.
It is not possible, for now. The temporary solution is to fork nom, remove the following line and all parsers that make use of alloc.
```#![cfg_attr(not(feature = "std"), feature(alloc))]```
If the feature guard is possible, how it should look like? I'm thinking of a new feature called `alloc`.
I saw You have `nightly` feature already, so maybe I could reuse it in terms of the on-switch if `nightly` is used.

I can work on this and make a PR if You want.

**Comment by Geal** [comment]
oh, that's a nice idea, and would be easily compatible with the new plan for no_std/std/core, etc.

**Comment by glandium** [comment]
This was implemented in ba357743de04b2549776f5b712319c46c1ea57bd but the merge conflict resolution in 43ed4e99f39bc43f50178452def4e1797db8c95e broke it by adding a `#![cfg_attr(not(feature = "std"), feature(alloc))]` line to src/lib.rs.

**Comment by Geal** [comment]
hello, this should be fixed in nom 4
