### ISSUE TITLE
Allow named parsers to take parameters

### ISSUE THREAD

**Issue by PaperPlaneSoftware** [Geal/nom#682]
I'm not sure if this is already possible, but I want to be able to define parsers that take parameters.

My use case is to build a tree like structure from a string. The string is composed of nested `[ .. ]` blocks each defining a branch and a branch is defined by 3 hex characters e.g. `[abc[def[123]]]` would define a branch `abc` with a single child `def` with a single child `123`.

Certain attributes of a branch are taken from the 'depth' in the tree, for example branch `123` is shorter than `def` is shorter than `abc`.

I would like to be able to define parsers something like this:

```
named!(hex <&str,u8>, map_res!(re_find!(r"[0-9a-fA-F]"), |s| u8::from_str_radix(s, 16)));
named!(branch(d: u8) <&str,Branch>, do_parse!(x: hex >> y: hex >> z: hex >> Branch { x, y, z, d }));
named!(tree(d: u8) <&str,Tree>, do_parse!(char!('[') >> branch: branch(d) >> children: many0!(tree(d - 1)) >> char!(']') >> Tree { branch, children } ));
```

I've tried to develop my own parser as a function that takes the depth parameter but I got into all sorts of compiler problems.

Apologies if there's already a standard way of doing something like this, I'm new to nom and Rust.

**Comment by CAD97** [comment]
[`named_args!`](http://rust.unhandledexpression.com/nom/macro.named_args.html) ([4.0.0-alpha2](https://docs.rs/nom/4.0.0-alpha2/nom/macro.named_args.html)) does exactly what you want.

```rust
named_args!(name ( arg : Type ) < I , O >,
    submac!(..)
);
```

Alternatively, write the function out manually (required if lifetimes get complicated):

```rust
fn name(i: I, arg: Type) -> IResult<I, O> {
    submac!(i, ..)
}
```

**Comment by Geal** [comment]
Hello,

yes, `named_args` will do the trick, and with nom 4 there are the same lifetime fixes as in `named!`
