### ISSUE TITLE
Some `IResult::*` remain

### ISSUE THREAD

**Issue by CAD97** [Geal/nom#697]
These are all occurrences I could find of `IResult::` in the repository's code using GitHub's search.

https://github.com/Geal/nom/blob/28341e7c728bde3eebea859b86ededb0a52b24df/src/str.rs#L159-L174

https://github.com/Geal/nom/blob/55bac0bfa8794f087cc9057208ab60154a4dcbde/src/bits.rs#L322-L340

`#[cfg(feature = verbose-errors)]`

https://github.com/Geal/nom/blob/e58efb7f93046a49afecd9d9881caefeddff6cb8/tests/cross_function_backtracking.rs#L73-L75

https://github.com/Geal/nom/blob/e58efb7f93046a49afecd9d9881caefeddff6cb8/tests/cross_function_backtracking.rs#L91-L93

https://github.com/Geal/nom/blob/e58efb7f93046a49afecd9d9881caefeddff6cb8/tests/cross_function_backtracking.rs#L126

**Comment by Geal** [comment]
hello, this should be fixed by 6980b61 and dbbd6c9
