### ISSUE TITLE
Missing crate std

### ISSUE THREAD

**Issue by chris13524** [Geal/nom#704]
`named!(alt_tags, alt!(tag!("abcd") | tag!("efgh")));` causes an error in projects where no_std is used. Specifically, the usage of the tag!() macro causes this due to it's use of std [here](https://docs.rs/nom/4.0.0-alpha2/src/nom/bytes.rs.html#23).

No doubt this issue also exists in macros such as tag_no_case!() due to their use of the stdilb too.

**Comment by chris13524** [comment]
Actually, a lot of these combinators require the stdlib. So I'm confused on how nom is suppose to function without a stdlib?

**Comment by chris13524** [comment]
Actually, it looks like I needed `extern crate core as std;` in my file before using the macros. This seemed to fix the issue.

**Comment by kamarkiewicz** [comment]
There is a hack that re-exports some core functionality as std [here](https://docs.rs/nom/4.0.0-beta1/src/nom/lib.rs.html#370), so the extra `extern crate ...` should be not a requirement. Some combinators have wrong `use` statement then.

**Comment by Michael-F-Bryan** [comment]
I don't think that re-export hack is working. I've disabled default features (disabling `std`) and a trivial `do_parse!()` macro fails because it can't find the `std` hack module.

My `Cargo.toml`:

```toml
[dependencies]
nom = { version = "4.0.0-beta2", default_features = false, features = [] }
```

The Error:

```text
error[E0433]: failed to resolve. Maybe a missing `extern crate std;`?
  --> src/parse.rs:11:1
   |
11 | / named!(
12 | |     number,
13 | |     do_parse!(major: take_while1!(digit) >> (Number::Integer(major)))
14 | | );
   | |__^ Maybe a missing `extern crate std;`?
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to previous error
```

Expanded output with `-Z external-macro-backtrace` is attached.

[output.txt](https://github.com/Geal/nom/files/1884614/output.txt)

**Comment by chris13524** [comment]
@Michael-F-Bryan I think you need to enable the `alloc` feature.

**Comment by Michael-F-Bryan** [comment]
@chris13524 why is that? Looking at the source code, I should only need the `std` feature disabled. Also, if you look at the expanded error message it's pointing at a line containing `use ::std::result::Result::*`, which definitely shouldn't need the `alloc` feature to work.

```rust
#[cfg(not(feature = "std"))]
mod std {
  #[cfg(feature = "alloc")]
  #[macro_use]
  pub use alloc::{boxed, string, vec};

  pub use core::{cmp, convert, fmt, iter, mem, ops, option, result, slice, str};
  pub mod prelude {
    pub use core::prelude as v1;
  }
}
```
