### ISSUE TITLE
Could not find `vec` in `std`

### ISSUE THREAD

**Issue by chris13524** [Geal/nom#706]
I'm building a no_std thingie and attempting to use `many1!`. I'm including nom like this: `nom = { version = "4.0.0-beta1", default-features = false, features = ["alloc"] }` so the `alloc` feature should be enabled. I see that `vec` is being added to `std` [here](https://docs.rs/nom/4.0.0-beta1/src/nom/lib.rs.html#368) But this doesn't seem to be working.

**Comment by kamarkiewicz** [comment]
Does the same problem occur when you compile with current master?
(instead of `version` please try `git = "https://github.com/Geal/nom", branch = "master"`)

**Comment by Geal** [comment]
hello, on current master, with the commit 9b12a2d it should work now, can you test?

**Comment by chris13524** [comment]
Hmm, I can't recall how to reproduce this anymore... Probably worth closing and I'll re-open if I come across the issue again :)
