### ISSUE TITLE
Take remaining bytes.

### ISSUE THREAD

**Issue by meh** [Geal/nom#71]
Right now I'm doing this:

```rust
named!(verbatim(&'a [u8]) -> &'a str, map_res!(
	alt!(take_until_either!("|^*$#") | rest),
	str::from_utf8));

fn rest(i: &[u8]) -> IResult<&[u8], &[u8]> {
	IResult::Done(&i[i.len()..], i)
}
```

I need to take until one of those characters happens, or read up to the end and finish parsing. Is there a better way to do it currently?

**Comment by Geal** [comment]
No, that's exactly how you would do it. I could add `rest` to nom, though.

**Comment by meh** [comment]
That would be cool!

**Comment by Geal** [comment]
Thanks for your PR :)
