### ISSUE TITLE
ws! returns Incomplete incorrectly (4.0.0-alpha2 and on)

### ISSUE THREAD

**Issue by myrrlyn** [Geal/nom#718]
Rust: `nightly-2018-02-07` and `nightly`.
Nom: 4.0.0-alpha2, beta1, beta2.
Features: None.

## Description

The ws! macro has regressions when consuming input that has no whitespace to trim.

In alpha1, ws! sees a trimmed string and passes it unmodified to its inner function.

In alpha2, ws! aborts early when there is no TRAILING whitespace in the input. It works correctly when there is trailing whitespace, regardless of LEADING whitespace.

In beta1, ws! fails entirely, with unknown incomplete data.

In beta2, ws! fails entirely, with incomplete data of size 1.

## Test Cases

```rust
#[macro_use] extern crate nom;

ws!("  hello  ", tag_s!("hello")).unwrap();
ws!("hello  ", tag_s!("hello")).unwrap();
ws!("  hello", tag_s!("hello")).unwrap();
ws!("hello", tag_s!("hello")).unwrap();
ws!("\thello\t", tag_s!("hello")).unwrap();
```

- alpha1: Ok, Ok, Ok, Ok, Ok
- alpha2: Ok, Ok, Err(Incomplete(Unknown)), Err(Incomplete(Unknown)), Ok
- beta1: Err(Incomplete(Unknown)), Err(Incomplete(Unknown)), Err(Incomplete(Unknown)), Err(Incomplete(Unknown)), Err(Incomplete(Unknown))
- beta2: Err(Incomplete(Size(1))), Err(Incomplete(Size(1))), Err(Incomplete(Size(1))), Err(Incomplete(Size(1))), Err(Incomplete(Size(1)))

**Comment by myrrlyn** [comment]
Update: The above test case also fails on master, commit `ffb0783`.

**Comment by Geal** [comment]
as mentioned on twitter, this happens because nom is now much stricter on Incomplete usage, so we can use `CompleteByteSlice` and `CompleteStr` instead: https://github.com/Geal/nom/blob/master/doc/upgrading_to_nom_4.md#dealing-with-incomplete-usage
