### ISSUE TITLE
[src] hyperlink links to wrong section of source

### ISSUE THREAD

**Issue by frewsxcv** [Geal/nom#72]
Pressing `[src]` in http://rust.unhandledexpression.com/nom/fn.multispace.html

links to

http://rust.unhandledexpression.com/src/nom/nom.rs.html#139-151

**Comment by Geal** [comment]
Thanks, I'll regenerate the docs

**Comment by Geal** [comment]
hum, the problem is still there after regenerating. There may be something wrong with my cargo :(

**Comment by frewsxcv** [comment]
It links to the correct place for me

![screen shot 2015-08-24 at 7 28 48 pm](https://cloud.githubusercontent.com/assets/416575/9455170/6714d456-4a96-11e5-823e-1d04496af545.png)

**Comment by Geal** [comment]
It should be fixed now

**Comment by frewsxcv** [comment]
Awesome, thanks!
