### ISSUE TITLE
some combinators force the custom error type to u32

### ISSUE THREAD

**Issue by myeisha** [Geal/nom#732]
some combinators, specifically `complete` and `cond_reduce` in my case, force the custom error type to `u32` when they are used. i've had a quick look at the macro definitions and it seems that many other combinators also force the error type to `u32`, but not all of them.

demonstration of the problem:

```
fn err(i: &str) -> nom::IResult<&str, u32, bool> {
    Err(nom::Err::Error(error_position!(i, nom::ErrorKind::Custom(false))))
}

named!{test<&str, u32>, complete!(err) }
```

this fails during compilation:
```
error[E0308]: match arms have incompatible types
  --> src/main.rs:8:1
   |
8  |    named!{test<&str, u32>,
   |   _^
   |  |_|
   | ||
9  | ||     complete!(err)
10 | || }
   | || ^
   | ||_|
   | |__expected u32, found bool
   |    match arm with an incompatible type
   |
   = note: expected type `std::result::Result<(&str, u32), nom::Err<&str, u32>>`
              found type `std::result::Result<(&str, u32), nom::Err<&str, bool>>`

```

I'm using nom 4.0.0-beta2, but current master also forces the error type of some combinators.

**Comment by Lythenas** [comment]
I have noticed that as well. In the case of the `complete` macro I just copied it and removed the `u32`. Here is the code that worked for me:

```rust
macro_rules! complete (
  ($i:expr, $submac:ident!( $($args:tt)* )) => (
    {
      use nom::lib::std::result::Result::*;
      use nom::{Err,ErrorKind};

      let i_ = $i.clone();
      match $submac!(i_, $($args)*) {
        Err(Err::Incomplete(_)) =>  {
          Err(Err::Error(error_position!($i, ErrorKind::Complete)))
        },
        rest => rest
      }
    }
  );
  ($i:expr, $f:expr) => (
    complete!($i, call!($f));
  );
);
```

However I believe this is a bug because if you force the `u32` on `ErrorKind::Complete` the `rest`-arm of the match also has to have the error type `u32` which for me it is not.

I'm not sure if removing the `u32` causes errors elsewhere (maybe because of failed type inference).

**Comment by Geal** [comment]
hello,
basic parsers and some combinators for the custom error to a `u32` to fix type inference issues. I wanted to make everything generic, but unfortunately the compiler will always complain.
To convert error types, you can use the `fix_error!` combinator

**Comment by myeisha** [comment]
that works if you accept that a custom error type cannot have more distinct values than `u32`, which is a reasonable thing to expect tbh. in my case using `fix_error!` requires unsafe code or a massive `From<u32>` impl for my error type, neither of which are very ergonomic.

i do wish for a combinator that converts the error type to `u32`, applies another combinator, and then converts the error type back to what it was to begin with. something that expands `c!(T, submac!(...))` to `fix_error!(T, submac!(fix_error!(u32, ...)))`, maybe even with inference of `T` if that's possible in this setting.

**Comment by Geal** [comment]
I'm sorry, I did not really understand what you want here. Why would you need unsafe code or a massive `From` implementation?
nom's basic parsers will never return the `ErrorKind::Custom(_)` variant, so if you don't use the `u32` error variant, the transformation will be small.

**Comment by myeisha** [comment]
the basic parsers don't return custom errors, yes. i have some named parsers that do though, and in some places i want to use those with eg `cond_reduce`, which forces the custom error type to u32. my custom error type is just another C-style enum that i can convert to u32 and back, but since the enum is large the `From u32` impl would be large too--unless i unsafely cast the u32 to my enum.

am i missing something here?
