### ISSUE TITLE
Feature flagging the parser?

### ISSUE THREAD

**Issue by bitemyapp** [Geal/nom#739]
I need to do pragma-flagging with a Nom parser like Alex and Happy do in GHC:

Cf.

https://github.com/ghc/ghc/blob/master/compiler/parser/Lexer.x#L244

https://github.com/ghc/ghc/blob/master/compiler/parser/Lexer.x#L405

Could you please point me in the right direction for doing this?

**Comment by Geal** [comment]
hello, the [cond](https://docs.rs/nom/4.0.0/nom/macro.cond.html) combinator should help for this
