### ISSUE TITLE
[4.0.0-beta] `ws!` makes a parser always return `Err(Incomplete(Size(1))`.

### ISSUE THREAD

**Issue by Ploppz** [Geal/nom#751]
- Rust version : `rustc 1.25.0 (84203cac6 2018-03-25)`
- nom version : `4.0.0-beta`
- nom compilation features used: (none)

## Problem
`ws!` makes a parser always return `Err(Incomplete(Size(1))`.

## Test case

The following testcase prints "Incomplete(Size(1)". If you leave the `ws!` out, however, it prints "Ok".

```
#[macro_use]
extern crate nom;

fn main() {
    match hi("hi") {
        Ok(_) => println!("Ok"),
        Err(e) => println!("{:?}", e),
    }
}

named!(hi<&str, ()>,
    ws!(
    do_parse!(
        tag!("hi") >>
        ()
    ))
);
```

**Comment by Geal** [comment]
hello, the `ws!` combinator tries to parse white space before and after its child parser, and here the incomplete result comes from trying to parse whitespace in the remaining input after the tag consumed "hi".
nom 4 changes the behaviour around partial parsing, you should now use the CompleteStr wrapper: https://github.com/Geal/nom/blob/master/doc/upgrading_to_nom_4.md#dealing-with-incomplete-usage

**Comment by Rydgel** [comment]
I had the same issue for my lexer and using the `CompleteX` wrappers fixed it.

**Comment by XBagon** [comment]
Would it be possible to have `ws!` only waiting for more whitespace when the inner parser is currently `Incomplete`?
