### ISSUE TITLE
nom4: issues with slices and many0/many1/fold_many

### ISSUE THREAD

**Issue by chifflier** [Geal/nom#764]
- Rust version : rustc 1.27.0-nightly (ac3c2288f 2018-04-18)
- nom version : 4.0
- nom compilation features used: none

## Test case

Example test case:

```
#[macro_use]
extern crate nom;

use nom::be_u16;
fn main() {
    let input = &[0x01, 0x02];
    let res = many1!(&input[..], be_u16);
    println!("res: {:?}", res);
    assert_eq!(res, Ok((&b""[..],vec![0x0102])));
}
```
I'm parsing an array of exactly one element, so I expect the `many1` (or `many0`) combinator to succeed. Instead, it now always fails (regression from nom3):
```
res: Err(Incomplete(Size(2)))
thread 'macros::tests::test_nom4' panicked at 'assertion failed: `(left == right)`
  left: `Err(Incomplete(Size(2)))`,
 right: `Ok(([], [258]))`',
```

I understand the changes, but the handling of slices is clearly counter-intuitive now: you have to add `complete` while the input is complete ...

Proposed fix: succeed when elements have been parsed, and remaining slice is empty

**Comment by vadixidav** [comment]
@chifflier I seem to have ran into this issue as well. What is your temporary workaround to get `many0!` to work?

**Comment by vadixidav** [comment]
Also, my minimal example:

```rust
#[macro_use]
extern crate nom;

fn main() {
    named!(f<Vec<&[u8]>>, many0!(take!(1)));
    let a = &[0][..];
    f(a).unwrap();
}
```

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Incomplete(Size(1))', libcore\result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by Geal** [comment]
this issue is now fixed in nom 5, where we introduce specialized versions of some parsers for streaming or complete inputs
