### ISSUE TITLE
Optimise the layout of `IResult`s `Needed` member in `nom5`

### ISSUE THREAD

**Issue by Evrey** [Geal/nom#765]
Initial suggestion can be [read here](https://www.reddit.com/r/rust/comments/8jdih5/nom_40_is_released_faster_simpler_better_parsers/dz0aslt/).

Currently, the struct definition of `Needed` is:
```Rust
pub enum Needed {
    Unknown,
    Size(usize),
}
```
... which has two potential issues:

- Due to alignment requirements, its size is always `2 * mem::size_of::<usize>()`, wasting 31, 63, or 127 bits, depending on the target pointer width. I.e. almost 50% of that `enum`'s size is wasted memory.
- It is possible to create a `Size(0)` value, which makes no sense. That would literally mean *"I did not have enough bytes to finish parsing, so please give me no more bytes at all to finish parsing"*. Put another way, `Size(0)` is a special case that most likely indicates a bug.

So my proposal is to utilise an upcoming feature to reduce the size of `Needed` down to `mem::size_of::<usize>()`. By specifying that `Size(usize)` can never be zero, `rustc` will use the invalid zero state to represent `Unknown`. The new implementation might look like this:
```Rust
use core::num::NonZeroUsize;

pub enum Needed {
    Unknown,
    Size(NonZeroUsize),
}
```
Sadly, that optimisation has no impact on the size of `IResult`, so the only relevant benefit of that optimisation is the removal of a non-sensical special case. It is possible to further compress the whole `IResult`, but only by using very specialised types for inputs and outputs, which means that it effectively already is as small as it gets.

**Comment by ProgVal** [comment]
What about something like this?

```rust
use core::num::NonZeroUsize;

pub struct Needed(usize); // private field

impl Needed {
    pub fn size_needed(&self) -> Option<NonZeroUsize> {
        if self.0 == 0 { None} else { Some(self.size) }
    }
}
```

**Comment by Geal** [comment]
could that be done with some `repr()` magic?

**Comment by Geal** [comment]
done in d2d8d7b
