### ISSUE TITLE
Add the functions `rest_complete` and `rest_complete_s`

### ISSUE THREAD

**Issue by Evrey** [Geal/nom#776]
`nom` provides the functions `rest` and `rest_s` to return all the remaining input. `nom 4` also adds the types `CompleteStr` and `CompleteByteSlice` for situations where the entire amount of data to be parsed is available in one big chunk.

Now, in a `nom` parser using `CompleteStr`, trying to use `rest_s` causes a type error, as `rest_s` is hard-coded to only accept inputs of type `&str`. One solution would be to add two similar functions which act on the complete types, such as my tiny implementation from today:

```Rust
#[inline]
fn rest_complete_s<'a>(input: CompleteStr<'a>) -> IResult<CompleteStr<'a>, CompleteStr<'a>> {
    Ok((CompleteStr(&(input.0)[input.0.len()..]), input))
}
```

An alternative solution would be to make the `rest` function generic in a way that handles all the four input types `&str`, `&[u8]`, `CompleteStr`, and `CompleteByteSlice`.

**Comment by Geal** [comment]
it would probably be better to make it generic (and remove `rest_s` while we're at it)

**Comment by Geal** [comment]
`rest` is now a generic function
