### ISSUE TITLE
Give back ownership

### ISSUE THREAD

**Issue by ProgVal** [Geal/nom#786]
In my parser, I use this pattern several times:

```rust
do_parse!(
  foo: foo_subparser >>
  bar: alt!(
    call!(bar_subparser1, foo.clone())
  | call!(bar_subparser2, foo)
  ) >> ...
)
```

However, `bar_subparser1` and `bar_subparser2` only consume the `foo` if they succeed (to build their return value).
It would be nice to have a way to get the ownership back in the parent parser if one option of the `alt!` failed, so avoid a useless clone.

**Comment by Geal** [comment]
I'm not really sure how this could be fixed :/
