### ISSUE TITLE
ws!(return_error!(...)) fails to compile

### ISSUE THREAD

**Issue by sinesc** [Geal/nom#796]
Wrapping return_error! in ws! causes return_error! to accept only one argument. 

## Prerequisites

- Rust version : rustc 1.26.2
- nom version : 4.0.0
- nom compilation features used: none

## Test case

```
#[macro_use]
extern crate nom;

named!(test, ws!(return_error!(ErrorKind::Custom(1), tag!("a"))));
```
## Error message

```
error: no rules expected the token `,`
  --> src\parser.rs:70:52
   |
70 | named!(test, ws!(return_error!(ErrorKind::Custom(1), tag!("a"))));
   |                                                    ^
```

**Comment by Geal** [comment]
`ws` will not work with combinators like `return_error`. You can put the `return_error` use in a separate function, that should fix it
