### ISSUE TITLE
Make combinators compatible with non-copy input types

### ISSUE THREAD

**Issue by xpayn** [Geal/nom#803]
I'm implementing a parser for vcards, and lines can be folded as follow:
```
this is line
another line
  with continuation
folding can happen ev
 ery
 w
 here
```
which when unfolded gives
```
this is line
another line with continuation
folding can happen everywhere
```
To sumerize, if you encounter "\r\n ", consider that you haven't changed line.
Nothing really annoying but i want to use stock combinators on unfolded lines and i don't want to excessively allocate.
Furthermore, RFC 6350 warns you:
```
Note: It is possible for very simple implementations to generate
improperly folded lines in the middle of a UTF-8 multi-octet
sequence.  For this reason, implementations SHOULD unfold lines in
such a way as to properly restore the original sequence.
```
So i went from `&str` to `&[u8]`
My solution is to create my own input type which stores the unfolded lines as an u8 slice and a vector of ranges that maps valid data (everything except "\r\n ")
Because of the inner vector, it is non-copy and a lot of things just don't compile anymore.
I cloned `nom` and fixed what has stoped working (basically adding `.clone()` calls in the culprit combinators)

My case is peculiar, but i think it could useful to allow non-copy type as input.
I realise that it is certainly not a priority, that it might have performance impacts and that it will need careful testing.
If this issue is deemed of interest, I'll try to contribute a PR as I'm the one needing it.

**Comment by Geal** [comment]
hello,
which combinators had missing `clone()` calls?

**Comment by Geal** [comment]
closing this for now
