### ISSUE TITLE
suggestion: tuple!(only_one_parser) should return a tuple of length 1

### ISSUE THREAD

**Issue by rbalicki2** [Geal/nom#805]
Thank you for the great library! I'm using 4.0.0.

I noticed that tuple!(only_one_parser) returns the value of only_one_parser, instead of (what I think is expected), a tuple of length 1.

I'm using tuple!(only_one_parser) as a stand-in, until additional parsers are implemented, so for now, what I'm doing is tuple!(only_one_parser, opt!(call!(parser_that_always_fails))), which is totally sufficient!

Thank you!

**Comment by Geal** [comment]
IIRC there's no tuple of 1 element, as `(value)` will be `value` ?
