### ISSUE TITLE
Err(Incomplete(Size(1))) when parsing last float of line

### ISSUE THREAD

**Issue by mpizenberg** [Geal/nom#809]
## Prerequisites

Here are a few things you should provide to help me understand the issue:

- Rust version : `1.26.0`
- nom version : `4.0.0`
- nom compilation features used: none

## Test case

I'm trying to parse a text file with multiple floats on each line to build types I have defined. The last float of each line does not seem to be parsable. Basically, my issue boils down to this example:

```rust
extern crate nom;

fn main() {
    println!("{:?}", nom::float_s("42.14"));
}
```

Which gives me:

```
Err(Incomplete(Size(1)))
```

Sorry if there is an example provided for this simple use case but I didn't see one?

**Comment by ian-p-cooke** [comment]
I replied to this [on reddit](https://www.reddit.com/r/rust/comments/8vhojh/hey_rustaceans_got_an_easy_question_ask_here/e1sejia/) and I'm wondering: is my solution using CompleteStr the recommended way of doing things?

The only thing I didn't like was having to define yet another 'float' parsing method and then I realized you could have one parser for f32 and f64 that covered &[u8], &str, and CompleteStr if you made it generic enough.  For example:

    #[allow(unused_imports)]
    pub fn floating_point<I, O, U>(input: I) -> IResult<I, O>
    where
        I:  Clone
            + nom::Slice<std::ops::Range<usize>>
            + nom::Slice<std::ops::RangeFrom<usize>>
            + nom::Slice<std::ops::RangeTo<usize>>
            + nom::Offset
            + nom::InputIter<Item = U, RawItem = U>
            + nom::AtEof
            + nom::InputLength
            + nom::InputTake
            + nom::ParseTo<O>
            + nom::InputTakeAtPosition<Item = U>,
        U: nom::AsChar,
    {
        flat_map!(input, call!(recognize_float), parse_to!(O))
    }

the only real drawback I see is that if type inference isn't available specifying the template parameters is kind of annoying: `floating_point::<CompleteStr, f32, char>(CompleteStr("3.14"))`  @Geal Would you be interested in a patch that added a method like this (and maybe deprecating the others)?

**Comment by danilaml** [comment]
This issue is very frustrating. I'm new to Rust and was trying to write a simple parse. Testing it on an input like `b"123"` was the first thing I tried and I couldn't figure out why it was failing on me (the fact that it was in `alt!` and as such I got even less useful `Err(Error(Code([49, 50, 51], Alt)))` didn't help).

Since the documentation lacks any example on how to use `(float|double)[_s]` functions I though I just didn't understand how to use nom and abandoned my project for a few months. It was a very demotivating experience.

**Comment by Geal** [comment]
hello,

since b96d630 (will be part of the upcoming 4.1 release), float and double will now work on all compatible nom input types (ie, those that implement nom's input type traits). float_s and double_s got the same fix, but are now marked as deprecated and will be removed in nom 5.0
