### ISSUE TITLE
Can nom work with AsyncRead?

### ISSUE THREAD

**Issue by lilith** [Geal/nom#810]
Does nom offer a way to work against async streams (like https://tokio-rs.github.io/tokio/tokio/io/trait.AsyncRead.html)?

**Comment by Geal** [comment]
Hello,

to integrate with tokio, it's a good idea to write a [tokio transport](https://tokio.rs/docs/going-deeper/frames/), as in https://github.com/sozu-proxy/lapin/blob/master/futures/src/transport.rs#L31-L55

nom is designed for that kind of use case :)

**Comment by alishir** [comment]
Hello @Geal,

I think with this approach we do call some parsers over and over, for example if we receive an stream that contains HTTP request, we parse the method multiple times. am I right?

**Comment by Geal** [comment]
It depends on the protocol you're parsing, but it's a tradeoff you have to decide about:
- either you write manually a state machine working byte by byte, like https://github.com/nodejs/http-parser (personally, I think it's cumbersome to write and maintain, and also a bit slow to run)
- or you have a state machine that knows which parser to apply next, ie, parse method and uri, store it, then call the header parser in a loop, then parse the body if necessary. The HTTP parser in [sozu](https://github.com/sozu-proxy/sozu) works that way
- or you could also assume that most requests will fit entirely into you input buffer, so in the common case when you get to it all the data is already in the buffer and the parser is called once, or the parser tells you that it needs more data in rare cases for which you have to accumulate more data and try again

**Comment by alishir** [comment]
@Geal Thanks a lot for detailed explanation.

**Comment by alishir** [comment]
@Geal Thanks a lot for detailed explanation.

**Comment by cheako** [comment]
I think this issue should be open.  Did Tokio remove transports?  I feel like this would need async versions of `Compare`, `InputTakeAtPosition`, `InputTake`,  `InputIter`, etc.  I.E. A whole new crate.

**Comment by Geal** [comment]
You can use [nom-bufreader](https://crates.io/crates/nom-bufreader) now, it helps a lot

**Comment by cheako** [comment]
Add that to the README :)
