### ISSUE TITLE
[long-term enhancement] Resuming parsing / playing nicely with tokio

### ISSUE THREAD

**Issue by Ekleog** [Geal/nom#811]
This is similar to #810, although I think it's not exactly the same thing.

What I'm thinking of is the possibility to resume parsing after a `nom::Incomplete` return, so that `nom` could just request more data from `tokio`, and when it becomes available resume parsing without having to re-parse all the already-parsed data.

Ideally, this idea would end in a `Stream` adapter that'd do eg. `Stream<Item: Buf> -> Stream<Item = Parsed>`. And ideally would provide a way from the returned `Stream` to recover the underlying `Stream<Item: Buf>` of unparsed-yet content, for when the type of the elements to parse would change. 

Use case: for SMTP parsing, I'm currently batching data to read into a full-line buffer then throwing `nom` on it. This would be helped much by the `Stream` adapter. But when a `DATA\r\n` comes in, I need to recover the underlying data stream, that could already have been passed-through to the line-buffering adapter. Hence [my current solution](https://github.com/Ekleog/yuubind/blob/master/smtp-server/src/crlflines.rs) about this, that heavily relies on the fact that I *know* I can just line-buffer the data. Also, it allocates much more than what a more-integrated-with-`nom` solution could do, because the buffers actually should not need to be contiguous in memory in order for `nom` to parse them.

Just throwing ideas out in the air for now, though :)

**Comment by Geal** [comment]
hello,
this will not be possible with nom directly. This is something that I tried to have in nom's first versions, and it would require nom's incomplete result to return a closure (like Parsec) that has references to the input. But that input would still need to be modified to accumulate more data.

There will be better patterns with generators, see this test for a nice example: https://github.com/geal/generator_nom

**Comment by Geal** [comment]
if you make a nom input type that works on non contiguous memory (like ropes or something else), it should work. I had an example of that somewhere but don't remember where I put it :(

**Comment by brainstorm** [comment]
I second the thoughts from @Ekleog ... [I'm currently implementing](https://github.com/brainstorm/bio-index-formats) an [async-await Rusoto (Amazon S3)](https://github.com/brainstorm/htsget-aws/blob/master/reads/Cargo.toml#L25) crate that reads a file from a bucket and I expected Nom to stream+read+pause+resume as the download transfer goes (or briefly stalls and continues)... [unfortunately I'm finding myself having to read the whole array of `&[u8]` for the Nom parser in memory, despite using `nom::bytes::streaming::{tag, take};`](https://github.com/brainstorm/htsget-aws/commit/7e93acfe02ea8dfd34079e597abbbd9e11b30141)... or at least that's what people with more experience than me recommend in the interface of tokio/futures and their Nom experience :-S

**Comment by Geal** [comment]
Nom should not decide where to pause or restart or how much data should be read because that's a task for the upper layer. Otherwise you could get a format that indicate a petabyte sized string and nom would keep asking to read and reallocate.
If you want to parse in streaming, you're responsible for deciding where it should pause.
As an example, for http, nom would parse the headers and return the content length, then the calling code decides to read or not. For chunks, nom would parse the chunk header and return its size, then you handle that
