### ISSUE TITLE
double_s does not work for CompleteStr parser

### ISSUE THREAD

**Issue by spease** [Geal/nom#815]
nom version: 0.4.0

The double_s function does not work directly with the new CompleteStr API. I was able to devise a wrapper method that at least passes my unit tests (I don't know how correct it is though). But it would be extremely nice if either double/double_s could be used directly with CompleteStr, or there was a general wrapper for the _s functions. I think this is likely too hard to be discoverable to a beginning nom user, and the preexisting tutorials use double_s, which could create a brick wall for new users.

```
pub fn double_cs(input: CompleteStr) -> ::nom::IResult<CompleteStr, f64> {
    nom::double_s(input.0).map(|r| (CompleteStr(r.0), r.1)).map_err(|e| {
        match e {
            nom::Err::Incomplete(a) => nom::Err::Incomplete(a),
            nom::Err::Error(c) => match c {
                nom::simple_errors::Context::Code(a,b) => nom::Err::Error(nom::simple_errors::Context::Code(CompleteStr(a), b)),
            },
            nom::Err::Failure(c) => match c {
                nom::simple_errors::Context::Code(a,b) => nom::Err::Failure(nom::simple_errors::Context::Code(CompleteStr(a), b)),
            }
        }
    })
}
```

**Comment by Geal** [comment]
hello,
since b96d630 (will be part of the upcoming 4.1 release), `float` and `double` will now work on all compatible nom input types (ie, those that implement nom's input type traits). `float_s` and `double_s` got the same fix, but are now marked as deprecated and will be removed in nom 5.0
