### ISSUE TITLE
Missing "pub" in method!()

### ISSUE THREAD

**Issue by Arcterus** [Geal/nom#816]
Two of the supposedly public expansions for `method!()` are missing `pub`.  This issue occurs on (at a minimum) the latest released version of nom.  It's triggerable with something like:
```rust
method!(pub complete_command<Parser, &[u8], CompleteCommand, ParserError>, mut self,
    // stuff goes here
);
```

**Comment by Geal** [comment]
thank you for the report, it's fixed in e7e7a4e
