### ISSUE TITLE
return_error!() fails with mutable arguments

### ISSUE THREAD

**Issue by Arcterus** [Geal/nom#817]
`return_error!()` fails if the parser take mutable arguments (or at least this seems to be the issue).  This issue occurs on the latest released version of nom.  Changing `let cl = // blah` to `let mut cl = // blah` in the macro fixes the issue for me.  Here is an example that triggers the problem:
```rust
type IResult<'a, O> = nom::IResult<&'a [u8], O, ParserError>;
fn function_def<'a>(input: &'a [u8], parser: &mut Parser) -> IResult<'a, FunctionDef> {
    do_parse!(input,
        name: fname >>
        tag_token!("()") >>
        call!(linebreak, parser) >>
        body: return_error!(ErrorKind::Custom(ParserError::FunctionDef), call!(function_body, parser)) >>
        (FunctionDef::new(name, Rc::new(body)))
    )
}
```

**Comment by Geal** [comment]
hello,

could you provide a smaller test case, that does not use functions and structs that are not available here?
