### ISSUE TITLE
user state?

### ISSUE THREAD

**Issue by mgreenbe** [Geal/nom#822]
Are there idioms/features for passing user state through nom parsers, like in Haskell's Parsec? (I guess this could be considered a feature request, for labelling purposes.)

**Comment by Geal** [comment]
Hello,
there's the [methods approach](https://docs.rs/nom/4.0.0/nom/methods/index.html), and you can also pass state explicitely as a parameter with [named_args](https://docs.rs/nom/4.0.0/nom/macro.named_args.html)
