### ISSUE TITLE
Revisit the recommended formatting of nom macro invocations

### ISSUE THREAD

**Issue by dtolnay** [Geal/nom#829]
Over the past two years, the [style team](https://github.com/rust-lang/rfcs/blob/master/text/1607-style-rfcs.md) has settled on a Rust style that uses exclusively four-space indentation

> Each level of indentation must be four spaces (that is, all indentation
> outside of string literals and comments must be a multiple of four).

and discourages any form of "visual" alignment meaning whitespace within a line to align tokens on vertical column boundaries. Please find the complete formatting guidelines RFC in https://github.com/rust-lang/rfcs/pull/2436.

I find that the heavily visually aligned style in nom's documentation looks very out of place in modern Rust code formatted according to the style team guidelines. Notice the two-space indentation, the one line indented by 11 spaces to achieve visual alignment, and the visual alignment of the `hex_primary` and `>>` tokens in the following snippet from the readme.

```rust
named!(hex_color<&str, Color>,
  do_parse!(
           tag!("#")   >>
    red:   hex_primary >>
    green: hex_primary >>
    blue:  hex_primary >>
    (Color { red, green, blue })
  )
);
```

It would be valuable to redesign how we intend for nom macro invocations to be formatted in modern Rust code, adjusting the input syntax of macros as necessary to arrive at a style that is harmonious with the one being pushed by the style team.

**Comment by Geal** [comment]
it would probably be useful to define a proper style for nom macros. I see two issues for now:
- rustfmt has always had a hard time to format macros correctly, so much so that I had to [skip it entirely for some parts of the code](https://github.com/Geal/nom/blob/master/src/nom.rs#L787-L813)
- do nom parsers, as a specific DSL, have to follow Rust's style guide?

**Comment by dtolnay** [comment]
- The documentation should display a well thought-out style regardless of whether that style is implemented in rustfmt.
- Yes, I believe any DSL embedded in Rust should follow a style that is harmonious with the Rust style to the extent possible. I believe it is possible to come up with a style for nom parsers that does this better.
