### ISSUE TITLE
macros shouldn't evaluate their arguments multiple times

### ISSUE THREAD

**Issue by bwo** [Geal/nom#831]
- Rust version : rustc 1.30.0-nightly (73c78734b 2018-08-05)
- nom version : nom 4.0.0
- nom compilation features used: defaults

## Test case

Please provide a short, complete (with crate import, etc) test case for
the issue, showing clearly the expected and obtained results.

Example test case:

```rust
#[macro_use]
extern crate nom;
named!(err_test, add_return_error!(ErrorKind::Custom({
    println!("hi"); 42u32
}), tag!("a test")));


#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn test_err() {
        err_test(b"asdf");
        assert!(false);
    }
}
```

Expected result: test fails; "hi" prints once
Actual result: test fails; "hi" prints twice.

This is unsurprising because the core of `add_return_error` is:

```rust
      match $submac!($i, $($args)*) {
        Ok((i, o))    => Ok((i, o)),
        Err(Err::Error(e))      => {
          unify_types(&e, &Context::Code($i, $code));
          Err(Err::Error(error_node_position!($i, $code, e)))
        },
        Err(Err::Failure(e))      => {
          unify_types(&e, &Context::Code($i, $code));
          Err(Err::Failure(error_node_position!($i, $code, e)))
        },
        Err(e) => Err(e),
      }
```

Each branch that uses `$code` uses the captured expression twice.

**Comment by Geal** [comment]
that's interesting. So maybe I should first put the argument in a local variable, then move it to the result afterwards?

**Comment by bwo** [comment]
yeah, that will fix it.

**Comment by Geal** [comment]
the current fix might evaluate the error code in all cases, even when succeeding

**Comment by Geal** [comment]
reworked in 5edc06b
