### ISSUE TITLE
usability: address changes introduced with Complete* and many* combinators

### ISSUE THREAD

**Issue by Geal** [Geal/nom#839]
references:
- #764 nom4: issues with slices and many0/many1/fold_many
- #766 nom4: take_while broken ?
- #768 Update breaks 11-bit parser- always Incomplete
- #790 many0 returns Incomplete in weird cases
- #795 CompleteByteSlice/CompleteStr are invasive and make parsers not reusable

There are especially issues around transforming to and from the `Complete*` types, when reusing parsers or passing the results through `flat_map!` and other combinators.

There's also the problem of making sure basic parser functions work with all types. As an example, the `hex_u32`, `be_*` and `le_*` only work on `&[u8]`, not `CompleteByteSlice`

**Comment by zaphar** [comment]
Just want to say that this particular issue is a blocker for my moving a project over to nom4. I was really excited to see the improvements in error handling in nom4 but this change and the invasiveness of the fix are giving me pause to finishing the conversion.

Most of the other changes are pretty mechanical and easy to do. This one does not fall in that category though.

**Comment by Geal** [comment]
@zaphar can you provide examples of code that is affected by the changes? This will help me think about the issue

**Comment by leshow** [comment]
Since my issue is mentioned, just like to add I'm still on nom 2. @khernyo appears to have written a PR to fix my particular problem (referenced in the issue)

**Comment by athei** [comment]
That is nice! With that change is there even a use case for `many0` and similar macros? They always return `Incomplete` and everyone just tries to come up with hacks to make them behave like the `many0_complete` you proposed. When you think about it they make only sense as complete version because how would a streaming parser know when `many0` is done: The amount or length was transmitted and they are usually called through something like `delimited!` or `length_bytes!` through which we know for sure that the input must me complete.

That means the `Incomplete` is always returned by a caller of `many0` but never by `many0` itself and therefore there is no reason to have non-complete versions of them.

**Comment by Geal** [comment]
the current behaviour of `many0!` is actually correct. It should stop and return the `Vec` of values once its underlying parser fails, but the issue is in defining what makes that parser fails.
Imagine you have the following: `named!(parser<Vec<&[u8]>>, many0!(tag!("abc")))`
if you pass `abcabcabc!` the parser will return `["abc", "abc", "abc"]` as expected, because the `tag` will fail on the `!` character.
But if you pass `abcabc`, the parser has no way of knowing if that's the whole input, or if it's missing data and the whole input is actually `abcabcabc!`.
But as you mentioned, often when working in streaming mode with length delimited format, we get fields for which we know the exact length (and probably have everything in the buffer already) so we should be able to switch to another behaviour.

**Comment by athei** [comment]
Ahh okay I was under the impression that `many0!` returns an error when the underlying parser fails. My mistake. It makes much more sense now in my head. Yes, complete versions of the macros would be much appreciated.

**Comment by leshow** [comment]
I noticed my issue was close, but doesn't work on 4.2. These changes will be included in 5?

**Comment by Geal** [comment]
closing this now, as nom 5 will fix those usability issues with `CompleteByteSlice` and `CompleteStr` by *check notes* REMOVING THEM ENTIRELY :D

Now there are specialized versions of parsers for streaming or complete input data in the `streaming` or `complete` submodules for some parser categories (see for example `nom::character` or nom::number`)
