### ISSUE TITLE
"verbose-errors" changes nom's API

### ISSUE THREAD

**Issue by jsgf** [Geal/nom#843]
## Prerequisites

Here are a few things you should provide to help me understand the issue:

- Rust version : 1.29.0
- nom version : 3.2.1
- nom compilation features used:

The `verbose-errors` feature changes `nom`'s API by changing the definition of the `IResult` type in a non-compatible way. This means that enabling the feature will break downstream users which don't expect it.

Since `cargo` always accumulates features across the dependency graph, if there are two users of `nom` within the same dep graph, and one enabled `verbose-errors`, it will break the other user which doesn't want it.

This is because in general cargo expects features to extend the functionality of a crate in a compatible way.

It would be better to make the `verbose-` and `simple-` explicit separate parts of the exposed API so that you can just use the API you want from a single instance of the crate.

cc: @alexcrichton

**Comment by Geal** [comment]
hello,

there's a workaround in nom 4: the errors are now an enum, and the one from `verbose-errors` includes the only case from `simple-errors`.

**Comment by kryptan** [comment]
@Geal, what do you mean by workaround? How do I actually handle the error in a way that won't break if `verbose-errors` is enabled?

```Rust
match context {
    Context::Code(input, error) => { ... },
    _ => unreachable!(),
}
```

This generates a warning about unreachable pattern and would panic if `verbose-errors` is enabled and other variant is returned.

Can you please provide an example how to handle the error properly?

**Comment by Geal** [comment]
`verbose-errors` has disappeared in nom 5. Now the error behaviour is completely decided by the error type
