### ISSUE TITLE
Allow consuming input for generic inputs

### ISSUE THREAD

**Issue by rubdos** [Geal/nom#847]
## My problem/case

Consider a parser that wants to be generic over its input: streaming/in memory, and tries to construct valid utf8 `str`'s without any copying.

```rust
fn header_field<'a, T>(input: T) -> IResult<T, (&'a str, &'a str), u32>
where
 T: 'a,
  T: Slice<Range<usize>> + Slice<RangeFrom<usize>> + Slice<RangeTo<usize>>,
  T: Clone + Offset,
  T: AsBytes + InputIter + AtEof,
  T: PartialEq,
  T: FindSubstring<&'a [u8]>,
 <T as InputIter>::Item: AsChar,
 T: InputTakeAtPosition,
 <T as InputTakeAtPosition>::Item: AsChar
{
   do_parse!(input,
       key: map_res!(
               map!(take_until_and_consume!(b":" as &[u8]),
                    |a| a.as_bytes()),
               std::str::from_utf8) >>
       val: map_res!(
               map!(take_until_and_consume!(b"\r" as &[u8]),
                    |a| a.as_bytes()),
               std::str::from_utf8) >>
       (key.trim(), val)
   )
}
```

`take_until_and_consume!` returns a `T`. The `AsBytes` trait however borrows from `T`, which makes the lifetimes in `|a| a.as_bytes()` closure impossible to satisfy (`a` gets dropped while borrowed). Note that semantically, `T` *is* a borrowed value (`&'a [u8]`, `CompleteByteSlice<'a>`), so this paradigm *should* make sense.

## Proposed solution

A `IntoBytes` trait can solve this issue:

```rust
pub trait IntoBytes<'a> {
    fn into_bytes(self) -> &'a [u8];
}

impl<'a> IntoBytes<'a> for &'a [u8] {
    fn into_bytes(self) -> &'a [u8] {
        self
    }
}

impl<'a> IntoBytes<'a> for CompleteByteSlice<'a> {
    fn into_bytes(self) -> &'a [u8] {
        self.0
    }
}
```

Or maybe even "just" implement `CompleteByteSlice<'a>: Into<&'a [u8]>`?

**Comment by Geal** [comment]
`CompleteByteSlice` and `CompleteStr` were removed in nom 5, things should be easier once it's released
