### ISSUE TITLE
Better document how to sanity check inside parser

### ISSUE THREAD

**Issue by MoritzFago** [Geal/nom#852]
## Prerequisites

Here are a few things you should provide to help me understand the issue:

- Rust version : rustc 1.32.0-nightly (6f93e93af 2018-11-14)
- nom version :4.1.1
- nom compilation features used:
none?
## Test case

Please provide a short, complete (with crate import, etc) test case for
the issue, showing clearly the expected and obtained results.

Example test case:

```
named_args!(parse_blob_string(len: u32)<Blob>,
	do_parse!(
		value!(if len ==0 {return Err(nom::Err::Failure(Context::Code(&[0], ErrorKind::Custom(INVALID_STRING_LENGTH))))})>>
		str: dbg_dmp!(take_str!(len -1 ))>>
		_terminator: tag!([0u8])>>
		( Blob::String(&str) ) 
		)
	);
```

How to do bettter error handling? This can't be the nom way to do it. Also better document how to.
Suggestion: 
cond_error!(cond like a.len()==0,ErrorSTring like "{} has a len of 0", a.len")

**Comment by Geal** [comment]
it should be easier to rewrite your parser like this:
```
fn parse_blob_string(i: &[u8], len: u32) -> IResult<&[u8], Blob> {
  if len ==0 {
    return Err(nom::Err::Failure(Context::Code(&[0], ErrorKind::Custom(INVALID_STRING_LENGTH))));
  }

  let (i, str) = take_str!(i, len - 1)?;
  let (i, terminator) = tag!(i, [0u8])?;

  Ok((i, Blob::String(str)))
}
```
