### ISSUE TITLE
Inefficient memory usage - clone()

### ISSUE THREAD

**Issue by ngortheone** [Geal/nom#863]
Hi, I've been working on a small project and I was debugging my code as I had to look at expanded macros generated by nom. 

Here is a sample parser:
```
named!(parse_priority<&str,char>,
    do_parse!(
        space1 >>
        c: delimited!(
                    tag!("[#"),
                    take_while_m_n!(1, 1, |c: char| c.is_alphabetic()),
                    tag!("]")) >>
     ( c.chars().next().unwrap()) )
));
```

By looking at the code with `cargo rustc -- -Z unstable-options --pretty=expanded ` I can see that this small function clones input var `i` at least 3-4 times! 
```
fn parse_priority(i: &str) -> ::nom::IResult<&str, char, u32> {
    {
        {
            use ::nom::lib::std::result::Result::*;
            let i_ = i.clone();
            match space1(i_) {
                Err(e) => Err(e),
                Ok((i, _)) => {
                    let i_ = i.clone();
                    {
                        use ::nom::lib::std::result::Result::*;
                        let i_ = i_.clone();
                        match {
                                  use ::nom::lib::std::result::Result::*;
                                  match {
                                            let i_ = i_.clone();
                                            ({
                                                 use ::nom::lib::std::result::Result::*;
                                                 use ::nom::{Err, Needed,
                                                             IResult,
                                                             ErrorKind};
....rest is omitted
```

I am not a Rust expert, but this seems to me a bit strange and not efficient at all!

**Comment by Veykril** [comment]
If I am not mistaken this clone actually only clones the reference and not the data itself meaning there is no actual performance impact here.

**Comment by Geal** [comment]
`&[u8]` and `&str` are `Copy` type, so they get an efficient `Clone` implementation. You can test it in this playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=05c1d3690e542a56fd3e609f5f4ee74d
Try debug and release versions, in "show assembly" mode. You'll see that it results in two ints moved around (a `&str` and `&[u8]` contain a pointer and a length).

**Comment by Geal** [comment]
the `clone()` call was introduced to allow non `Copy` input types: https://github.com/Geal/nom/commit/fdfb7b7b76e2b86a01e99f615b8679d764121828

**Comment by ngortheone** [comment]
@Geal @Veykril Thanks for clarification!
