### ISSUE TITLE
nom dbg! macro seems to be conflicting with std dbg! macro

### ISSUE THREAD

**Issue by ncoif** [Geal/nom#864]
Hello!!

It seems that the [nom](https://docs.rs/nom/4.2.0/nom/macro.dbg.html) `dbg!` macro is conflicting with the newly introduced [std](https://doc.rust-lang.org/std/macro.dbg.html) `dbg!` macro (because of a different expected syntax).

```
rustc 1.32.0 (9fda7c223 2019-01-16)
nom = "4.2.0"
```

Here is an example of code that doesn't compile, with a `expected expression` error.

```
#[macro_use]
extern crate nom;

fn main() {
  let res = 42;
  dbg!(&res);
}
```

Disclaimer: I'm pretty new to rust, so if there is a way to selectively indicate which macro namespace to use, or to exclude some macros when using a crate, that would be helpful.

Thanks a lot!!

**Comment by lucasem** [comment]
Use `std::dbg!` — or better yet, get rid of the blanket macro import with `#[macro_use] extern crate nom` and just import the macros you need (e.g. `use nom::{method, tag}`) if you're on the 2018 edition.

**Comment by ncoif** [comment]
Thanks a lot!!
