### ISSUE TITLE
"unexpected end of macro invocation"

### ISSUE THREAD

**Issue by gregberns** [Geal/nom#866]
When nesting `sep` and `permutation` there is an issue when compiling, but the errors are incomprehensible, so just wanted to bring it up.
I'm very new to this so just wanted to report it. Hopefully there's a workaround or I'm just doing something wrong. I hope I provided enough information to replicate.

## Prerequisites

- Rust version : rustc 1.33.0-nightly (8e2063d02 2019-01-07)
- nom version : "4.2"
- nom compilation features used: (I don't think I'm using any)

## Test case

The following code fails to compile due to what looks like macro parsing issues, potentially because of nested macros. 

The problem is that I don't really have any idea how to change the code to fix the issue.

Compile error:
```
error: unexpected end of macro invocation
  --> <::nom::whitespace::permutation_iterator_sep macros>:33:52
   |
33 | $ i , $ separator , $ all_done , $ needed , $ res , $ ( $ rest ) * ) ) ; } ) ;
   |                                                    ^ missing tokens in macro arguments

error: unexpected end of macro invocation
  --> <::nom::branch::permutation_unwrap macros>:36:53
   |
36 | ( $ ( $ parsed ) , * , res . unwrap (  ) ) , $ res , $ ( $ rest ) * ) ) } else
   |                                                     ^ missing tokens in macro arguments

error: unexpected end of macro invocation
  --> <::nom::sequence::tuple_parser macros>:20:32
   |
20 | i_ , ( $ ( $ parsed ) * , o ) , $ ( $ rest ) * ) } ) } ) ; (
   |                                ^ missing tokens in macro arguments

```

Example test case:

```
// using Rust2018
#![feature(custom_attribute)]
use nom::*;

fn main() {
    match foobar("(test)") {
        Ok(res) => {
            assert_eq!(res.1, "");
        }
        Err(error) => panic!("{:?}", error)
    }
}

named!(pub comma<&str, &str>, eat_separator!(","));
named!(pub parse_bar<&str, &str>, tag_s!("bar"));
named!(pub parse_baz<&str, &str>, tag_s!("baz"));

named!(foobar<&str, &str>,
    delimited!(
        tag_s!("{"),
        sep!(comma, permutation!(
            parse_bar,
            parse_baz,
            // operation,
        )),
        tag_s!("}"),
    )
);
```

**Comment by Geal** [comment]
I thnk that's because `permutation` will not accept a trailing comma, so removing the comma after `parse_baz` should fix it
