### ISSUE TITLE
How do I document a named! parser?

### ISSUE THREAD

**Issue by leo60228** [Geal/nom#868]
## Prerequisites

Here are a few things you should provide to help me understand the issue:

- Rust version : `rustc -V` 1.31.0
- nom version : 4.2
- nom compilation features used: none

## Test case

Please provide a short, complete (with crate import, etc) test case for
the issue, showing clearly the expected and obtained results.

Example test case:

```rust
#[macro_use]
extern crate nom;

/// description
/// 
/// # Examples:
/// ```
/// assert_eq!(2, 3);
/// ```
named!(pub example, take!(0));
```

`cargo test` will succeed.

**Comment by Geal** [comment]
You can add documentation with the `named_attr` macro: https://docs.rs/nom/4.2.2/nom/macro.named_attr.html
