### ISSUE TITLE
Unsure how to match either

### ISSUE THREAD

**Issue by spease** [Geal/nom#873]
I need to match `-[0-9]`

Currently, I have:
```
preceded!(tag!("S"), nom::digit)
```

It looks like there's a take_until_either!, but no take_while_either!. Maybe there should be take_until! and take_while! and then an either! combinator?

**Comment by Geal** [comment]
yes, you can try with take_while

**Comment by spease** [comment]
So I guess it needs to be a lambda that returns true/false and has an input of u8 then?

I think you can close this, thanks.
