### ISSUE TITLE
More human-readable error messages

### ISSUE THREAD

**Issue by spease** [Geal/nom#875]
One thing I feel like is missing is more human-readable error messages. EG:
```
Got 'abc', expected digit.
```

Perhaps more complex structures could even construct error messages:
```
Got 'abc', expected at least 1 either digit or "None".
```

Even if these weren't perfect, it would still be better than just dropping the input string and position information out. This would be very useful for parsers on user input, since then the error message could be provided to the user directly. With the current approach, I'm not sure how you'd deal with user error messages without splitting up your parsers to miniscule sizes to roll your own error messages.

**Comment by Geal** [comment]
those error messages do not make sense in the general case, so nom is designed to let the user make their own error messages
