### ISSUE TITLE
Add FromStr example, possibly macro

### ISSUE THREAD

**Issue by spease** [Geal/nom#876]
I think this is useful enough to warrant a separate ticket.

One thing I wish for almost every time I use nom is having a way to implement core::str::FromStr using a nom parser. Ideally, it'd be nice if the FromStr implementation could still be changed in other nom parsers.

As it is, I usually end up defining my own macro for the project, manually implementing it, or just never get around to it.

I tried hacking it with named! myself tonight, but I had to back out ultimately because I couldn't figure out how to get the lifetime correct and/or use it in a different nom parser. Eg in this case I had a nom parser for an enum, and then I wanted to have a parser for a vector of those enums.

One possible way to do this would be to have a `from_str!(Type, ...)` macro (better name pending) that does a 'correct' implementation of FromStr for that type. Since FromStr is a core part of the language, I think special treatment can be justified.

**Comment by Geal** [comment]
I'll think about it for nom 5

**Comment by Geal** [comment]
added in a70d3f6

**Comment by spease** [comment]
Cool, thanks!

**Comment by detly** [comment]
Sorry, where is this?

**Comment by Geal** [comment]
Here: https://github.com/Geal/nom/blob/82309d2fa5da06ccb6301c5cff10d579aebffa15/doc/nom_recipes.md#L247

**Comment by detly** [comment]
Ah thanks! I was actually looking for something the other way around, but I might file a feature request.
