### ISSUE TITLE
Generate macro's as "backend"

### ISSUE THREAD

**Issue by flip111** [Geal/nom#880]
Would it be possible to instead of parsing things on run time, to let nom generate code for macro's that implement some DSL?

**Comment by Geal** [comment]
I'm sorry, I did not understand the question

**Comment by flip111** [comment]
Sorry i didn't notice your question before. So i will attempt to describe it in some pseudo code

For example if you want the macro
```rust
macro_rules! my_vec {
  ($($x: expr),*) => {{
    let mut vector = Vec::new();
    $(vector.push($x);)*
    vector
  }}
}
```

taken from https://hub.packtpub.com/creating-macros-in-rust-tutorial/

and instead of writing the macro manually it could be done with combinatos. In pseudo code:
```
name = "my_vec"
start = "let mut vector = Vec::new();"
item_start = "$(vector.push("
item_stop = ");)*"
stop = "    vector
  }}
}"

|name, start, item_start, item_stop| + "macro_rules! " + name + " {
  ($($x: expr),*) => {{
    " + start + map_res!(many0!(/* some number */), |val| item_start + |val| + item_stop) + stop
```

The benefit of this is that if you define some DSL for runtime it now also works on compile time and you can mix it with your rust code.

**Comment by Geal** [comment]
I still do not understand. What is the use case?

**Comment by flip111** [comment]
I started to type some more explanation. But after writing three paragraphs i felt that i just couldn't explain myself clearly enough. I know what i want, but i can't explain it right now technically. So i will get back to this later when i have a better idea of the pieces involved. Thank you
