### ISSUE TITLE
Compilation issue with i128 support in nom >= 4.2.0

### ISSUE THREAD

**Issue by tonyvelichko** [Geal/nom#884]
Hi guys. I've found an issue while updating nom to the latest version. I have rustc 1.35.0 and when I update nom version to greater than 4.1.1 all i128 related macros and functions are not available, and of course, it breaks up my compile. 
I investigate a bit and found the following:
1. Downloaded nom crate sources don't have build.rs file (checked in cargo cache). 
2. In nom >= 4.2.0 was added a #[cfg(stable_i128)] to all i128 related macros and functions.
3. Configuration for i128 is defined in build.rs which is not shipped within the crate. 

So, no matter which version of rustc you are using, all i128 related functions will not be available anyway.

**Comment by Geal** [comment]
thank you for the report, I just published version 4.2.3 which includes the `build.rs` file, that should fix the issue

**Comment by tonyvelichko** [comment]
Just checked version 4.2.3, this issue no longer arise. Thanks for your support.
