### ISSUE TITLE
Wrong error when using commas in alt

### ISSUE THREAD

**Issue by pythondude325** [Geal/nom#890]
When using commas as the separator in alt! the compiler should throw `alt uses '|' as separator, not ','`, but instead throws ``could not find `compile_error` in $crate``. I think this related to #862 (~ in do_parse) so there could be more occurrences of this issue.

## Prerequisites

- Rust version : rustc 1.34.0-nightly (e3428db7c 2019-03-31)
- nom version : 4.2.3
- nom compilation features used: default

## Test case

```
#[macro_use]
extern crate nom;

named!(multi<&[u8], &[u8]>,  alt!(tag!("a"), tag!("b")));
```

Expected Error: `alt uses '|' as separator, not ','`
Actual Error: ``could not find `compile_error` in $crate``

**Comment by Geal** [comment]
this is fixed in nom 5 that I'll release soon
