### ISSUE TITLE
port sequence combinators to the new design

### ISSUE THREAD

**Issue by Geal** [Geal/nom#899]
for most cases this is not too useful since we can just write a parser function in imperative style, but applying a tuple of parsers in order could still be interesting. The code is in `src/sequence/macros.rs`. To rewrite:
- `tuple`
- `do_parse`: is it necessary?

**Comment by Evelyn-H** [comment]
My two cents; I feel like keeping the number of macros/combinators to a minimum would be a good thing. One of the things that made it harder for me to get used to the library initially was the vast amount of macros that all looked very similar at a first glance. Though this might already be better if there's better documentation in 5.0.

**Comment by Geal** [comment]
I want to remove a few combinators, and I'll separate functions in more modules. A big issue with macros was that they are all at the top level, so we often have to look them up in alphabetical order. functions can have a more coherent organization.

**Comment by Geal** [comment]
the methods combinators and whitespace combinators will move out in other crates, I don't know yet about others

**Comment by Geal** [comment]
all the sequence combinators are now ported to functions. the `tuple` combinator stays in macro form, but there is a function version
