### ISSUE TITLE
Additional Input for Parsers

### ISSUE THREAD

**Issue by Binero** [Geal/nom#90]
A parser might need more input than just what it's parsing. At the moment there doesn't seem to be a way to supply additional input to one. 

An example use case is, in our parser library, we want to have the parser fill a vector we supply to it with the data it parses. At the moment, it seems we are forced to have the parser return a vector, and then merge it with an existing one.

**Comment by Geal** [comment]
hi!

Could you tell me more about your use case? Isn't `Incomplete` doing what you need? Parsers are simple functions, they do not keep state. I'm working on other layers to build state machines around the parsers.

**Comment by Binero** [comment]
I would like my parser to add what it reads to a vector, and then just return the updated vector. It's not like I need it to get state. 

For example with the INI example, I would like to supply a has map to add things to as opposed to generate a new none. As such I need to pass it a map/vector to add to.

**Comment by Geal** [comment]
you can make a parser like that by avoiding the `named!` combinator and writing the function definition manually, like this:

```rust
fn parse(input: &[u8], acc: &mut Vec<Something>) -> IResult<&[u8], &mut Vec<Something>> {
...
}
```

The current implementation of `many0!` and `many1!` do not support modifying a vector passed as parameter, but it should be doable (see https://github.com/Geal/nom/blob/master/src/macros.rs#L1415-L1433 ).

**Comment by Binero** [comment]
That seems like a good work-around. Thanks!
