### ISSUE TITLE
blanket implementations of ParseError

### ISSUE THREAD

**Issue by Geal** [Geal/nom#900]
to avoid orphan instances with `ParseError`, we should have predefined implementations for common error types people might use. Right now I see:
- `(Input, ErrorKind)`(which is the default error type)
- `()`
anything else?

**Comment by Geal** [comment]
the first exists, but you're free to do the second :)
Any idea of other common error types someone could use?

**Comment by loewenheim** [comment]
I did the one for `()`, should I open a PR? And as for other common error types, I have no idea, sorry :(

**Comment by Geal** [comment]
sure, please do :)
