### ISSUE TITLE
proper implementation of float and double parsers from text representation

### ISSUE THREAD

**Issue by Geal** [Geal/nom#902]
right now we use `recognize_float` then call `.parse::<f64>()` on the recognized input, which means the data is parsed twice. It is necessary because `parse()` assumes it has the full input, and will not return remaining input data if there is some after the number. This is the main reason for serde being faster than nom on JSON benchmarks: serde constructs the number as it is parsing it.
We need a float parser that does that.

**Comment by pickfire** [comment]
What about parsing something like `0.01f32` as seen in rust?

**Comment by Geal** [comment]
@pickfire not really in scope. Anyone can implement that by writing `terminated(float, tag("f32"))`

**Comment by Geal** [comment]
nom 5 will now use the lexical-core crate to parse float since 40f20aa070c
