### ISSUE TITLE
How to tell whether input has been consumed?

### ISSUE THREAD

**Issue by loewenheim** [Geal/nom#908]
Some of the combinators in https://github.com/Geal/nom/blob/5.0/src/multi/mod.rs need to be able to tell whether a subparser actually consumes any of its input because they run it in a loop and would otherwise get stuck. How this is done is a bit inconsistent; sometimes, the input before and after the argument parser is compared by length and sometimes just with `==`. Which of these is better? Is there perhaps a completely different way to do it?

**Comment by Geal** [comment]
It should be fine to replace with equality in all cases, because we might encounter cases where length comparison does not make sense, like an input type that can read more from a file if needed.
This will add `PartialEq` as requirement on the input type of those combinators, but it's ok.

**Comment by loewenheim** [comment]
Ok, I’ll use `PartialEq`.
