### ISSUE TITLE
nom 5 code level documentation

### ISSUE THREAD

**Issue by Geal** [Geal/nom#914]
this new version introduces a lot more combinators and parsers:
- the existing macros combinators
- the streaming related function combinators (usually in `src/<module>/streaming.rs`)
- the complete input related function combinators (usually in `src/<module>/complete.rs`)
- the more general combinators (usually in `src/<module>/mod.rs`)

So in a lot of cases, we have three versions: macro, streaming and complete. Users should be able to understand quickly which one they need, without being overwhelmed by their number (I'm in the process of removing some of them).

Here is the format I'd like for most documentation entries:

```
/// Recognizes one character  <-- short, one line description for the function or macros list
///
/// the input data will be compared to the char combinator's argument, and it will return a `char` if successful <-- longer description if the function is confusing
///
/// *streaming version*: will return `Err(nom::Err::Incomplete(_))` if there's not enough input data <-- additional information for streaming or complete version. For complete: *complete version*: will return an error if there's not enough input data
///
/// ```rust
//  # <-- use this syntax to hide the boilerplate
/// # #[macro_use] extern crate nom;
/// # use nom::{Err,error::ErrorKind};
/// use nom::character::streaming::char;
/// # fn main() {
/// let parser = |s: &str| {
///   char('a')(s);
/// };
///
/// short examples with assertions for main cases:
/// - valid input
/// - invalid input
/// - what happens if the parser reaches the end of input (different behaviour for streaming/complete)
/// 
/// assert_eq!(match_letter_a("abc"), Ok(("bc", 'a')));
/// assert_eq!(match_letter_a(b"123cdef"), Err(Err::Error(error_position!(&b"123cdef"[..], ErrorKind::Char))));
/// assert_eq!(match_letter_a(""), Err(Err::Incomplete(Needed::Size(1)));
/// # }
/// ```
```

A lot of macros are already documented, but not all of them, and their docs are often confusing, so they need a fresh eye.

I added `#![warn(missing_docs)]` and `#![warn(missing_doc_code_examples)] `, so to know where to look, clone the repo, launch a compilation and look for the warnings :)

**Comment by lu-zero** [comment]
Could you please make a project with small issues and tick-boxes ? ^^

**Comment by Geal** [comment]
I felt the itch to do it but did not have the time to write it
unfortunately :(

**Comment by lu-zero** [comment]
I guess I can help on that then :P

**Comment by GuillaumeGomez** [comment]
To be sure you don't have an item without doc examples, you can also add `#![deny(missing_doc_code_examples)]`. :)

**Comment by GuillaumeGomez** [comment]
Oh also, I'm currently doing `character/complete.rs` (to avoid contributing on the same things...).

**Comment by lu-zero** [comment]
@GuillaumeGomez I made [this](https://github.com/Geal/nom/issues/915) to start tracking.

**Comment by Waelwindows** [comment]
We should update this issue to show the change from using closures to functions.
```rust
fn parser(s: &str) -> IResult<&str, char> {
  char('a')(s)
}
```

**Comment by jlgerber** [comment]
cheers on nom5 looking to be a leap forward in usability. I did notice that the doc examples don't compile if you try and use them by cut and pasting, which is how people will most likely try and learn nom. 

For example, if i cut and paste the tuple example into a fresh cargo project, i get an error about :
```
error[E0283]: type annotations required: cannot resolve `_: std::clone::Clone`
  --> src/main.rs:39:19
   |
39 |     let parser = tuple((alpha1, digit1, alpha1));
   |                   ^^^^^
   |
   = note: required by `nom::sequence::tuple
```

**Comment by Geal** [comment]
@jlgerber the documentation page shows that tuple is generic over the input type, and if you just write `let parser = tuple((alpha1, digit1, alpha1));` without calling `parser`, the compiler has no way to know which input type you want to use. If you copy the last 2 lines of the example it will build properly

**Comment by Geal** [comment]
closing this since the documentation effort for nom 5 is finally done 🍾
