### ISSUE TITLE
Stuck on Incomplete with take_while_m_n

### ISSUE THREAD

**Issue by ianks** [Geal/nom#919]
## Prerequisites

Here are a few things you should provide to help me understand the issue:

- Rust version : `rustc 1.36.0-nightly (6d599337f 2019-04-22)`
- nom version `5.0.0-alpha1:
- nom compilation features used:

## Test case

Hi there! I am having a lot of trouble parsing a variable length string of digits. Essentially, I cannot get pas the error of `Err(Incomplete(Size(1)))` when using `take_while_m_n!` and using an inexact `m` and `n`. If I use the exact size of the test case, it passes! Unfortuantely, it would then be invalid for real world data :sad:

Can someone guide me in the write direction here? thank you so much!

Example test case:

```rust
#[derive(Debug, PartialEq)]
pub struct TransactionSetHeader<'a> {
    pub transaction_set_identifier_code: &'a str,
    pub transaction_set_control_number: &'a str,
}

#[allow(dead_code)]
fn from_str(input: &[u8]) -> Result<&str, &str> {
    Ok(std::str::from_utf8(input).unwrap().trim())
}

named!(take_cell, take_until_and_consume!("*"));

### HAVING TROUBLE HERE
named!(take_control_number<&[u8], &str>, map_res!(take_while_m_n!(4, 9, nom::character::is_digit), std::str::from_utf8));

### THIS WORKS!?
# named!(take_control_number<&[u8], &str>, map_res!(take_while_m_n!(5, 5, nom::character::is_digit), std::str::from_utf8));
named!(cell<&[u8], &str>, map_res!(take_cell, from_str));

named!(pub transaction_set_header<&[u8], TransactionSetHeader>,
   do_parse!(
     tag!("ST*") >>
     transaction_set_identifier_code: cell >>
     transaction_set_control_number: take_control_number >>
     (
       TransactionSetHeader {
         transaction_set_identifier_code,
         transaction_set_control_number,
     }
     )
  )
);

#[cfg(test)]
use pretty_assertions::assert_eq;

#[test]
fn parse_isa_header() {
    let value = "ST*832*10001".as_bytes();

    assert_eq!(
        transaction_set_header(value),
        Ok((
            "".as_bytes(),
            TransactionSetHeader {
                transaction_set_identifier_code: "832",
                transaction_set_control_number: "10001",
            }
        ))
    );
}
```

**Comment by Geal** [comment]
`take_while_m_n` works in streaming mode, so here, if you want to parse a slice of 4 to 9 digits, here's the behaviour to expect:
- `10001;`: will recognize `10001` and leave the `;`
- `1234567890`: will recognize `123456789` and leave the `0`
- `10001`: returns `Incomplete` because we do not know if there will be more data coming

With nom 5, you can use another version of `take_while_m_n` that is in `nom::bytes::complete::take_while_m_n`. It is a function instead of a macro though. But for `10001` as input, it will properly recognize `10001`
