### ISSUE TITLE
print_offsets is not String safe -- invokes undefined behavior

### ISSUE THREAD

**Issue by bluss** [Geal/nom#92]
`print_offsets` and `HexDisplay::to_hex_from` don't look like they are string safe. They assume the `&[u8]` input is valid utf-8 (and may slice codepoints of valid utf-8, too I guess).

Testcase: `nom::print_offsets(&[0xff; 37], 0, &Vec::new())` produces an invalid `String`.

None of the print / output related unsafe blocks look performance critical, so I'd recommend switching to safe rust for this.

**Comment by bluss** [comment]
Also remember that you may "slice codepoints" anywhere you insert color control chars that appear inside an encoding sequence for a codepoint.

**Comment by Geal** [comment]
Yes, that is an issue I encountered a few times, and I don't know yet how I should handle it. Since every line is limited, it's not an issue most of the time, but it really does not look nice.

The utf-8 assumption is best effort: you don't know if the data you display is a valid utf-8 string, you just try to show as much as possible.

Are there hexdump programs that handle utf-8 characters correctly? Or do they just show the ascii ones?

**Comment by bluss** [comment]
I want to point out that invalid data (not UTF-8) in String is not optional. It's [undefined behavior](http://doc.rust-lang.org/reference.html#behavior-considered-undefined) and breaks rust's safety guarantees. This is why I urge you to use safe code.

Use String::to_string_lossy for now, but there is room to do something smart for sliced codepoints. I'd render their bytes using just `.` like the nonprintables, if they are sliced.

**Comment by Geal** [comment]
At last, it is done :)

If you have other suggestions like those, I'll be happy to fix nom!

**Comment by bluss** [comment]
This concluded the auditing of all `unsafe`-marked sections in nom, so that's nice.

Doing print_offsets well for unicode text sounds like an interesting project, I'm tempted, but I don't have the time.

**Comment by Geal** [comment]
There are three `unsafe` parts remaining, one for an array memory intialization (I think there's a better way to do it now), and two for casts to floats.

**Comment by bluss** [comment]
Yes I've looked at all of them, and submitted a PR for the array memory initialization already.
