### ISSUE TITLE
IResult::Incomplete parameter type

### ISSUE THREAD

**Issue by rhoark** [Geal/nom#95]
According to the docs, IResult::Incomplete is constructed with an i32, but it seems to actually want an instance of enum Needed, which is private. Probably misunderstanding on my part, but I'm stuck as to how to return an Incomplete.

**Comment by Geal** [comment]
I probably forgot to update that part of the docs. Is that in the readme? You can find the enum as `nom::Needed`. It has two variants: `Unknown` (when we know we need more data but don't know how much) and `Size(usize)` (when we know how much).

**Comment by Geal** [comment]
Now the README contains the correct info, since 9b71164. Thank you for pointing it out!
