### ISSUE TITLE
How to get a permutation of many0 items

### ISSUE THREAD

**Issue by tversteeg** [Geal/nom#951]
## Prerequisites

- Rust version:  rustc 1.37.0-nightly
- nom version: 5.0.0-beta2
- nom compilation features used: std

## Test case

```rust
#[macro_use]
extern crate nom;

use nom::{
    IResult,
    multi::many0,
    bytes::complete::tag,
    branch::permutation,
    sequence::pair
};

fn list1(i: &str) -> IResult<&str, Vec<&str>> {
    many0(tag("AA"))(i)
}

fn list2(i: &str) -> IResult<&str, Vec<(&str, &str)>> {
    many0(pair(tag("B"), tag("B")))(i)
}

fn list3(i: &str) -> IResult<&str, Vec<&str>> {
    many0(tag("CC"))(i)
}

fn perm(i: &str) -> IResult<&str, (Vec<&str>, Vec<(&str, &str)>, Vec<&str>)> {
    permutation((list1, list2, list3))(i)
}

fn main() {
    let i = "BBAABBBBAA";
    let (list1, list2, list3) = perm(i).unwrap().1;
    assert_eq!(list1, vec!["AA", "AA"]);
    assert_eq!(list2, vec![("B", "B"), ("B", "B"), ("B", "B")]);
    assert_eq!(list3, Vec::<&str>::new());
}
```
Fails with at the first `assert_eq!`:
```
left: `[]`,
right: `["AA", "AA"]`
```

## Question

I'm trying to get a `permutation` of different `many0` arrays where the arrays have different return values. So basically all the options of the permutation are optional but should match as much as possible. 
Shouldn't at least `vec!["AA"]` be returned in the example? Am I making in error in my reasoning or is this a bug?

**Comment by frehberg** [comment]
Hi,  instead of using "many0", I would define an iterator consuming token by token from the input sequence, check the iterator-example for this https://github.com/Geal/nom/blob/master/examples/iterator.rs 
And using "map!(..)" every  tokens might be an enum-variant, check  https://github.com/Geal/nom/blob/master/examples/json.rs#L132

**Comment by frehberg** [comment]
Define a Token type like this one, and each parser of list1, list2 or list3 shall return one of those variants (using map!()) , this way it should be possible to permute them and getting a single return list with mixed token.

(pseudo code)
```
enum Token<'t> {
  ManyAA(&'t str),
  ManyBBPair(&'t str),
  ManyCC(&'t str),
}
```

**Comment by tversteeg** [comment]
Thanks that might be helpful, isn't the empty array being returned at least a bug though?

**Comment by Geal** [comment]
I agree, using the iterator would work much better, the `permutation` combinator is not designed for this.
`many0` will accumulate 0 or more parsed values, so if it was not able to parse one, it returns the empty array. You might want `many1` instead
