### ISSUE TITLE
Request - simple lisp parsing example

### ISSUE THREAD

**Issue by bddap** [Geal/nom#952]
This would be helpful.

**Comment by Geal** [comment]
sorry, I do not have the time to work on this, but if you find or write a good one, I could add it to the list of examples

**Comment by MarkMcCaskey** [comment]
@bddap didn't see this before posting https://github.com/Geal/nom/issues/903#issuecomment-498422054 ; I made an s-expression parser using nom5 which is MIT licensed.

I'd be willing and able to contribute to a lisp parser example.  What exactly did you have in mind?  Something like S-expressions or a full parser for scheme or something?

**Comment by bddap** [comment]
Awesome! A very simple s-expression parser, something less than 100 lines, would make it easy to get started using nom. The json example is a good start, but an s-expr parser could be much simpler.

**Comment by MarkMcCaskey** [comment]
@bddap 
I just hacked out a little lisp https://github.com/MarkMcCaskey/nom/blob/master/examples/s_expression.rs ; I'm going to sleep now, but I'll add comments, clean it up, and make a PR tomorrow.
