### ISSUE TITLE
length_value macro assumes fixed size parsers

### ISSUE THREAD

**Issue by zokier** [Geal/nom#96]
In `length_value` macro, if second parser returns `Needed::Size(length)` then the macro returns `Needed::Size(length_token + length*number of items)`. This seems to assume that each iteration/item consumes equal amount of input, which seems fragile.

More correct implementation would have a counter which counts how many bytes are consumed on each iteration and use that value for calculating how many bytes are needed in total. If I'm not mistaken, this would make the macro significantly less efficient because it would cause the first items to be repeatedly parsed until the input buffer contains all the items.

**Comment by Geal** [comment]
Yes, the current implementation is a tradeoff. There may be a more flexible way to do it, though. Any ideas?

**Comment by zokier** [comment]
My personal preference would be to remove the macro in its current state, but I might be bit biased because I just happened to trip on it. But I don't think it can currently be implemented both so that it is generically correct and performant, with the way the parsers are structured currently. I'd love to be proved wrong.

One idea that comes to mind is somehow marking parsers that consume fixed amount of input in the type system so the compiler then could forbid using `length_value!` (and possibly others) with incompatible parsers. Not being exactly an expert on Rust, macros or parsers I don't know how feasible such idea is.

Another thing would be allowing parsers to store some state in themselves, so `length_value!` could store partially parsed results internally. Or maybe have some way of returning/handling partial results from parsers.

In any case the documentation for `length_value!` could certainly be improved to include a mention of the current limitation.

**Comment by cholcombe973** [comment]
I'm not sure if I've run into this also but I'm seeing the following:
```
src/serial.rs:3184:57: 3184:63 error: unexpected end of macro invocation
src/serial.rs:3184                     length_value!(le_u32, pair!(le_u64, le_u64))
```

I can't seem to combine length_value with a pair! parser.  It works if I don't use pair!

**Comment by Geal** [comment]
the `length_*` combinators changed behaviour in 2.0
