### ISSUE TITLE
`length_data` has same documentation as `length_value`

### ISSUE THREAD

**Issue by robojeb** [Geal/nom#979]
The wording of the documentation for `length_data` is identical to that of `length_value`. 

It looks like the example was updated but the `length_data` doc references a second parser which doesn't exist in the definition of that function. 

> Gets a number from the first parser, takes a subslice of the input of that size, then applies the second parser on that subslice.

Ideally the example for `length_data` would be updated to differentiate itself from `length_value`, currently they have identical output so it isn't obvious what their function is supposed to be. 

Perhaps the `length_data` example should do the following:

1) Grab a different number of bytes than the `length_value` 
2) Show two inputs, such that it shows it gets N bytes but doesn't care about the content of those bytes like `length_value` does.

**Comment by jameysharp** [comment]
I found this bug report while I was studying the implementation of these particular parsers. It looks to me like this documentation problem was fixed in 47306c48a44f16e46f5d1e28ed730b160070699c, which was included in nom 5.1.0. Is it still an issue?

**Comment by Geal** [comment]
you're right, it was already fixed
