### ISSUE TITLE
No version of dbg_dmp for &str?

### ISSUE THREAD

**Issue by qrilka** [Geal/nom#981]
I was following https://github.com/Geal/nom/blob/master/doc/error_management.md and tried to use `dbg_dmp` to debug my parser but couldn't as the function uses `&[u8]` and my parser reads `&str` - is this intended or maybe there is some way around this problem?

**Comment by rljacobson** [comment]
I was unable to use any of the debugging features. The lack of `&str` support is #613. Someone provides a workaround in a comment to that issue, but I couldn't get it to work. YMMV. 

An unpleasant workaround is to `map` each combinator you wish to trace with your own `trace` function that prints any relevant data at the time of the map. But at that point you might as well implement `dbg_dmp`.

Beware that much of the documentation is out of date after the 5.0.0 release. It is a major overhaul of the design, so it's understandable. The good news is, it appears that a lot of eyeballs are on this code base, so I'd guess that it will mature quickly. I wish I had time to help.

**Comment by qrilka** [comment]
Thanks, closing in favor of #613
