### ISSUE TITLE
many0 doesn't return results for alphanumeric0

### ISSUE THREAD

**Issue by tones111** [Geal/nom#982]
- Rust version : rustc 1.35.0 (3c235d560 2019-05-20)
- nom version : 5.0.0
- nom compilation features used: none (default)

I'm having trouble understanding why the test using alphanumeric1 passes but fails when using alphanumeric0

```
extern crate nom;
use nom::{
    character::complete::{alphanumeric0, alphanumeric1},
    multi::many0,
    IResult,
};

fn parser0(s: &str) -> IResult<&str, Vec<&str>> {
    many0(alphanumeric0)(s)
}

fn parser1(s: &str) -> IResult<&str, Vec<&str>> {
    many0(alphanumeric1)(s)
}

#[test]
fn test_parser0() {
    assert_eq!(parser0("abc"), Ok(("", vec!["abc"])));
}

#[test]
fn test_parser1() {
    assert_eq!(parser1("abc"), Ok(("", vec!["abc"])));
}
```

The issue seems to be at src/multi/mod.rs:47 (version 5.0.0) where once all of the valid input has been pushed into acc i1 == i and many0 returns an error.  I would expect to get the acc vector that has one element.  Shouldn't it always return acc since no results is valid?  It looks like many1 uses a similar pattern after finding the first result.

**Comment by Geal** [comment]
`alphanumeric0` will succeed even if there's no more input, while `alphanumeric1` must parse at least one char to succeed.
If you pass to `many0` a parser that can succeed without consuming i put, it can result into an infinite loop, that's why `many0` has this check

**Comment by tones111** [comment]
Sure, but I would still expect it to make progress when possible.

Thanks for the v5 release.  I've found debugging to be a much more pleasant experience.

**Comment by shages** [comment]
I ran into a similar issue. The parser I passed to `many0` would indeed succeed without consuming input, which I didn't intend and fixed. I like this behavior, but the cause of the error wasn't obvious to me while debugging. Maybe an example could be added to the `many0` docs?

```rust
use nom::character::complete::alphanumeric0;
use nom::error::ErrorKind;

// This parser would result in an infinite loop, which is detected and instead returns an error
fn parser_infinite(s: &str) -> IResult<&str, Vec<&str>> {
    many0(alphanumeric0)(s)
}

assert_eq!(parser_infinite("abc"), Err(Err::Error(("", ErrorKind::Many0))));
```

I'm new to Rust, and I've really enjoyed using `nom`. Thanks for the awesome library!

**Comment by Geal** [comment]
yes, the documentation should make it very clear that parsers accepting empty input should not be passed to many0 and many1, I'll add that

**Comment by Geal** [comment]
I added more info in ab8277d
