### ISSUE TITLE
Unable to build for thumbv7em_none_eabi (no_std target)

### ISSUE THREAD

**Issue by jeffreydecker** [Geal/nom#983]
- Rust version : rustc 1.35.0 (3c235d560 2019-05-20)
- nom version : 4.0.0 and 5.0.0
- nom compilation features used: default-features = false

I'm looking to use nom to build a parser for my embedded project. The problem that I've run into however is that even with `default-features = false` I get the following error when I try to build:

```
error[E0463]: can't find crate for `std`
  |
  = note: the `thumbv7em-none-eabi` target may not be installed
```

If I remove nom as a dependency everything is happy again.

From what I can tell nom should usable with `no_std` but sadly, I don't seem to be able to. Maybe it's specific to the `thumbv7em_none_eabi` target? I run into this issue if I use version 4.0.0 or 5.0.0.

**Comment by Geal** [comment]
Could you show me a test case? Especially, the content of your Cargo.toml, which toolchain and which command you use to build

**Comment by Geal** [comment]
closing this for now, feel free to reopen if you get more information
