### ISSUE TITLE
Ability to provide custom "expected" error messages

### ISSUE THREAD

**Issue by netvl** [Geal/nom#989]
At the moment, it seems that it is not really possible to add customized errors when using default error types (at least since nom 5.0; from what I understood when reading various issues here, it seems there was some support for custom error types, but it looks like it was dropped).

For example, when I run my parser with the `VerboseError` error type, I get messages which look like this:
```
0: at line 0, in Verify:
<abc:def:hij/>
        ^

1: at line 0, in attribute:
<abc:def:hij/>
        ^

2: at line 0, in start tag:
<abc:def:hij/>
^

3: at line 0, in before doctype:
<abc:def:hij/>
^

4: at line 0, in before declaration:
<abc:def:hij/>
^
```
which does seem nice, but I would like to be able to provide more context. In this example, I would like to add a more detailed message like this:
```
0: at line 0, in Verify:
<abc:def:hij/>
        ^
Unexpected character ':'
```

From what I saw in the source code, in particular, for `VerboseError`, it seems that it has some of the common cases hardcoded there (e.g. if I used the `char` parser, it would provide an error message about the expected character; but for virtually any other parser there would be no details). It does not seem possible to add any custom messages aside from implementing the `ParseError` trait, which I would really like to avoid.

Maybe appending some details could be done by providing another combinator, say, `extended_context`, which would look like this:
```rust
let name_start = extended_context(
  "name start",
  char_matching(|c| is_name_start_char(c) && c != ':'),
  "Expected a name start character which is not ':'"
);
```
? This is just an idea, and it would probably require some changes to the `ParseError` trait, but it seems to be a straightforward way to add such context to errors.

More generally, is there some suggested approach for doing custom error messages in nom 5+? It seems that previously custom errors could be done much simpler than now, or maybe I'm missing something?

**Comment by Geal** [comment]
the `ParseError` trait provides common tools to build errors, and most of nom uses it to add context, but nothing is preventing you from making an error type that supports other patterns, like the extended context you are talking about, as long as it also supports `ParseError` (the trait is really simple to implement, you don't need to do all of the methods).
Custom errors in previous versions were creating issues with type inference, and it was hard to do anything interesting without spending a lot of time converting between error types.
With the new design, there are two basic error types that are limited, but any error type can be used instead, without type inference issue, only a trait requirement.
I'm planning to add more features to ParseError, but not in the near future, I first want to see what will be really needed, and what can be implemented outside of nom.
