### ISSUE TITLE
Issue with parsers that return generics

### ISSUE THREAD

**Issue by zrneely** [Geal/nom#99]
(Let me preface this by saying that it might well be a bug in Rust's macro parser, or that I may just be doing something wrong. I'm not very familiar with this library, so I may have missed something.)

The following produces a compile-time error, which is unexpected:
        
    #[macro_use]
    extern crate nom;
    use nom::*;

    use std::str;

    named!(sample_parser<Vec<&str>>, many0!(
            map_res!(
                delimited!(opt!(multispace), alpha, opt!(multispace)),
                str::from_utf8
            )
        )
    );

    fn main() {
        let result = sample_parser(b"abc def");
        println!("{:?}", result);
    }

The error is:

    src/main.rs:8:22: 8:25 error: expected an item keyword
    src/main.rs:8 named!(sample_parser<Vec<&str>>, many0!(
                                       ^~~
    
The same thing happens with `String` instead of `&str`. Adding a space between the closing angle brackets in the parser's return type corrects the error, and the parser works as expected.

    named!(sample_parser<Vec<&str> >, many0!(

I don't think that space is supposed to be necessary.

**Comment by Geal** [comment]
This is indeed caused by the macro parser, because `>>` is an operator. Unfortunately, there is nothing I can do here, except documenting it somewhere :(

**Comment by Geal** [comment]
Hi, I documented the issue in 038190e.
