### ISSUE TITLE
Alt with more than 21 elements

### ISSUE THREAD

**Issue by rgiot** [Geal/nom#994]
In nom 5.0, the `alt` function is limited to 21 elements.
In my use case, I have far more elments that that.
What is the best strategy to handle this case without manually generating larger cases ?

On my side I may code a function fed with a slice of combinators, but maybe nom deserves such kind of function.

**Comment by Havvy** [comment]
Can you put another alt as an element of the alt?

**Comment by rgiot** [comment]
@Havvy Indeed I have finally solved my issue with this trick instead of written another function. The issue is that I had to do it manually

**Comment by Geal** [comment]
unfortunately, to implement `alt` I had to choose an arbitrary limit to the number of parsers. I could raise that number, but there will always be someone who runs into the limit. Meanwhile, `alt` is associative, so it's easy to combine multiple `alt` parsers
